/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdoptionApproval,
  AdoptionApprovalAdoptionApprovalInput,
  ConstraintViolation,
} from '../models/index';
import {
    AdoptionApprovalFromJSON,
    AdoptionApprovalToJSON,
    AdoptionApprovalAdoptionApprovalInputFromJSON,
    AdoptionApprovalAdoptionApprovalInputToJSON,
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
} from '../models/index';

export interface AdoptionApprovalsDecideRequest {
    adoptionApprovalAdoptionApprovalInput: AdoptionApprovalAdoptionApprovalInput;
}

export interface AdoptionApprovalsGetRequest {
    id: string;
}

export interface AdoptionApprovalsListRequest {
    page?: number;
}

export interface AdoptionApprovalsWithdrawRequest {
    id: string;
}

/**
 * 
 */
export class AdoptionApprovalApi extends runtime.BaseAPI {

    /**
     * Creates a AdoptionApproval resource.
     * Creates a AdoptionApproval resource.
     */
    async adoptionApprovalsDecideRaw(requestParameters: AdoptionApprovalsDecideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdoptionApproval>> {
        if (requestParameters['adoptionApprovalAdoptionApprovalInput'] == null) {
            throw new runtime.RequiredError(
                'adoptionApprovalAdoptionApprovalInput',
                'Required parameter "adoptionApprovalAdoptionApprovalInput" was null or undefined when calling adoptionApprovalsDecide().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/adoption_approvals`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdoptionApprovalAdoptionApprovalInputToJSON(requestParameters['adoptionApprovalAdoptionApprovalInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdoptionApprovalFromJSON(jsonValue));
    }

    /**
     * Creates a AdoptionApproval resource.
     * Creates a AdoptionApproval resource.
     */
    async adoptionApprovalsDecide(requestParameters: AdoptionApprovalsDecideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdoptionApproval> {
        const response = await this.adoptionApprovalsDecideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a AdoptionApproval resource.
     * Retrieves a AdoptionApproval resource.
     */
    async adoptionApprovalsGetRaw(requestParameters: AdoptionApprovalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdoptionApproval>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adoptionApprovalsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/adoption_approvals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdoptionApprovalFromJSON(jsonValue));
    }

    /**
     * Retrieves a AdoptionApproval resource.
     * Retrieves a AdoptionApproval resource.
     */
    async adoptionApprovalsGet(requestParameters: AdoptionApprovalsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdoptionApproval> {
        const response = await this.adoptionApprovalsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the collection of AdoptionApproval resources.
     * Retrieves the collection of AdoptionApproval resources.
     */
    async adoptionApprovalsListRaw(requestParameters: AdoptionApprovalsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdoptionApproval>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/adoption_approvals`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdoptionApprovalFromJSON));
    }

    /**
     * Retrieves the collection of AdoptionApproval resources.
     * Retrieves the collection of AdoptionApproval resources.
     */
    async adoptionApprovalsList(requestParameters: AdoptionApprovalsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdoptionApproval>> {
        const response = await this.adoptionApprovalsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the AdoptionApproval resource.
     * Removes the AdoptionApproval resource.
     */
    async adoptionApprovalsWithdrawRaw(requestParameters: AdoptionApprovalsWithdrawRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling adoptionApprovalsWithdraw().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/adoption_approvals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the AdoptionApproval resource.
     * Removes the AdoptionApproval resource.
     */
    async adoptionApprovalsWithdraw(requestParameters: AdoptionApprovalsWithdrawRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.adoptionApprovalsWithdrawRaw(requestParameters, initOverrides);
    }

}
