/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdoptionApproval,
  AdoptionApprovalAdoptionApprovalInput,
  ConstraintViolation,
} from '../models/index';
import {
    AdoptionApprovalFromJSON,
    AdoptionApprovalToJSON,
    AdoptionApprovalAdoptionApprovalInputFromJSON,
    AdoptionApprovalAdoptionApprovalInputToJSON,
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
} from '../models/index';

export interface ApiAdoptionApprovalsGetCollectionRequest {
    page?: number;
}

export interface ApiAdoptionApprovalsIdDeleteRequest {
    id: string;
}

export interface ApiAdoptionApprovalsIdGetRequest {
    id: string;
}

export interface ApiAdoptionApprovalsPostRequest {
    adoptionApprovalAdoptionApprovalInput: AdoptionApprovalAdoptionApprovalInput;
}

/**
 * 
 */
export class AdoptionApprovalApi extends runtime.BaseAPI {

    /**
     * Retrieves the collection of AdoptionApproval resources.
     * Retrieves the collection of AdoptionApproval resources.
     */
    async apiAdoptionApprovalsGetCollectionRaw(requestParameters: ApiAdoptionApprovalsGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdoptionApproval>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/adoption_approvals`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdoptionApprovalFromJSON));
    }

    /**
     * Retrieves the collection of AdoptionApproval resources.
     * Retrieves the collection of AdoptionApproval resources.
     */
    async apiAdoptionApprovalsGetCollection(requestParameters: ApiAdoptionApprovalsGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdoptionApproval>> {
        const response = await this.apiAdoptionApprovalsGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the AdoptionApproval resource.
     * Removes the AdoptionApproval resource.
     */
    async apiAdoptionApprovalsIdDeleteRaw(requestParameters: ApiAdoptionApprovalsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAdoptionApprovalsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/adoption_approvals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the AdoptionApproval resource.
     * Removes the AdoptionApproval resource.
     */
    async apiAdoptionApprovalsIdDelete(requestParameters: ApiAdoptionApprovalsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiAdoptionApprovalsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a AdoptionApproval resource.
     * Retrieves a AdoptionApproval resource.
     */
    async apiAdoptionApprovalsIdGetRaw(requestParameters: ApiAdoptionApprovalsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdoptionApproval>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiAdoptionApprovalsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/adoption_approvals/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdoptionApprovalFromJSON(jsonValue));
    }

    /**
     * Retrieves a AdoptionApproval resource.
     * Retrieves a AdoptionApproval resource.
     */
    async apiAdoptionApprovalsIdGet(requestParameters: ApiAdoptionApprovalsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdoptionApproval> {
        const response = await this.apiAdoptionApprovalsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a AdoptionApproval resource.
     * Creates a AdoptionApproval resource.
     */
    async apiAdoptionApprovalsPostRaw(requestParameters: ApiAdoptionApprovalsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdoptionApproval>> {
        if (requestParameters['adoptionApprovalAdoptionApprovalInput'] == null) {
            throw new runtime.RequiredError(
                'adoptionApprovalAdoptionApprovalInput',
                'Required parameter "adoptionApprovalAdoptionApprovalInput" was null or undefined when calling apiAdoptionApprovalsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/adoption_approvals`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdoptionApprovalAdoptionApprovalInputToJSON(requestParameters['adoptionApprovalAdoptionApprovalInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdoptionApprovalFromJSON(jsonValue));
    }

    /**
     * Creates a AdoptionApproval resource.
     * Creates a AdoptionApproval resource.
     */
    async apiAdoptionApprovalsPost(requestParameters: ApiAdoptionApprovalsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdoptionApproval> {
        const response = await this.apiAdoptionApprovalsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
