/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Application,
  ApplicationJsonMergePatch,
  ConstraintViolation,
} from '../models/index';
import {
    ApplicationFromJSON,
    ApplicationToJSON,
    ApplicationJsonMergePatchFromJSON,
    ApplicationJsonMergePatchToJSON,
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
} from '../models/index';

export interface ApplicationsCreateRequest {
    application: Omit<Application, 'firstRunningAt'|'iconKey'|'iconSource'|'poolDomain'|'id'|'deletedAt'|'createdAt'|'updatedAt'|'operatorChosenIcon'|'iconVersion'|'deleted'>;
}

export interface ApplicationsDeleteRequest {
    id: string;
}

export interface ApplicationsGetRequest {
    id: string;
}

export interface ApplicationsListRequest {
    page?: number;
    slug?: string;
    slug2?: Array<string>;
    organization?: string;
    organization2?: Array<string>;
    organizationSlug?: string;
    organizationSlug2?: Array<string>;
}

export interface ApplicationsUpdateRequest {
    id: string;
    applicationJsonMergePatch: Omit<ApplicationJsonMergePatch, 'firstRunningAt'|'iconKey'|'iconSource'|'poolDomain'|'id'|'deletedAt'|'createdAt'|'updatedAt'|'operatorChosenIcon'|'iconVersion'|'deleted'>;
}

/**
 * 
 */
export class ApplicationApi extends runtime.BaseAPI {

    /**
     * Creates a Application resource.
     * Creates a Application resource.
     */
    async applicationsCreateRaw(requestParameters: ApplicationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['application'] == null) {
            throw new runtime.RequiredError(
                'application',
                'Required parameter "application" was null or undefined when calling applicationsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/applications`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApplicationToJSON(requestParameters['application']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * Creates a Application resource.
     * Creates a Application resource.
     */
    async applicationsCreate(requestParameters: ApplicationsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.applicationsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the Application resource.
     * Removes the Application resource.
     */
    async applicationsDeleteRaw(requestParameters: ApplicationsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling applicationsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/applications/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the Application resource.
     * Removes the Application resource.
     */
    async applicationsDelete(requestParameters: ApplicationsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.applicationsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a Application resource.
     * Retrieves a Application resource.
     */
    async applicationsGetRaw(requestParameters: ApplicationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling applicationsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/applications/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * Retrieves a Application resource.
     * Retrieves a Application resource.
     */
    async applicationsGet(requestParameters: ApplicationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.applicationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the collection of Application resources.
     * Retrieves the collection of Application resources.
     */
    async applicationsListRaw(requestParameters: ApplicationsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Application>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        if (requestParameters['slug2'] != null) {
            queryParameters['slug[]'] = requestParameters['slug2'];
        }

        if (requestParameters['organization'] != null) {
            queryParameters['organization'] = requestParameters['organization'];
        }

        if (requestParameters['organization2'] != null) {
            queryParameters['organization[]'] = requestParameters['organization2'];
        }

        if (requestParameters['organizationSlug'] != null) {
            queryParameters['organization.slug'] = requestParameters['organizationSlug'];
        }

        if (requestParameters['organizationSlug2'] != null) {
            queryParameters['organization.slug[]'] = requestParameters['organizationSlug2'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/applications`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApplicationFromJSON));
    }

    /**
     * Retrieves the collection of Application resources.
     * Retrieves the collection of Application resources.
     */
    async applicationsList(requestParameters: ApplicationsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Application>> {
        const response = await this.applicationsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the Application resource.
     * Updates the Application resource.
     */
    async applicationsUpdateRaw(requestParameters: ApplicationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Application>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling applicationsUpdate().'
            );
        }

        if (requestParameters['applicationJsonMergePatch'] == null) {
            throw new runtime.RequiredError(
                'applicationJsonMergePatch',
                'Required parameter "applicationJsonMergePatch" was null or undefined when calling applicationsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/applications/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ApplicationJsonMergePatchToJSON(requestParameters['applicationJsonMergePatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApplicationFromJSON(jsonValue));
    }

    /**
     * Updates the Application resource.
     * Updates the Application resource.
     */
    async applicationsUpdate(requestParameters: ApplicationsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Application> {
        const response = await this.applicationsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
