/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreditTransaction,
} from '../models/index';
import {
    CreditTransactionFromJSON,
    CreditTransactionToJSON,
} from '../models/index';

export interface ApiCreditTransactionsGetCollectionRequest {
    page?: number;
}

export interface ApiCreditTransactionsIdGetRequest {
    id: string;
}

/**
 * 
 */
export class CreditTransactionApi extends runtime.BaseAPI {

    /**
     * Retrieves the collection of CreditTransaction resources.
     * Retrieves the collection of CreditTransaction resources.
     */
    async apiCreditTransactionsGetCollectionRaw(requestParameters: ApiCreditTransactionsGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CreditTransaction>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/credit_transactions`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CreditTransactionFromJSON));
    }

    /**
     * Retrieves the collection of CreditTransaction resources.
     * Retrieves the collection of CreditTransaction resources.
     */
    async apiCreditTransactionsGetCollection(requestParameters: ApiCreditTransactionsGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CreditTransaction>> {
        const response = await this.apiCreditTransactionsGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves a CreditTransaction resource.
     * Retrieves a CreditTransaction resource.
     */
    async apiCreditTransactionsIdGetRaw(requestParameters: ApiCreditTransactionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreditTransaction>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCreditTransactionsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/credit_transactions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreditTransactionFromJSON(jsonValue));
    }

    /**
     * Retrieves a CreditTransaction resource.
     * Retrieves a CreditTransaction resource.
     */
    async apiCreditTransactionsIdGet(requestParameters: ApiCreditTransactionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreditTransaction> {
        const response = await this.apiCreditTransactionsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
