/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConstraintViolation,
  DeploymentAccessGate,
  DeploymentAccessGateJsonMergePatch,
} from '../models/index';
import {
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
    DeploymentAccessGateFromJSON,
    DeploymentAccessGateToJSON,
    DeploymentAccessGateJsonMergePatchFromJSON,
    DeploymentAccessGateJsonMergePatchToJSON,
} from '../models/index';

export interface DeploymentAccessGatesCreateRequest {
    deploymentAccessGate: Omit<DeploymentAccessGate, 'id'|'createdAt'|'updatedAt'>;
}

export interface DeploymentAccessGatesDeleteRequest {
    id: string;
}

export interface DeploymentAccessGatesGetRequest {
    id: string;
}

export interface DeploymentAccessGatesListRequest {
    page?: number;
}

export interface DeploymentAccessGatesUpdateRequest {
    id: string;
    deploymentAccessGateJsonMergePatch: Omit<DeploymentAccessGateJsonMergePatch, 'id'|'createdAt'|'updatedAt'>;
}

/**
 * 
 */
export class DeploymentAccessGateApi extends runtime.BaseAPI {

    /**
     * Creates a DeploymentAccessGate resource.
     * Creates a DeploymentAccessGate resource.
     */
    async deploymentAccessGatesCreateRaw(requestParameters: DeploymentAccessGatesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentAccessGate>> {
        if (requestParameters['deploymentAccessGate'] == null) {
            throw new runtime.RequiredError(
                'deploymentAccessGate',
                'Required parameter "deploymentAccessGate" was null or undefined when calling deploymentAccessGatesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployment_access_gates`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeploymentAccessGateToJSON(requestParameters['deploymentAccessGate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentAccessGateFromJSON(jsonValue));
    }

    /**
     * Creates a DeploymentAccessGate resource.
     * Creates a DeploymentAccessGate resource.
     */
    async deploymentAccessGatesCreate(requestParameters: DeploymentAccessGatesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentAccessGate> {
        const response = await this.deploymentAccessGatesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the DeploymentAccessGate resource.
     * Removes the DeploymentAccessGate resource.
     */
    async deploymentAccessGatesDeleteRaw(requestParameters: DeploymentAccessGatesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deploymentAccessGatesDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployment_access_gates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the DeploymentAccessGate resource.
     * Removes the DeploymentAccessGate resource.
     */
    async deploymentAccessGatesDelete(requestParameters: DeploymentAccessGatesDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deploymentAccessGatesDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a DeploymentAccessGate resource.
     * Retrieves a DeploymentAccessGate resource.
     */
    async deploymentAccessGatesGetRaw(requestParameters: DeploymentAccessGatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentAccessGate>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deploymentAccessGatesGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployment_access_gates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentAccessGateFromJSON(jsonValue));
    }

    /**
     * Retrieves a DeploymentAccessGate resource.
     * Retrieves a DeploymentAccessGate resource.
     */
    async deploymentAccessGatesGet(requestParameters: DeploymentAccessGatesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentAccessGate> {
        const response = await this.deploymentAccessGatesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the collection of DeploymentAccessGate resources.
     * Retrieves the collection of DeploymentAccessGate resources.
     */
    async deploymentAccessGatesListRaw(requestParameters: DeploymentAccessGatesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeploymentAccessGate>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployment_access_gates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeploymentAccessGateFromJSON));
    }

    /**
     * Retrieves the collection of DeploymentAccessGate resources.
     * Retrieves the collection of DeploymentAccessGate resources.
     */
    async deploymentAccessGatesList(requestParameters: DeploymentAccessGatesListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeploymentAccessGate>> {
        const response = await this.deploymentAccessGatesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the DeploymentAccessGate resource.
     * Updates the DeploymentAccessGate resource.
     */
    async deploymentAccessGatesUpdateRaw(requestParameters: DeploymentAccessGatesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentAccessGate>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deploymentAccessGatesUpdate().'
            );
        }

        if (requestParameters['deploymentAccessGateJsonMergePatch'] == null) {
            throw new runtime.RequiredError(
                'deploymentAccessGateJsonMergePatch',
                'Required parameter "deploymentAccessGateJsonMergePatch" was null or undefined when calling deploymentAccessGatesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployment_access_gates/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DeploymentAccessGateJsonMergePatchToJSON(requestParameters['deploymentAccessGateJsonMergePatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentAccessGateFromJSON(jsonValue));
    }

    /**
     * Updates the DeploymentAccessGate resource.
     * Updates the DeploymentAccessGate resource.
     */
    async deploymentAccessGatesUpdate(requestParameters: DeploymentAccessGatesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentAccessGate> {
        const response = await this.deploymentAccessGatesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
