/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConstraintViolation,
  Deployment,
  DeploymentBundleUploadConfirmInput,
  DeploymentBundleUploadConfirmOutput,
  DeploymentBundleUploadDeclareInput,
  DeploymentBundleUploadDeclareOutput,
  DeploymentDeploymentEndpoint,
  DeploymentJsonMergePatch,
} from '../models/index';
import {
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
    DeploymentFromJSON,
    DeploymentToJSON,
    DeploymentBundleUploadConfirmInputFromJSON,
    DeploymentBundleUploadConfirmInputToJSON,
    DeploymentBundleUploadConfirmOutputFromJSON,
    DeploymentBundleUploadConfirmOutputToJSON,
    DeploymentBundleUploadDeclareInputFromJSON,
    DeploymentBundleUploadDeclareInputToJSON,
    DeploymentBundleUploadDeclareOutputFromJSON,
    DeploymentBundleUploadDeclareOutputToJSON,
    DeploymentDeploymentEndpointFromJSON,
    DeploymentDeploymentEndpointToJSON,
    DeploymentJsonMergePatchFromJSON,
    DeploymentJsonMergePatchToJSON,
} from '../models/index';

export interface ApiDeploymentsGetCollectionRequest {
    page?: number;
}

export interface ApiDeploymentsIdDeleteRequest {
    id: string;
}

export interface ApiDeploymentsIdGetRequest {
    id: string;
}

export interface ApiDeploymentsIdPatchRequest {
    id: string;
    deploymentJsonMergePatch: Omit<DeploymentJsonMergePatch, 'id'|'deletedAt'|'createdAt'|'updatedAt'|'onASwarm'|'deleted'>;
}

export interface ApiDeploymentsIdendpointsGetCollectionRequest {
    id: string;
}

export interface ApiDeploymentsPostRequest {
    deployment: Omit<Deployment, 'id'|'deletedAt'|'createdAt'|'updatedAt'|'onASwarm'|'deleted'>;
}

export interface BundleUploadConfirmRequest {
    deploymentBundleUploadConfirmInput: DeploymentBundleUploadConfirmInput;
}

export interface BundleUploadDeclareRequest {
    deploymentBundleUploadDeclareInput: DeploymentBundleUploadDeclareInput;
}

/**
 * 
 */
export class DeploymentApi extends runtime.BaseAPI {

    /**
     * Retrieves the collection of Deployment resources.
     * Retrieves the collection of Deployment resources.
     */
    async apiDeploymentsGetCollectionRaw(requestParameters: ApiDeploymentsGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Deployment>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployments`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeploymentFromJSON));
    }

    /**
     * Retrieves the collection of Deployment resources.
     * Retrieves the collection of Deployment resources.
     */
    async apiDeploymentsGetCollection(requestParameters: ApiDeploymentsGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Deployment>> {
        const response = await this.apiDeploymentsGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the Deployment resource.
     * Removes the Deployment resource.
     */
    async apiDeploymentsIdDeleteRaw(requestParameters: ApiDeploymentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDeploymentsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the Deployment resource.
     * Removes the Deployment resource.
     */
    async apiDeploymentsIdDelete(requestParameters: ApiDeploymentsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDeploymentsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a Deployment resource.
     * Retrieves a Deployment resource.
     */
    async apiDeploymentsIdGetRaw(requestParameters: ApiDeploymentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDeploymentsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentFromJSON(jsonValue));
    }

    /**
     * Retrieves a Deployment resource.
     * Retrieves a Deployment resource.
     */
    async apiDeploymentsIdGet(requestParameters: ApiDeploymentsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment> {
        const response = await this.apiDeploymentsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the Deployment resource.
     * Updates the Deployment resource.
     */
    async apiDeploymentsIdPatchRaw(requestParameters: ApiDeploymentsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDeploymentsIdPatch().'
            );
        }

        if (requestParameters['deploymentJsonMergePatch'] == null) {
            throw new runtime.RequiredError(
                'deploymentJsonMergePatch',
                'Required parameter "deploymentJsonMergePatch" was null or undefined when calling apiDeploymentsIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployments/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DeploymentJsonMergePatchToJSON(requestParameters['deploymentJsonMergePatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentFromJSON(jsonValue));
    }

    /**
     * Updates the Deployment resource.
     * Updates the Deployment resource.
     */
    async apiDeploymentsIdPatch(requestParameters: ApiDeploymentsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment> {
        const response = await this.apiDeploymentsIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the collection of Deployment resources.
     * Retrieves the collection of Deployment resources.
     */
    async apiDeploymentsIdendpointsGetCollectionRaw(requestParameters: ApiDeploymentsIdendpointsGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DeploymentDeploymentEndpoint>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiDeploymentsIdendpointsGetCollection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployments/{id}/endpoints`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DeploymentDeploymentEndpointFromJSON));
    }

    /**
     * Retrieves the collection of Deployment resources.
     * Retrieves the collection of Deployment resources.
     */
    async apiDeploymentsIdendpointsGetCollection(requestParameters: ApiDeploymentsIdendpointsGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DeploymentDeploymentEndpoint>> {
        const response = await this.apiDeploymentsIdendpointsGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a Deployment resource.
     * Creates a Deployment resource.
     */
    async apiDeploymentsPostRaw(requestParameters: ApiDeploymentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Deployment>> {
        if (requestParameters['deployment'] == null) {
            throw new runtime.RequiredError(
                'deployment',
                'Required parameter "deployment" was null or undefined when calling apiDeploymentsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployments`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeploymentToJSON(requestParameters['deployment']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentFromJSON(jsonValue));
    }

    /**
     * Creates a Deployment resource.
     * Creates a Deployment resource.
     */
    async apiDeploymentsPost(requestParameters: ApiDeploymentsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Deployment> {
        const response = await this.apiDeploymentsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a Deployment resource.
     * Creates a Deployment resource.
     */
    async bundleUploadConfirmRaw(requestParameters: BundleUploadConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentBundleUploadConfirmOutput>> {
        if (requestParameters['deploymentBundleUploadConfirmInput'] == null) {
            throw new runtime.RequiredError(
                'deploymentBundleUploadConfirmInput',
                'Required parameter "deploymentBundleUploadConfirmInput" was null or undefined when calling bundleUploadConfirm().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployments/bundle_uploads/confirm`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeploymentBundleUploadConfirmInputToJSON(requestParameters['deploymentBundleUploadConfirmInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentBundleUploadConfirmOutputFromJSON(jsonValue));
    }

    /**
     * Creates a Deployment resource.
     * Creates a Deployment resource.
     */
    async bundleUploadConfirm(requestParameters: BundleUploadConfirmRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentBundleUploadConfirmOutput> {
        const response = await this.bundleUploadConfirmRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a Deployment resource.
     * Creates a Deployment resource.
     */
    async bundleUploadDeclareRaw(requestParameters: BundleUploadDeclareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeploymentBundleUploadDeclareOutput>> {
        if (requestParameters['deploymentBundleUploadDeclareInput'] == null) {
            throw new runtime.RequiredError(
                'deploymentBundleUploadDeclareInput',
                'Required parameter "deploymentBundleUploadDeclareInput" was null or undefined when calling bundleUploadDeclare().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/deployments/bundle_uploads`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DeploymentBundleUploadDeclareInputToJSON(requestParameters['deploymentBundleUploadDeclareInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeploymentBundleUploadDeclareOutputFromJSON(jsonValue));
    }

    /**
     * Creates a Deployment resource.
     * Creates a Deployment resource.
     */
    async bundleUploadDeclare(requestParameters: BundleUploadDeclareRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeploymentBundleUploadDeclareOutput> {
        const response = await this.bundleUploadDeclareRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
