/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConstraintViolation,
  ManagedService,
  ManagedServiceManagedServiceInput,
} from '../models/index';
import {
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
    ManagedServiceFromJSON,
    ManagedServiceToJSON,
    ManagedServiceManagedServiceInputFromJSON,
    ManagedServiceManagedServiceInputToJSON,
} from '../models/index';

export interface ApiManagedServicesGetCollectionRequest {
    page?: number;
}

export interface ApiManagedServicesIdDeleteRequest {
    id: string;
}

export interface ApiManagedServicesIdGetRequest {
    id: string;
}

export interface ApiManagedServicesPostRequest {
    managedServiceManagedServiceInput: ManagedServiceManagedServiceInput;
}

export interface ResumeRequest {
    id: string;
}

export interface SuspendRequest {
    id: string;
}

/**
 * 
 */
export class ManagedServiceApi extends runtime.BaseAPI {

    /**
     * Retrieves the collection of ManagedService resources.
     * Retrieves the collection of ManagedService resources.
     */
    async apiManagedServicesGetCollectionRaw(requestParameters: ApiManagedServicesGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ManagedService>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/managed_services`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ManagedServiceFromJSON));
    }

    /**
     * Retrieves the collection of ManagedService resources.
     * Retrieves the collection of ManagedService resources.
     */
    async apiManagedServicesGetCollection(requestParameters: ApiManagedServicesGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ManagedService>> {
        const response = await this.apiManagedServicesGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the ManagedService resource.
     * Removes the ManagedService resource.
     */
    async apiManagedServicesIdDeleteRaw(requestParameters: ApiManagedServicesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiManagedServicesIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/managed_services/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the ManagedService resource.
     * Removes the ManagedService resource.
     */
    async apiManagedServicesIdDelete(requestParameters: ApiManagedServicesIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiManagedServicesIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a ManagedService resource.
     * Retrieves a ManagedService resource.
     */
    async apiManagedServicesIdGetRaw(requestParameters: ApiManagedServicesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedService>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiManagedServicesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/managed_services/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedServiceFromJSON(jsonValue));
    }

    /**
     * Retrieves a ManagedService resource.
     * Retrieves a ManagedService resource.
     */
    async apiManagedServicesIdGet(requestParameters: ApiManagedServicesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedService> {
        const response = await this.apiManagedServicesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a ManagedService resource.
     * Creates a ManagedService resource.
     */
    async apiManagedServicesPostRaw(requestParameters: ApiManagedServicesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedService>> {
        if (requestParameters['managedServiceManagedServiceInput'] == null) {
            throw new runtime.RequiredError(
                'managedServiceManagedServiceInput',
                'Required parameter "managedServiceManagedServiceInput" was null or undefined when calling apiManagedServicesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/managed_services`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ManagedServiceManagedServiceInputToJSON(requestParameters['managedServiceManagedServiceInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedServiceFromJSON(jsonValue));
    }

    /**
     * Creates a ManagedService resource.
     * Creates a ManagedService resource.
     */
    async apiManagedServicesPost(requestParameters: ApiManagedServicesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedService> {
        const response = await this.apiManagedServicesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a ManagedService resource.
     * Creates a ManagedService resource.
     */
    async resumeRaw(requestParameters: ResumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedService>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling resume().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/managed_services/{id}/resume`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedServiceFromJSON(jsonValue));
    }

    /**
     * Creates a ManagedService resource.
     * Creates a ManagedService resource.
     */
    async resume(requestParameters: ResumeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedService> {
        const response = await this.resumeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a ManagedService resource.
     * Creates a ManagedService resource.
     */
    async suspendRaw(requestParameters: SuspendRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ManagedService>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling suspend().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/managed_services/{id}/suspend`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ManagedServiceFromJSON(jsonValue));
    }

    /**
     * Creates a ManagedService resource.
     * Creates a ManagedService resource.
     */
    async suspend(requestParameters: SuspendRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ManagedService> {
        const response = await this.suspendRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
