/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConstraintViolation,
  Organization,
  OrganizationJsonMergePatch,
} from '../models/index';
import {
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
    OrganizationFromJSON,
    OrganizationToJSON,
    OrganizationJsonMergePatchFromJSON,
    OrganizationJsonMergePatchToJSON,
} from '../models/index';

export interface ApiOrganizationsGetCollectionRequest {
    page?: number;
    slug?: string;
    slug2?: Array<string>;
}

export interface ApiOrganizationsIdDeleteRequest {
    id: string;
}

export interface ApiOrganizationsIdGetRequest {
    id: string;
}

export interface ApiOrganizationsIdPatchRequest {
    id: string;
    organizationJsonMergePatch: Omit<OrganizationJsonMergePatch, 'tierPin'|'tierPinnedAt'|'tierPinReason'|'lowBalanceWarnedAt'|'twoFactorRequiredAt'|'id'|'deletedAt'|'createdAt'|'updatedAt'|'tierPinned'|'deleted'>;
}

export interface ApiOrganizationsPostRequest {
    organization: Omit<Organization, 'tierPin'|'tierPinnedAt'|'tierPinReason'|'lowBalanceWarnedAt'|'twoFactorRequiredAt'|'id'|'deletedAt'|'createdAt'|'updatedAt'|'tierPinned'|'deleted'>;
}

/**
 * 
 */
export class OrganizationApi extends runtime.BaseAPI {

    /**
     * Retrieves the collection of Organization resources.
     * Retrieves the collection of Organization resources.
     */
    async apiOrganizationsGetCollectionRaw(requestParameters: ApiOrganizationsGetCollectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Organization>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        if (requestParameters['slug2'] != null) {
            queryParameters['slug[]'] = requestParameters['slug2'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/organizations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganizationFromJSON));
    }

    /**
     * Retrieves the collection of Organization resources.
     * Retrieves the collection of Organization resources.
     */
    async apiOrganizationsGetCollection(requestParameters: ApiOrganizationsGetCollectionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Organization>> {
        const response = await this.apiOrganizationsGetCollectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the Organization resource.
     * Removes the Organization resource.
     */
    async apiOrganizationsIdDeleteRaw(requestParameters: ApiOrganizationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiOrganizationsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the Organization resource.
     * Removes the Organization resource.
     */
    async apiOrganizationsIdDelete(requestParameters: ApiOrganizationsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiOrganizationsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a Organization resource.
     * Retrieves a Organization resource.
     */
    async apiOrganizationsIdGetRaw(requestParameters: ApiOrganizationsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiOrganizationsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Retrieves a Organization resource.
     * Retrieves a Organization resource.
     */
    async apiOrganizationsIdGet(requestParameters: ApiOrganizationsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.apiOrganizationsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates the Organization resource.
     * Updates the Organization resource.
     */
    async apiOrganizationsIdPatchRaw(requestParameters: ApiOrganizationsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiOrganizationsIdPatch().'
            );
        }

        if (requestParameters['organizationJsonMergePatch'] == null) {
            throw new runtime.RequiredError(
                'organizationJsonMergePatch',
                'Required parameter "organizationJsonMergePatch" was null or undefined when calling apiOrganizationsIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/merge-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/organizations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: OrganizationJsonMergePatchToJSON(requestParameters['organizationJsonMergePatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Updates the Organization resource.
     * Updates the Organization resource.
     */
    async apiOrganizationsIdPatch(requestParameters: ApiOrganizationsIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.apiOrganizationsIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates a Organization resource.
     * Creates a Organization resource.
     */
    async apiOrganizationsPostRaw(requestParameters: ApiOrganizationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Organization>> {
        if (requestParameters['organization'] == null) {
            throw new runtime.RequiredError(
                'organization',
                'Required parameter "organization" was null or undefined when calling apiOrganizationsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/organizations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OrganizationToJSON(requestParameters['organization']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganizationFromJSON(jsonValue));
    }

    /**
     * Creates a Organization resource.
     * Creates a Organization resource.
     */
    async apiOrganizationsPost(requestParameters: ApiOrganizationsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Organization> {
        const response = await this.apiOrganizationsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
