/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConstraintViolation,
  ServiceBinding,
  ServiceBindingServiceBindingInput,
} from '../models/index';
import {
    ConstraintViolationFromJSON,
    ConstraintViolationToJSON,
    ServiceBindingFromJSON,
    ServiceBindingToJSON,
    ServiceBindingServiceBindingInputFromJSON,
    ServiceBindingServiceBindingInputToJSON,
} from '../models/index';

export interface ServiceBindingsCreateRequest {
    serviceBindingServiceBindingInput: ServiceBindingServiceBindingInput;
}

export interface ServiceBindingsDeleteRequest {
    id: string;
}

export interface ServiceBindingsGetRequest {
    id: string;
}

export interface ServiceBindingsListRequest {
    page?: number;
}

/**
 * 
 */
export class ServiceBindingApi extends runtime.BaseAPI {

    /**
     * Creates a ServiceBinding resource.
     * Creates a ServiceBinding resource.
     */
    async serviceBindingsCreateRaw(requestParameters: ServiceBindingsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceBinding>> {
        if (requestParameters['serviceBindingServiceBindingInput'] == null) {
            throw new runtime.RequiredError(
                'serviceBindingServiceBindingInput',
                'Required parameter "serviceBindingServiceBindingInput" was null or undefined when calling serviceBindingsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/service_bindings`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceBindingServiceBindingInputToJSON(requestParameters['serviceBindingServiceBindingInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceBindingFromJSON(jsonValue));
    }

    /**
     * Creates a ServiceBinding resource.
     * Creates a ServiceBinding resource.
     */
    async serviceBindingsCreate(requestParameters: ServiceBindingsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceBinding> {
        const response = await this.serviceBindingsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes the ServiceBinding resource.
     * Removes the ServiceBinding resource.
     */
    async serviceBindingsDeleteRaw(requestParameters: ServiceBindingsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceBindingsDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/service_bindings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes the ServiceBinding resource.
     * Removes the ServiceBinding resource.
     */
    async serviceBindingsDelete(requestParameters: ServiceBindingsDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.serviceBindingsDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Retrieves a ServiceBinding resource.
     * Retrieves a ServiceBinding resource.
     */
    async serviceBindingsGetRaw(requestParameters: ServiceBindingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceBinding>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceBindingsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/service_bindings/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceBindingFromJSON(jsonValue));
    }

    /**
     * Retrieves a ServiceBinding resource.
     * Retrieves a ServiceBinding resource.
     */
    async serviceBindingsGet(requestParameters: ServiceBindingsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceBinding> {
        const response = await this.serviceBindingsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieves the collection of ServiceBinding resources.
     * Retrieves the collection of ServiceBinding resources.
     */
    async serviceBindingsListRaw(requestParameters: ServiceBindingsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ServiceBinding>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/service_bindings`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ServiceBindingFromJSON));
    }

    /**
     * Retrieves the collection of ServiceBinding resources.
     * Retrieves the collection of ServiceBinding resources.
     */
    async serviceBindingsList(requestParameters: ServiceBindingsListRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ServiceBinding>> {
        const response = await this.serviceBindingsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
