/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A human's decision on one compose service the adoption planner detected —
 * approve it, or decline it (§15).
 * 
 * **The switch arms detection; this is what authorizes the act.**
 * {@see \App\Service\ManagedService\Adoption\AdoptionReconciler} only ever turns a
 * candidate into a real {@see ManagedService}/{@see ServiceBinding} pair when a row
 * here says `approved`, and only for the compose service name recorded — a rename
 * is a different candidate with no decision of its own yet.
 * 
 * **There is no "pending" row.** A service the planner reports and nobody has
 * decided on simply has none here; recording one for every candidate on every
 * deploy would need cleaning up the moment a service is renamed away, for a state
 * ("undecided") a missing row already expresses for free.
 * 
 * One row per (application, compose service): deciding again — approving after a
 * rejection, or the reverse — updates it rather than accumulating history, because
 * only the current decision governs what the next deploy does.
 * @export
 * @interface AdoptionApprovalAdoptionApprovalInput
 */
export interface AdoptionApprovalAdoptionApprovalInput {
    /**
     * 
     * @type {string}
     * @memberof AdoptionApprovalAdoptionApprovalInput
     */
    application: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdoptionApprovalAdoptionApprovalInput
     */
    composeServiceName: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdoptionApprovalAdoptionApprovalInput
     */
    approved?: boolean;
}

/**
 * Check if a given object implements the AdoptionApprovalAdoptionApprovalInput interface.
 */
export function instanceOfAdoptionApprovalAdoptionApprovalInput(value: object): value is AdoptionApprovalAdoptionApprovalInput {
    if (!('application' in value) || value['application'] === undefined) return false;
    if (!('composeServiceName' in value) || value['composeServiceName'] === undefined) return false;
    return true;
}

export function AdoptionApprovalAdoptionApprovalInputFromJSON(json: any): AdoptionApprovalAdoptionApprovalInput {
    return AdoptionApprovalAdoptionApprovalInputFromJSONTyped(json, false);
}

export function AdoptionApprovalAdoptionApprovalInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdoptionApprovalAdoptionApprovalInput {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'],
        'composeServiceName': json['composeServiceName'],
        'approved': json['approved'] == null ? undefined : json['approved'],
    };
}

export function AdoptionApprovalAdoptionApprovalInputToJSON(json: any): AdoptionApprovalAdoptionApprovalInput {
    return AdoptionApprovalAdoptionApprovalInputToJSONTyped(json, false);
}

export function AdoptionApprovalAdoptionApprovalInputToJSONTyped(value?: AdoptionApprovalAdoptionApprovalInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'composeServiceName': value['composeServiceName'],
        'approved': value['approved'],
    };
}

