/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A human's decision on one compose service the adoption planner detected —
 * approve it, or decline it (§15).
 * 
 * **The switch arms detection; this is what authorizes the act.**
 * {@see \App\Service\ManagedService\Adoption\AdoptionReconciler} only ever turns a
 * candidate into a real {@see ManagedService}/{@see ServiceBinding} pair when a row
 * here says `approved`, and only for the compose service name recorded — a rename
 * is a different candidate with no decision of its own yet.
 * 
 * **There is no "pending" row.** A service the planner reports and nobody has
 * decided on simply has none here; recording one for every candidate on every
 * deploy would need cleaning up the moment a service is renamed away, for a state
 * ("undecided") a missing row already expresses for free.
 * 
 * One row per (application, compose service): deciding again — approving after a
 * rejection, or the reverse — updates it rather than accumulating history, because
 * only the current decision governs what the next deploy does.
 * @export
 * @interface AdoptionApproval
 */
export interface AdoptionApproval {
    /**
     * 
     * @type {string}
     * @memberof AdoptionApproval
     */
    application?: string;
    /**
     * The compose service name this decision is about — joined against a live plan by name.
     * @type {string}
     * @memberof AdoptionApproval
     */
    composeServiceName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdoptionApproval
     */
    approved?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdoptionApproval
     */
    decidedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AdoptionApproval
     */
    readonly id?: string;
}

/**
 * Check if a given object implements the AdoptionApproval interface.
 */
export function instanceOfAdoptionApproval(value: object): value is AdoptionApproval {
    return true;
}

export function AdoptionApprovalFromJSON(json: any): AdoptionApproval {
    return AdoptionApprovalFromJSONTyped(json, false);
}

export function AdoptionApprovalFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdoptionApproval {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'] == null ? undefined : json['application'],
        'composeServiceName': json['composeServiceName'] == null ? undefined : json['composeServiceName'],
        'approved': json['approved'] == null ? undefined : json['approved'],
        'decidedAt': json['decidedAt'] == null ? undefined : (new Date(json['decidedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AdoptionApprovalToJSON(json: any): AdoptionApproval {
    return AdoptionApprovalToJSONTyped(json, false);
}

export function AdoptionApprovalToJSONTyped(value?: Omit<AdoptionApproval, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'composeServiceName': value['composeServiceName'],
        'approved': value['approved'],
        'decidedAt': value['decidedAt'] == null ? undefined : ((value['decidedAt'] as any).toISOString()),
    };
}

