/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * List adoption approval decisions the caller can see.
 * @export
 * @interface AdoptionApproval
 */
export interface AdoptionApproval {
    /**
     * 
     * @type {string}
     * @memberof AdoptionApproval
     */
    application?: string;
    /**
     * The compose service name this decision is about — joined against a live plan by name.
     * @type {string}
     * @memberof AdoptionApproval
     */
    composeServiceName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdoptionApproval
     */
    approved?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AdoptionApproval
     */
    decidedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof AdoptionApproval
     */
    readonly id?: string;
}

/**
 * Check if a given object implements the AdoptionApproval interface.
 */
export function instanceOfAdoptionApproval(value: object): value is AdoptionApproval {
    return true;
}

export function AdoptionApprovalFromJSON(json: any): AdoptionApproval {
    return AdoptionApprovalFromJSONTyped(json, false);
}

export function AdoptionApprovalFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdoptionApproval {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'] == null ? undefined : json['application'],
        'composeServiceName': json['composeServiceName'] == null ? undefined : json['composeServiceName'],
        'approved': json['approved'] == null ? undefined : json['approved'],
        'decidedAt': json['decidedAt'] == null ? undefined : (new Date(json['decidedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AdoptionApprovalToJSON(json: any): AdoptionApproval {
    return AdoptionApprovalToJSONTyped(json, false);
}

export function AdoptionApprovalToJSONTyped(value?: Omit<AdoptionApproval, 'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'composeServiceName': value['composeServiceName'],
        'approved': value['approved'],
        'decidedAt': value['decidedAt'] == null ? undefined : ((value['decidedAt'] as any).toISOString()),
    };
}

