/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Approve or decline an adopted compose service candidate.
 * @export
 * @interface AdoptionApprovalAdoptionApprovalInput
 */
export interface AdoptionApprovalAdoptionApprovalInput {
    /**
     * 
     * @type {string}
     * @memberof AdoptionApprovalAdoptionApprovalInput
     */
    application: string | null;
    /**
     * 
     * @type {string}
     * @memberof AdoptionApprovalAdoptionApprovalInput
     */
    composeServiceName: string;
    /**
     * 
     * @type {boolean}
     * @memberof AdoptionApprovalAdoptionApprovalInput
     */
    approved?: boolean;
}

/**
 * Check if a given object implements the AdoptionApprovalAdoptionApprovalInput interface.
 */
export function instanceOfAdoptionApprovalAdoptionApprovalInput(value: object): value is AdoptionApprovalAdoptionApprovalInput {
    if (!('application' in value) || value['application'] === undefined) return false;
    if (!('composeServiceName' in value) || value['composeServiceName'] === undefined) return false;
    return true;
}

export function AdoptionApprovalAdoptionApprovalInputFromJSON(json: any): AdoptionApprovalAdoptionApprovalInput {
    return AdoptionApprovalAdoptionApprovalInputFromJSONTyped(json, false);
}

export function AdoptionApprovalAdoptionApprovalInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdoptionApprovalAdoptionApprovalInput {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'],
        'composeServiceName': json['composeServiceName'],
        'approved': json['approved'] == null ? undefined : json['approved'],
    };
}

export function AdoptionApprovalAdoptionApprovalInputToJSON(json: any): AdoptionApprovalAdoptionApprovalInput {
    return AdoptionApprovalAdoptionApprovalInputToJSONTyped(json, false);
}

export function AdoptionApprovalAdoptionApprovalInputToJSONTyped(value?: AdoptionApprovalAdoptionApprovalInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'composeServiceName': value['composeServiceName'],
        'approved': value['approved'],
    };
}

