/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Variable } from './Variable';
import {
    VariableFromJSON,
    VariableFromJSONTyped,
    VariableToJSON,
    VariableToJSONTyped,
} from './Variable';
import type { SealedSecret } from './SealedSecret';
import {
    SealedSecretFromJSON,
    SealedSecretFromJSONTyped,
    SealedSecretToJSON,
    SealedSecretToJSONTyped,
} from './SealedSecret';
import type { PortAllocation } from './PortAllocation';
import {
    PortAllocationFromJSON,
    PortAllocationFromJSONTyped,
    PortAllocationToJSON,
    PortAllocationToJSONTyped,
} from './PortAllocation';

/**
 * A deployable "island": one logical app, defined by a compose file, deployed as a
 * swarm stack. Holds a pointer to the current (immutable) deployment; history lives
 * in the deployment revisions.
 * @export
 * @interface ApplicationJsonMergePatch
 */
export interface ApplicationJsonMergePatch {
    /**
     * Re-home this application. Callers own everything the uniqueness
     * constraint and the trust invariant elsewhere in the platform expect of
     * a move — the entity itself only holds the pointer.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    isolationLevel?: ApplicationJsonMergePatchIsolationLevelEnum;
    /**
     * Whether a deploy's compose file is watched for services a managed
     * equivalent could replace.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    serviceAdoption?: ApplicationJsonMergePatchServiceAdoptionEnum;
    /**
     * How this application's routed HTTP services are gated at the edge —
     * `None` by default, so an application behaves exactly as it always has
     * until an org manager opts it in ({@see AccessGateMode}).
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    accessGate?: ApplicationJsonMergePatchAccessGateEnum;
    /**
     * Pointer to the currently active revision; null before the first deploy.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    currentDeployment?: string | null;
    /**
     * The first moment any revision of this application ever reached
     * `running` — null until it has. What {@see \App\Service\Teardown\TeardownGracePeriod}
     * measures grace-period uptime from, in place of the current revision's
     * own `createdAt` (#1307): a revision row is stamped at bundle ingest and
     * a fresh one is created on every `sc deploy`, so measuring off it gave a
     * six-month-old production application a ten-minute grace period the
     * moment it was redeployed. This is set once and never moved — a
     * redeploy, or reactivating an old revision, does not reset it, because
     * the application's history is what earns the longer grace, not whichever
     * revision happens to be current.
     * @type {Date}
     * @memberof ApplicationJsonMergePatch
     */
    readonly firstRunningAt?: Date | null;
    /**
     * Which deployment *name* owns the application's apex identity — the stack,
     * network and hostname that carry no revision component
     * ({@see \App\Service\Placement\StackNaming}).
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    primaryDeploymentName?: string | null;
    /**
     * The `<prefix>-<org>-<app>` join this application's stacks were **already
     * named from**, before the separator was made unambiguous — or null, meaning
     * nothing of this application has ever been on a swarm under the old name and
     * {@see \App\Service\Placement\StackNaming} is free to derive the current one.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    legacyStackBase?: string | null;
    /**
     * Object key of this application's stored icon, or null when nobody has given
     * it one — in which case {@see \App\Service\Icon\GeneratedIcon} draws one from
     * the name and slug, so every application has an icon either way.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    readonly iconKey?: string | null;
    /**
     * Where {@see $iconKey} came from — null exactly when there is no stored icon.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    readonly iconSource?: ApplicationJsonMergePatchIconSourceEnum | null;
    /**
     * This application's own Garage build-context bucket — where `sc deploy`'s
     * uploaded contexts and forwarded images are parked, and the only bucket the
     * build key below can read. Null until the first upload provisions it
     * ({@see \App\Service\Bundle\ApplicationBuildBucketProvisioner}); every
     * application predating #996 looks like that too, and provisions on its next
     * deploy.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    buildBucket?: string | null;
    /**
     * The access-key id of the read-only Garage key scoped to {@see $buildBucket},
     * handed to build tasks. Doubles as Garage's own identifier for the key (the
     * same way {@see ManagedService::$externalKeyId} does), so nothing separate is
     * persisted for it.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    buildKeyId?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApplicationJsonMergePatch
     */
    deployments?: Array<string>;
    /**
     * 
     * @type {Array<Variable>}
     * @memberof ApplicationJsonMergePatch
     */
    variables?: Array<Variable>;
    /**
     * 
     * @type {Array<PortAllocation>}
     * @memberof ApplicationJsonMergePatch
     */
    portAllocations?: Array<PortAllocation>;
    /**
     * 
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationJsonMergePatch
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationJsonMergePatch
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ApplicationJsonMergePatch
     */
    readonly updatedAt?: Date | null;
    /**
     * 
     * @type {SealedSecret}
     * @memberof ApplicationJsonMergePatch
     */
    buildCredential?: SealedSecret;
    /**
     * 
     * @type {SealedSecret}
     * @memberof ApplicationJsonMergePatch
     */
    accessGateCredential?: SealedSecret | null;
    /**
     * Point the application at a stored icon, or at none.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    icon?: string | null;
    /**
     * Whether the stored icon was chosen by a person, and so must survive the next
     * deploy's favicon extraction.
     * @type {boolean}
     * @memberof ApplicationJsonMergePatch
     */
    readonly operatorChosenIcon?: boolean;
    /**
     * A short, stable token for the icon a caller is looking at — the cache-busting
     * half of the icon URL, and null when there is nothing stored to bust.
     * @type {string}
     * @memberof ApplicationJsonMergePatch
     */
    readonly iconVersion?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApplicationJsonMergePatch
     */
    readonly deleted?: boolean;
}


/**
 * @export
 */
export const ApplicationJsonMergePatchIsolationLevelEnum = {
    Shared: 'shared',
    Dedicated: 'dedicated'
} as const;
export type ApplicationJsonMergePatchIsolationLevelEnum = typeof ApplicationJsonMergePatchIsolationLevelEnum[keyof typeof ApplicationJsonMergePatchIsolationLevelEnum];

/**
 * @export
 */
export const ApplicationJsonMergePatchServiceAdoptionEnum = {
    Off: 'off',
    Auto: 'auto'
} as const;
export type ApplicationJsonMergePatchServiceAdoptionEnum = typeof ApplicationJsonMergePatchServiceAdoptionEnum[keyof typeof ApplicationJsonMergePatchServiceAdoptionEnum];

/**
 * @export
 */
export const ApplicationJsonMergePatchAccessGateEnum = {
    None: 'none',
    BasicAuth: 'basic_auth',
    Token: 'token',
    SomeonesAuth: 'someones_auth'
} as const;
export type ApplicationJsonMergePatchAccessGateEnum = typeof ApplicationJsonMergePatchAccessGateEnum[keyof typeof ApplicationJsonMergePatchAccessGateEnum];

/**
 * @export
 */
export const ApplicationJsonMergePatchIconSourceEnum = {
    Uploaded: 'uploaded',
    Favicon: 'favicon'
} as const;
export type ApplicationJsonMergePatchIconSourceEnum = typeof ApplicationJsonMergePatchIconSourceEnum[keyof typeof ApplicationJsonMergePatchIconSourceEnum];


/**
 * Check if a given object implements the ApplicationJsonMergePatch interface.
 */
export function instanceOfApplicationJsonMergePatch(value: object): value is ApplicationJsonMergePatch {
    return true;
}

export function ApplicationJsonMergePatchFromJSON(json: any): ApplicationJsonMergePatch {
    return ApplicationJsonMergePatchFromJSONTyped(json, false);
}

export function ApplicationJsonMergePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApplicationJsonMergePatch {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': json['organization'] == null ? undefined : json['organization'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'isolationLevel': json['isolationLevel'] == null ? undefined : json['isolationLevel'],
        'serviceAdoption': json['serviceAdoption'] == null ? undefined : json['serviceAdoption'],
        'accessGate': json['accessGate'] == null ? undefined : json['accessGate'],
        'currentDeployment': json['currentDeployment'] == null ? undefined : json['currentDeployment'],
        'firstRunningAt': json['firstRunningAt'] == null ? undefined : (new Date(json['firstRunningAt'])),
        'primaryDeploymentName': json['primaryDeploymentName'] == null ? undefined : json['primaryDeploymentName'],
        'legacyStackBase': json['legacyStackBase'] == null ? undefined : json['legacyStackBase'],
        'iconKey': json['iconKey'] == null ? undefined : json['iconKey'],
        'iconSource': json['iconSource'] == null ? undefined : json['iconSource'],
        'buildBucket': json['buildBucket'] == null ? undefined : json['buildBucket'],
        'buildKeyId': json['buildKeyId'] == null ? undefined : json['buildKeyId'],
        'deployments': json['deployments'] == null ? undefined : json['deployments'],
        'variables': json['variables'] == null ? undefined : ((json['variables'] as Array<any>).map(VariableFromJSON)),
        'portAllocations': json['portAllocations'] == null ? undefined : ((json['portAllocations'] as Array<any>).map(PortAllocationFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'buildCredential': json['buildCredential'] == null ? undefined : SealedSecretFromJSON(json['buildCredential']),
        'accessGateCredential': json['accessGateCredential'] == null ? undefined : SealedSecretFromJSON(json['accessGateCredential']),
        'icon': json['icon'] == null ? undefined : json['icon'],
        'operatorChosenIcon': json['operatorChosenIcon'] == null ? undefined : json['operatorChosenIcon'],
        'iconVersion': json['iconVersion'] == null ? undefined : json['iconVersion'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function ApplicationJsonMergePatchToJSON(json: any): ApplicationJsonMergePatch {
    return ApplicationJsonMergePatchToJSONTyped(json, false);
}

export function ApplicationJsonMergePatchToJSONTyped(value?: Omit<ApplicationJsonMergePatch, 'firstRunningAt'|'iconKey'|'iconSource'|'id'|'deletedAt'|'createdAt'|'updatedAt'|'operatorChosenIcon'|'iconVersion'|'deleted'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': value['organization'],
        'slug': value['slug'],
        'name': value['name'],
        'isolationLevel': value['isolationLevel'],
        'serviceAdoption': value['serviceAdoption'],
        'accessGate': value['accessGate'],
        'currentDeployment': value['currentDeployment'],
        'primaryDeploymentName': value['primaryDeploymentName'],
        'legacyStackBase': value['legacyStackBase'],
        'buildBucket': value['buildBucket'],
        'buildKeyId': value['buildKeyId'],
        'deployments': value['deployments'],
        'variables': value['variables'] == null ? undefined : ((value['variables'] as Array<any>).map(VariableToJSON)),
        'portAllocations': value['portAllocations'] == null ? undefined : ((value['portAllocations'] as Array<any>).map(PortAllocationToJSON)),
        'buildCredential': SealedSecretToJSON(value['buildCredential']),
        'accessGateCredential': SealedSecretToJSON(value['accessGateCredential']),
        'icon': value['icon'],
    };
}

