/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BundleAdditionalContextInput
 */
export interface BundleAdditionalContextInput {
    /**
     * 
     * @type {string}
     * @memberof BundleAdditionalContextInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BundleAdditionalContextInput
     */
    contextSha256: string;
}

/**
 * Check if a given object implements the BundleAdditionalContextInput interface.
 */
export function instanceOfBundleAdditionalContextInput(value: object): value is BundleAdditionalContextInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('contextSha256' in value) || value['contextSha256'] === undefined) return false;
    return true;
}

export function BundleAdditionalContextInputFromJSON(json: any): BundleAdditionalContextInput {
    return BundleAdditionalContextInputFromJSONTyped(json, false);
}

export function BundleAdditionalContextInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleAdditionalContextInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'contextSha256': json['contextSha256'],
    };
}

export function BundleAdditionalContextInputToJSON(json: any): BundleAdditionalContextInput {
    return BundleAdditionalContextInputToJSONTyped(json, false);
}

export function BundleAdditionalContextInputToJSONTyped(value?: BundleAdditionalContextInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'contextSha256': value['contextSha256'],
    };
}

