/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BundleForwardedImageInput
 */
export interface BundleForwardedImageInput {
    /**
     * 
     * @type {string}
     * @memberof BundleForwardedImageInput
     */
    service: string;
    /**
     * 
     * @type {string}
     * @memberof BundleForwardedImageInput
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof BundleForwardedImageInput
     */
    contextSha256: string;
}

/**
 * Check if a given object implements the BundleForwardedImageInput interface.
 */
export function instanceOfBundleForwardedImageInput(value: object): value is BundleForwardedImageInput {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('contextSha256' in value) || value['contextSha256'] === undefined) return false;
    return true;
}

export function BundleForwardedImageInputFromJSON(json: any): BundleForwardedImageInput {
    return BundleForwardedImageInputFromJSONTyped(json, false);
}

export function BundleForwardedImageInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleForwardedImageInput {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'image': json['image'],
        'contextSha256': json['contextSha256'],
    };
}

export function BundleForwardedImageInputToJSON(json: any): BundleForwardedImageInput {
    return BundleForwardedImageInputToJSONTyped(json, false);
}

export function BundleForwardedImageInputToJSONTyped(value?: BundleForwardedImageInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'image': value['image'],
        'contextSha256': value['contextSha256'],
    };
}

