/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BundleUploadTarget
 */
export interface BundleUploadTarget {
    /**
     * 
     * @type {string}
     * @memberof BundleUploadTarget
     */
    service?: string;
    /**
     * The additional context's name, or null for a service's own primary context/image.
     * @type {string}
     * @memberof BundleUploadTarget
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BundleUploadTarget
     */
    contextSha256?: string;
    /**
     * 
     * @type {boolean}
     * @memberof BundleUploadTarget
     */
    alreadyStored?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BundleUploadTarget
     */
    uploadUrl?: string | null;
}

/**
 * Check if a given object implements the BundleUploadTarget interface.
 */
export function instanceOfBundleUploadTarget(value: object): value is BundleUploadTarget {
    return true;
}

export function BundleUploadTargetFromJSON(json: any): BundleUploadTarget {
    return BundleUploadTargetFromJSONTyped(json, false);
}

export function BundleUploadTargetFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleUploadTarget {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'] == null ? undefined : json['service'],
        'name': json['name'] == null ? undefined : json['name'],
        'contextSha256': json['contextSha256'] == null ? undefined : json['contextSha256'],
        'alreadyStored': json['alreadyStored'] == null ? undefined : json['alreadyStored'],
        'uploadUrl': json['uploadUrl'] == null ? undefined : json['uploadUrl'],
    };
}

export function BundleUploadTargetToJSON(json: any): BundleUploadTarget {
    return BundleUploadTargetToJSONTyped(json, false);
}

export function BundleUploadTargetToJSONTyped(value?: BundleUploadTarget | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'name': value['name'],
        'contextSha256': value['contextSha256'],
        'alreadyStored': value['alreadyStored'],
        'uploadUrl': value['uploadUrl'],
    };
}

