/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BundleAdditionalContextInput } from './BundleAdditionalContextInput';
import {
    BundleAdditionalContextInputFromJSON,
    BundleAdditionalContextInputFromJSONTyped,
    BundleAdditionalContextInputToJSON,
    BundleAdditionalContextInputToJSONTyped,
} from './BundleAdditionalContextInput';

/**
 * 
 * @export
 * @interface BundleContextInput
 */
export interface BundleContextInput {
    /**
     * 
     * @type {string}
     * @memberof BundleContextInput
     */
    service: string;
    /**
     * 
     * @type {string}
     * @memberof BundleContextInput
     */
    contextSha256: string;
    /**
     * 
     * @type {string}
     * @memberof BundleContextInput
     */
    dockerfile?: string;
    /**
     * 
     * @type {Array<BundleAdditionalContextInput>}
     * @memberof BundleContextInput
     */
    additionalContexts?: Array<BundleAdditionalContextInput>;
}

/**
 * Check if a given object implements the BundleContextInput interface.
 */
export function instanceOfBundleContextInput(value: object): value is BundleContextInput {
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('contextSha256' in value) || value['contextSha256'] === undefined) return false;
    return true;
}

export function BundleContextInputFromJSON(json: any): BundleContextInput {
    return BundleContextInputFromJSONTyped(json, false);
}

export function BundleContextInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BundleContextInput {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'],
        'contextSha256': json['contextSha256'],
        'dockerfile': json['dockerfile'] == null ? undefined : json['dockerfile'],
        'additionalContexts': json['additionalContexts'] == null ? undefined : ((json['additionalContexts'] as Array<any>).map(BundleAdditionalContextInputFromJSON)),
    };
}

export function BundleContextInputToJSON(json: any): BundleContextInput {
    return BundleContextInputToJSONTyped(json, false);
}

export function BundleContextInputToJSONTyped(value?: BundleContextInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'contextSha256': value['contextSha256'],
        'dockerfile': value['dockerfile'],
        'additionalContexts': value['additionalContexts'] == null ? undefined : ((value['additionalContexts'] as Array<any>).map(BundleAdditionalContextInputToJSON)),
    };
}

