/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConstraintViolationViolationsInner
 */
export interface ConstraintViolationViolationsInner {
    /**
     * The property path of the violation
     * @type {string}
     * @memberof ConstraintViolationViolationsInner
     */
    propertyPath: string;
    /**
     * The message associated with the violation
     * @type {string}
     * @memberof ConstraintViolationViolationsInner
     */
    message: string;
    /**
     * The code of the violation
     * @type {string}
     * @memberof ConstraintViolationViolationsInner
     */
    code?: string;
    /**
     * An extra hint to understand the violation
     * @type {string}
     * @memberof ConstraintViolationViolationsInner
     */
    hint?: string;
    /**
     * The serialized payload of the violation
     * @type {{ [key: string]: any; }}
     * @memberof ConstraintViolationViolationsInner
     */
    payload?: { [key: string]: any; };
}

/**
 * Check if a given object implements the ConstraintViolationViolationsInner interface.
 */
export function instanceOfConstraintViolationViolationsInner(value: object): value is ConstraintViolationViolationsInner {
    if (!('propertyPath' in value) || value['propertyPath'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ConstraintViolationViolationsInnerFromJSON(json: any): ConstraintViolationViolationsInner {
    return ConstraintViolationViolationsInnerFromJSONTyped(json, false);
}

export function ConstraintViolationViolationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstraintViolationViolationsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'propertyPath': json['propertyPath'],
        'message': json['message'],
        'code': json['code'] == null ? undefined : json['code'],
        'hint': json['hint'] == null ? undefined : json['hint'],
        'payload': json['payload'] == null ? undefined : json['payload'],
    };
}

export function ConstraintViolationViolationsInnerToJSON(json: any): ConstraintViolationViolationsInner {
    return ConstraintViolationViolationsInnerToJSONTyped(json, false);
}

export function ConstraintViolationViolationsInnerToJSONTyped(value?: ConstraintViolationViolationsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'propertyPath': value['propertyPath'],
        'message': value['message'],
        'code': value['code'],
        'hint': value['hint'],
        'payload': value['payload'],
    };
}

