/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ConstraintViolationViolationsInner } from './ConstraintViolationViolationsInner';
import {
    ConstraintViolationViolationsInnerFromJSON,
    ConstraintViolationViolationsInnerFromJSONTyped,
    ConstraintViolationViolationsInnerToJSON,
    ConstraintViolationViolationsInnerToJSONTyped,
} from './ConstraintViolationViolationsInner';

/**
 * Unprocessable entity
 * @export
 * @interface ConstraintViolation
 */
export interface ConstraintViolation {
    /**
     * 
     * @type {number}
     * @memberof ConstraintViolation
     */
    status?: number;
    /**
     * 
     * @type {Array<ConstraintViolationViolationsInner>}
     * @memberof ConstraintViolation
     */
    violations?: Array<ConstraintViolationViolationsInner>;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolation
     */
    readonly detail?: string;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolation
     */
    readonly type?: string;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolation
     */
    readonly title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConstraintViolation
     */
    readonly instance?: string | null;
}

/**
 * Check if a given object implements the ConstraintViolation interface.
 */
export function instanceOfConstraintViolation(value: object): value is ConstraintViolation {
    return true;
}

export function ConstraintViolationFromJSON(json: any): ConstraintViolation {
    return ConstraintViolationFromJSONTyped(json, false);
}

export function ConstraintViolationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConstraintViolation {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'violations': json['violations'] == null ? undefined : ((json['violations'] as Array<any>).map(ConstraintViolationViolationsInnerFromJSON)),
        'detail': json['detail'] == null ? undefined : json['detail'],
        'type': json['type'] == null ? undefined : json['type'],
        'title': json['title'] == null ? undefined : json['title'],
        'instance': json['instance'] == null ? undefined : json['instance'],
    };
}

export function ConstraintViolationToJSON(json: any): ConstraintViolation {
    return ConstraintViolationToJSONTyped(json, false);
}

export function ConstraintViolationToJSONTyped(value?: Omit<ConstraintViolation, 'detail'|'type'|'title'|'instance'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'violations': value['violations'] == null ? undefined : ((value['violations'] as Array<any>).map(ConstraintViolationViolationsInnerToJSON)),
    };
}

