/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The byte snapshot a storage debit was computed from — the evidence a
 * GiB-month charge can be checked against, the same role
 * {@see $usageSeconds} plays for a compute debit. Null on anything but a
 * storage debit.
 * @export
 * @interface CreditTransactionUsageBytes
 */
export interface CreditTransactionUsageBytes {
}

/**
 * Check if a given object implements the CreditTransactionUsageBytes interface.
 */
export function instanceOfCreditTransactionUsageBytes(value: object): value is CreditTransactionUsageBytes {
    return true;
}

export function CreditTransactionUsageBytesFromJSON(json: any): CreditTransactionUsageBytes {
    return CreditTransactionUsageBytesFromJSONTyped(json, false);
}

export function CreditTransactionUsageBytesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditTransactionUsageBytes {
    return json;
}

export function CreditTransactionUsageBytesToJSON(json: any): CreditTransactionUsageBytes {
    return CreditTransactionUsageBytesToJSONTyped(json, false);
}

export function CreditTransactionUsageBytesToJSONTyped(value?: CreditTransactionUsageBytes | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

