/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The engine-milliseconds this load debit was computed from — the delta
 * {@see \App\Service\ManagedService\LoadSampler} accrued and
 * {@see \App\Service\Credit\LoadBiller} then billed and cleared. Null on
 * anything but a load debit.
 * @export
 * @interface CreditTransactionEngineMillis
 */
export interface CreditTransactionEngineMillis {
}

/**
 * Check if a given object implements the CreditTransactionEngineMillis interface.
 */
export function instanceOfCreditTransactionEngineMillis(value: object): value is CreditTransactionEngineMillis {
    return true;
}

export function CreditTransactionEngineMillisFromJSON(json: any): CreditTransactionEngineMillis {
    return CreditTransactionEngineMillisFromJSONTyped(json, false);
}

export function CreditTransactionEngineMillisFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditTransactionEngineMillis {
    return json;
}

export function CreditTransactionEngineMillisToJSON(json: any): CreditTransactionEngineMillis {
    return CreditTransactionEngineMillisToJSONTyped(json, false);
}

export function CreditTransactionEngineMillisToJSONTyped(value?: CreditTransactionEngineMillis | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

