/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditTransactionEngineMillis } from './CreditTransactionEngineMillis';
import {
    CreditTransactionEngineMillisFromJSON,
    CreditTransactionEngineMillisFromJSONTyped,
    CreditTransactionEngineMillisToJSON,
    CreditTransactionEngineMillisToJSONTyped,
} from './CreditTransactionEngineMillis';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { CreditTransactionUsageBytes } from './CreditTransactionUsageBytes';
import {
    CreditTransactionUsageBytesFromJSON,
    CreditTransactionUsageBytesFromJSONTyped,
    CreditTransactionUsageBytesToJSON,
    CreditTransactionUsageBytesToJSONTyped,
} from './CreditTransactionUsageBytes';

/**
 * An IMMUTABLE, append-only ledger row for an Organization's shared credit
 * balance. A balance is never mutated in place — it's always
 * `SUM(amountCents)` over `Succeeded` rows (see
 * {@see CreditTransactionRepository::balanceForOrganization()}). Read-only over
 * the API: money movement stays server-driven.
 * 
 * Three kinds of row, one table ({@see CreditTransactionType}):
 * 
 *   - a **top-up** is created `Pending` before redirecting to Stripe Checkout,
 *     keyed on `stripeCheckoutSessionId`, then flipped to `Succeeded`/`Failed`
 *     by {@see \App\Controller\StripeWebhookController};
 *   - a **grant** and a **debit** are terminal the moment they are written, so
 *     both are written `Succeeded` — the `Pending` default is a Stripe-webhook
 *     state and is wrong for them — and neither has a Stripe session, which is
 *     why `stripeCheckoutSessionId` is nullable.
 * 
 * A debit additionally carries the hour it bills for and the meter reading it
 * came from, so the ledger can be checked against the usage events rather than
 * taken on trust. One table rather than two because the balance has to be the
 * sum of money in and money out, and a second table would make every balance
 * read a join.
 * @export
 * @interface CreditTransaction
 */
export interface CreditTransaction {
    /**
     * 
     * @type {string}
     * @memberof CreditTransaction
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditTransaction
     */
    type?: CreditTransactionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreditTransaction
     */
    status?: CreditTransactionStatusEnum;
    /**
     * Signed integer amount in the smallest currency unit (cents for USD).
     * @type {number}
     * @memberof CreditTransaction
     */
    amountCents?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditTransaction
     */
    currency?: string;
    /**
     * Stripe Checkout Session id; a top-up row is created Pending against this
     * before redirecting. Null on a grant and on a debit, neither of which has
     * a Stripe session — the *type* is what says which kind of row this is, not
     * whether this column is set.
     * @type {string}
     * @memberof CreditTransaction
     */
    stripeCheckoutSessionId?: string | null;
    /**
     * The clock hour a debit bills for, truncated to the hour and stored UTC.
     * @type {Date}
     * @memberof CreditTransaction
     */
    readonly usageHour?: Date | null;
    /**
     * Which meter wrote this row; null on every non-debit row. The other half
     * of the unique key above, and always set on a debit — never left null the
     * way a top-up or grant's `usageHour` is, or two debits from different
     * meters in the same hour would stop colliding with each other but a debit
     * from the *same* meter twice would also stop colliding with itself.
     * @type {string}
     * @memberof CreditTransaction
     */
    readonly resourceKind?: CreditTransactionResourceKindEnum | null;
    /**
     * Resolved container-seconds this debit was computed from; null on anything but a compute debit.
     * @type {number}
     * @memberof CreditTransaction
     */
    readonly usageSeconds?: number | null;
    /**
     * Containers the meter saw start and never saw stop over the billed hour.
     * @type {number}
     * @memberof CreditTransaction
     */
    readonly unresolvedContainers?: number | null;
    /**
     * 
     * @type {CreditTransactionUsageBytes}
     * @memberof CreditTransaction
     */
    usageBytes?: CreditTransactionUsageBytes | null;
    /**
     * 
     * @type {CreditTransactionEngineMillis}
     * @memberof CreditTransaction
     */
    engineMillis?: CreditTransactionEngineMillis | null;
    /**
     * Stripe Event id that last transitioned this row; secondary idempotency guard for webhook delivery.
     * @type {string}
     * @memberof CreditTransaction
     */
    stripeEventId?: string | null;
    /**
     * 
     * @type {User}
     * @memberof CreditTransaction
     */
    createdBy?: User | null;
    /**
     * 
     * @type {string}
     * @memberof CreditTransaction
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof CreditTransaction
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreditTransaction
     */
    readonly updatedAt?: Date | null;
}


/**
 * @export
 */
export const CreditTransactionTypeEnum = {
    TopUp: 'top_up',
    Grant: 'grant',
    Debit: 'debit',
    GiftCard: 'gift_card'
} as const;
export type CreditTransactionTypeEnum = typeof CreditTransactionTypeEnum[keyof typeof CreditTransactionTypeEnum];

/**
 * @export
 */
export const CreditTransactionStatusEnum = {
    Pending: 'pending',
    Succeeded: 'succeeded',
    Failed: 'failed'
} as const;
export type CreditTransactionStatusEnum = typeof CreditTransactionStatusEnum[keyof typeof CreditTransactionStatusEnum];

/**
 * @export
 */
export const CreditTransactionResourceKindEnum = {
    Compute: 'compute',
    Storage: 'storage',
    EngineLoad: 'engine_load',
    RegistryStorage: 'registry_storage'
} as const;
export type CreditTransactionResourceKindEnum = typeof CreditTransactionResourceKindEnum[keyof typeof CreditTransactionResourceKindEnum];


/**
 * Check if a given object implements the CreditTransaction interface.
 */
export function instanceOfCreditTransaction(value: object): value is CreditTransaction {
    return true;
}

export function CreditTransactionFromJSON(json: any): CreditTransaction {
    return CreditTransactionFromJSONTyped(json, false);
}

export function CreditTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': json['organization'] == null ? undefined : json['organization'],
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'amountCents': json['amountCents'] == null ? undefined : json['amountCents'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'stripeCheckoutSessionId': json['stripeCheckoutSessionId'] == null ? undefined : json['stripeCheckoutSessionId'],
        'usageHour': json['usageHour'] == null ? undefined : (new Date(json['usageHour'])),
        'resourceKind': json['resourceKind'] == null ? undefined : json['resourceKind'],
        'usageSeconds': json['usageSeconds'] == null ? undefined : json['usageSeconds'],
        'unresolvedContainers': json['unresolvedContainers'] == null ? undefined : json['unresolvedContainers'],
        'usageBytes': json['usageBytes'] == null ? undefined : CreditTransactionUsageBytesFromJSON(json['usageBytes']),
        'engineMillis': json['engineMillis'] == null ? undefined : CreditTransactionEngineMillisFromJSON(json['engineMillis']),
        'stripeEventId': json['stripeEventId'] == null ? undefined : json['stripeEventId'],
        'createdBy': json['createdBy'] == null ? undefined : UserFromJSON(json['createdBy']),
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function CreditTransactionToJSON(json: any): CreditTransaction {
    return CreditTransactionToJSONTyped(json, false);
}

export function CreditTransactionToJSONTyped(value?: Omit<CreditTransaction, 'usageHour'|'resourceKind'|'usageSeconds'|'unresolvedContainers'|'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': value['organization'],
        'type': value['type'],
        'status': value['status'],
        'amountCents': value['amountCents'],
        'currency': value['currency'],
        'stripeCheckoutSessionId': value['stripeCheckoutSessionId'],
        'usageBytes': CreditTransactionUsageBytesToJSON(value['usageBytes']),
        'engineMillis': CreditTransactionEngineMillisToJSON(value['engineMillis']),
        'stripeEventId': value['stripeEventId'],
        'createdBy': UserToJSON(value['createdBy']),
    };
}

