/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An IMMUTABLE compose revision. A deploy is a new row; rollback re-points
 * Application::$currentDeployment at an older one. Placement is resolved onto this
 * row (targetSwarm) at deploy time, so migration is just the next revision.
 * @export
 * @interface DeploymentDeploymentEndpoint
 */
export interface DeploymentDeploymentEndpoint {
    /**
     * 
     * @type {string}
     * @memberof DeploymentDeploymentEndpoint
     */
    service?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentDeploymentEndpoint
     */
    protocol?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentDeploymentEndpoint
     */
    host?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DeploymentDeploymentEndpoint
     */
    port?: number | null;
    /**
     * 
     * @type {number}
     * @memberof DeploymentDeploymentEndpoint
     */
    targetPort?: number;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentDeploymentEndpoint
     */
    assigned?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DeploymentDeploymentEndpoint
     */
    edgeRouted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeploymentDeploymentEndpoint
     */
    url?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentDeploymentEndpoint
     */
    hostUnknownReason?: string | null;
}

/**
 * Check if a given object implements the DeploymentDeploymentEndpoint interface.
 */
export function instanceOfDeploymentDeploymentEndpoint(value: object): value is DeploymentDeploymentEndpoint {
    return true;
}

export function DeploymentDeploymentEndpointFromJSON(json: any): DeploymentDeploymentEndpoint {
    return DeploymentDeploymentEndpointFromJSONTyped(json, false);
}

export function DeploymentDeploymentEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentDeploymentEndpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'] == null ? undefined : json['service'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
        'host': json['host'] == null ? undefined : json['host'],
        'port': json['port'] == null ? undefined : json['port'],
        'targetPort': json['targetPort'] == null ? undefined : json['targetPort'],
        'assigned': json['assigned'] == null ? undefined : json['assigned'],
        'edgeRouted': json['edgeRouted'] == null ? undefined : json['edgeRouted'],
        'url': json['url'] == null ? undefined : json['url'],
        'hostUnknownReason': json['hostUnknownReason'] == null ? undefined : json['hostUnknownReason'],
    };
}

export function DeploymentDeploymentEndpointToJSON(json: any): DeploymentDeploymentEndpoint {
    return DeploymentDeploymentEndpointToJSONTyped(json, false);
}

export function DeploymentDeploymentEndpointToJSONTyped(value?: DeploymentDeploymentEndpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'protocol': value['protocol'],
        'host': value['host'],
        'port': value['port'],
        'targetPort': value['targetPort'],
        'assigned': value['assigned'],
        'edgeRouted': value['edgeRouted'],
        'url': value['url'],
        'hostUnknownReason': value['hostUnknownReason'],
    };
}

