/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BundleContextInput } from './BundleContextInput';
import {
    BundleContextInputFromJSON,
    BundleContextInputFromJSONTyped,
    BundleContextInputToJSON,
    BundleContextInputToJSONTyped,
} from './BundleContextInput';
import type { BundleForwardedImageInput } from './BundleForwardedImageInput';
import {
    BundleForwardedImageInputFromJSON,
    BundleForwardedImageInputFromJSONTyped,
    BundleForwardedImageInputToJSON,
    BundleForwardedImageInputToJSONTyped,
} from './BundleForwardedImageInput';

/**
 * An IMMUTABLE compose revision. A deploy is a new row; rollback re-points
 * Application::$currentDeployment at an older one. Placement is resolved onto this
 * row (targetSwarm) at deploy time, so migration is just the next revision.
 * @export
 * @interface DeploymentBundleUploadDeclareInput
 */
export interface DeploymentBundleUploadDeclareInput {
    /**
     * 
     * @type {string}
     * @memberof DeploymentBundleUploadDeclareInput
     */
    application: string | null;
    /**
     * Matches `App\Service\Bundle\BundleManifest::$client` — which client produced this.
     * @type {string}
     * @memberof DeploymentBundleUploadDeclareInput
     */
    client: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentBundleUploadDeclareInput
     */
    name?: string | null;
    /**
     * Ask for a new revision even if this digest already matches one —
     * {@see BundleManifest::$force}'s own meaning, unchanged.
     * @type {boolean}
     * @memberof DeploymentBundleUploadDeclareInput
     */
    force?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeploymentBundleUploadDeclareInput
     */
    compose: string;
    /**
     * 
     * @type {Array<BundleContextInput>}
     * @memberof DeploymentBundleUploadDeclareInput
     */
    contexts?: Array<BundleContextInput>;
    /**
     * 
     * @type {Array<BundleForwardedImageInput>}
     * @memberof DeploymentBundleUploadDeclareInput
     */
    images?: Array<BundleForwardedImageInput>;
}

/**
 * Check if a given object implements the DeploymentBundleUploadDeclareInput interface.
 */
export function instanceOfDeploymentBundleUploadDeclareInput(value: object): value is DeploymentBundleUploadDeclareInput {
    if (!('application' in value) || value['application'] === undefined) return false;
    if (!('client' in value) || value['client'] === undefined) return false;
    if (!('compose' in value) || value['compose'] === undefined) return false;
    return true;
}

export function DeploymentBundleUploadDeclareInputFromJSON(json: any): DeploymentBundleUploadDeclareInput {
    return DeploymentBundleUploadDeclareInputFromJSONTyped(json, false);
}

export function DeploymentBundleUploadDeclareInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentBundleUploadDeclareInput {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'],
        'client': json['client'],
        'name': json['name'] == null ? undefined : json['name'],
        'force': json['force'] == null ? undefined : json['force'],
        'compose': json['compose'],
        'contexts': json['contexts'] == null ? undefined : ((json['contexts'] as Array<any>).map(BundleContextInputFromJSON)),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(BundleForwardedImageInputFromJSON)),
    };
}

export function DeploymentBundleUploadDeclareInputToJSON(json: any): DeploymentBundleUploadDeclareInput {
    return DeploymentBundleUploadDeclareInputToJSONTyped(json, false);
}

export function DeploymentBundleUploadDeclareInputToJSONTyped(value?: DeploymentBundleUploadDeclareInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'client': value['client'],
        'name': value['name'],
        'force': value['force'],
        'compose': value['compose'],
        'contexts': value['contexts'] == null ? undefined : ((value['contexts'] as Array<any>).map(BundleContextInputToJSON)),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(BundleForwardedImageInputToJSON)),
    };
}

