/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeploymentJsonMergePatchBuildContextsValueValue
 */
export interface DeploymentJsonMergePatchBuildContextsValueValue {
}

/**
 * Check if a given object implements the DeploymentJsonMergePatchBuildContextsValueValue interface.
 */
export function instanceOfDeploymentJsonMergePatchBuildContextsValueValue(value: object): value is DeploymentJsonMergePatchBuildContextsValueValue {
    return true;
}

export function DeploymentJsonMergePatchBuildContextsValueValueFromJSON(json: any): DeploymentJsonMergePatchBuildContextsValueValue {
    return DeploymentJsonMergePatchBuildContextsValueValueFromJSONTyped(json, false);
}

export function DeploymentJsonMergePatchBuildContextsValueValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentJsonMergePatchBuildContextsValueValue {
    return json;
}

export function DeploymentJsonMergePatchBuildContextsValueValueToJSON(json: any): DeploymentJsonMergePatchBuildContextsValueValue {
    return DeploymentJsonMergePatchBuildContextsValueValueToJSONTyped(json, false);
}

export function DeploymentJsonMergePatchBuildContextsValueValueToJSONTyped(value?: DeploymentJsonMergePatchBuildContextsValueValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

