/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SealedSecret } from './SealedSecret';
import {
    SealedSecretFromJSON,
    SealedSecretFromJSONTyped,
    SealedSecretToJSON,
    SealedSecretToJSONTyped,
} from './SealedSecret';

/**
 * List an application's per-deployment access-gate overrides.
 * @export
 * @interface DeploymentAccessGate
 */
export interface DeploymentAccessGate {
    /**
     * 
     * @type {string}
     * @memberof DeploymentAccessGate
     */
    application?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentAccessGate
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentAccessGate
     */
    accessGate?: DeploymentAccessGateAccessGateEnum;
    /**
     * 
     * @type {string}
     * @memberof DeploymentAccessGate
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof DeploymentAccessGate
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DeploymentAccessGate
     */
    readonly updatedAt?: Date | null;
    /**
     * 
     * @type {SealedSecret}
     * @memberof DeploymentAccessGate
     */
    accessGateCredential?: SealedSecret | null;
}


/**
 * @export
 */
export const DeploymentAccessGateAccessGateEnum = {
    None: 'none',
    BasicAuth: 'basic_auth',
    Token: 'token',
    SomeonesAuth: 'someones_auth'
} as const;
export type DeploymentAccessGateAccessGateEnum = typeof DeploymentAccessGateAccessGateEnum[keyof typeof DeploymentAccessGateAccessGateEnum];


/**
 * Check if a given object implements the DeploymentAccessGate interface.
 */
export function instanceOfDeploymentAccessGate(value: object): value is DeploymentAccessGate {
    return true;
}

export function DeploymentAccessGateFromJSON(json: any): DeploymentAccessGate {
    return DeploymentAccessGateFromJSONTyped(json, false);
}

export function DeploymentAccessGateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentAccessGate {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'] == null ? undefined : json['application'],
        'name': json['name'] == null ? undefined : json['name'],
        'accessGate': json['accessGate'] == null ? undefined : json['accessGate'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'accessGateCredential': json['accessGateCredential'] == null ? undefined : SealedSecretFromJSON(json['accessGateCredential']),
    };
}

export function DeploymentAccessGateToJSON(json: any): DeploymentAccessGate {
    return DeploymentAccessGateToJSONTyped(json, false);
}

export function DeploymentAccessGateToJSONTyped(value?: Omit<DeploymentAccessGate, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'name': value['name'],
        'accessGate': value['accessGate'],
        'accessGateCredential': SealedSecretToJSON(value['accessGateCredential']),
    };
}

