/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeploymentJsonMergePatchCanonicalSpecValue
 */
export interface DeploymentJsonMergePatchCanonicalSpecValue {
}

/**
 * Check if a given object implements the DeploymentJsonMergePatchCanonicalSpecValue interface.
 */
export function instanceOfDeploymentJsonMergePatchCanonicalSpecValue(value: object): value is DeploymentJsonMergePatchCanonicalSpecValue {
    return true;
}

export function DeploymentJsonMergePatchCanonicalSpecValueFromJSON(json: any): DeploymentJsonMergePatchCanonicalSpecValue {
    return DeploymentJsonMergePatchCanonicalSpecValueFromJSONTyped(json, false);
}

export function DeploymentJsonMergePatchCanonicalSpecValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentJsonMergePatchCanonicalSpecValue {
    return json;
}

export function DeploymentJsonMergePatchCanonicalSpecValueToJSON(json: any): DeploymentJsonMergePatchCanonicalSpecValue {
    return DeploymentJsonMergePatchCanonicalSpecValueToJSONTyped(json, false);
}

export function DeploymentJsonMergePatchCanonicalSpecValueToJSONTyped(value?: DeploymentJsonMergePatchCanonicalSpecValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

