/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeploymentJsonMergePatchBuildContextsValueValue } from './DeploymentJsonMergePatchBuildContextsValueValue';
import {
    DeploymentJsonMergePatchBuildContextsValueValueFromJSON,
    DeploymentJsonMergePatchBuildContextsValueValueFromJSONTyped,
    DeploymentJsonMergePatchBuildContextsValueValueToJSON,
    DeploymentJsonMergePatchBuildContextsValueValueToJSONTyped,
} from './DeploymentJsonMergePatchBuildContextsValueValue';
import type { DeploymentJsonMergePatchCanonicalSpecValue } from './DeploymentJsonMergePatchCanonicalSpecValue';
import {
    DeploymentJsonMergePatchCanonicalSpecValueFromJSON,
    DeploymentJsonMergePatchCanonicalSpecValueFromJSONTyped,
    DeploymentJsonMergePatchCanonicalSpecValueToJSON,
    DeploymentJsonMergePatchCanonicalSpecValueToJSONTyped,
} from './DeploymentJsonMergePatchCanonicalSpecValue';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Service } from './Service';
import {
    ServiceFromJSON,
    ServiceFromJSONTyped,
    ServiceToJSON,
    ServiceToJSONTyped,
} from './Service';
import type { DeploymentVariable } from './DeploymentVariable';
import {
    DeploymentVariableFromJSON,
    DeploymentVariableFromJSONTyped,
    DeploymentVariableToJSON,
    DeploymentVariableToJSONTyped,
} from './DeploymentVariable';
import type { Failure } from './Failure';
import {
    FailureFromJSON,
    FailureFromJSONTyped,
    FailureToJSON,
    FailureToJSONTyped,
} from './Failure';

/**
 * An IMMUTABLE compose revision. A deploy is a new row; rollback re-points
 * Application::$currentDeployment at an older one. Placement is resolved onto this
 * row (targetSwarm) at deploy time, so migration is just the next revision.
 * @export
 * @interface Deployment
 */
export interface Deployment {
    /**
     * 
     * @type {string}
     * @memberof Deployment
     */
    application?: string;
    /**
     * Monotonic per-application revision number.
     * @type {number}
     * @memberof Deployment
     */
    sequence?: number;
    /**
     * What this revision is called — `sc` defaults it to the slugified branch,
     * so the normal shape is a deployment per branch. Null for revisions created
     * before the field existed, or by a client that doesn't send one.
     * @type {string}
     * @memberof Deployment
     */
    name?: string | null;
    /**
     * Exactly what the user submitted.
     * @type {string}
     * @memberof Deployment
     */
    rawCompose?: string;
    /**
     * Parsed, supported-subset-only canonical representation — what
     * {@see \App\Service\Compose\ComposeParser::parse()} produced. Both keys are
     * optional here and not there: a row is whatever was written when it was
     * written, so a revision that predates a key still has to load.
     * @type {{ [key: string]: DeploymentJsonMergePatchCanonicalSpecValue; }}
     * @memberof Deployment
     */
    canonicalSpec?: { [key: string]: DeploymentJsonMergePatchCanonicalSpecValue; };
    /**
     * Build contexts uploaded with this revision, keyed by compose service name:
     * `{ contextSha256, dockerfile, dockerfileContent?, additionalContexts?, image?, log? }`. The
     * tarballs themselves live in the content-addressed bundle cache
     * ({@see \App\Service\Bundle\BundleStorage}); this is the pointer the build
     * worker will walk. `dockerfileContent` is a best-effort text preview
     * extracted at ingest ({@see \App\Service\Bundle\ContextDockerfileReader}) — null
     * when the context was too large to preview or predates this field.
     * @type {{ [key: string]: { [key: string]: DeploymentJsonMergePatchBuildContextsValueValue; }; }}
     * @memberof Deployment
     */
    buildContexts?: { [key: string]: { [key: string]: DeploymentJsonMergePatchBuildContextsValueValue; }; };
    /**
     * Client-forwarded images uploaded with this revision, keyed by compose
     * service name: `{ contextSha256, originalImage, image?, log? }`. See
     * docs/registry.md's "Client-side forwarding" callout: `sc` detects a
     * private, unbuildable `image:` reference it can already reach locally
     * and offers to upload it, for a platform that has no other way to pull
     * it. A sibling to {@see self::$buildContexts} rather than folded into
     * it — that array means "run this through BuildKit", and this one never
     * does. The tarballs live in the object store
     * ({@see \App\Service\Bundle\ImageStorage}), not the database; `image`
     * is filled in once the loader has pushed it to the internal registry,
     * the same way `buildContexts[]['image']` is. `{}` for every revision
     * that forwarded nothing, which is most of them.
     * @type {{ [key: string]: { [key: string]: string | null; }; }}
     * @memberof Deployment
     */
    forwardedImages?: { [key: string]: { [key: string]: string | null; }; };
    /**
     * `build.secrets` values declared for this revision's build services
     * (Grey.ooo/someones.computer_agent#46), sealed the moment they arrive
     * ({@see \App\Service\Secret\SecretBox}) and never written to the object
     * store the way a build context is: unlike a context tarball, a build
     * secret is live tenant credential material, not something worth caching
     * by content — closer to how {@see \App\Service\Registry\RegistryTokenSigner}
     * mints a push token than to how {@see \App\Entity\Variable} keeps one.
     * @type {{ [key: string]: { [key: string]: { [key: string]: string; }; }; }}
     * @memberof Deployment
     */
    buildSecrets?: { [key: string]: { [key: string]: { [key: string]: string; }; }; };
    /**
     * Resolved by the placement engine; null until placed.
     * @type {string}
     * @memberof Deployment
     */
    targetSwarm?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Deployment
     */
    status?: DeploymentStatusEnum;
    /**
     * Why the revision is in its current status — the build worker's failure
     * message, typically. Null whenever there is nothing to explain.
     * @type {string}
     * @memberof Deployment
     */
    statusReason?: string | null;
    /**
     * Set on a `Failed` revision that had already created or updated at least
     * one service on `$targetSwarm` before the failure — a live half-stack,
     * not "nothing happened" (#1270). {@see self::isOnASwarm()} reads this
     * for exactly the revisions the ordinary `Deploying`/`Running` check
     * cannot see: whatever partially landed still has to be reachable to a
     * manual Teardown and countable by the stray-container sweep, which is
     * why every other status leaves this false rather than tracking it.
     * @type {boolean}
     * @memberof Deployment
     */
    failedOnSwarm?: boolean;
    /**
     * When {@see \App\Service\Reconcile\RevisionDegradationDetector} first
     * found this `Running` revision with no task actually running on its
     * swarm — null while at least one is, or before it was ever checked.
     * @type {Date}
     * @memberof Deployment
     */
    zeroTaskObservedAt?: Date | null;
    /**
     * Set once a `Running` revision has gone a full grace period with zero
     * tasks actually running on its swarm (#1279) — a {@see Failure} of
     * {@see \App\Enum\FailurePhase::Runtime} is recorded alongside it. Never
     * flips `$status` itself: `running` still means "this is what the
     * application should be serving", and a revision the platform cannot
     * reach a running task for is a fact about the swarm, not a new desired
     * state — the same desired/observed separation
     * {@see \App\Service\Reconcile\DriftDetector} already keeps at read
     * time, made durable here so it survives past one page view.
     * @type {boolean}
     * @memberof Deployment
     */
    degraded?: boolean;
    /**
     * Content digest of the canonical spec, for dedupe/audit.
     * @type {string}
     * @memberof Deployment
     */
    digest?: string | null;
    /**
     * 
     * @type {User}
     * @memberof Deployment
     */
    createdBy?: User | null;
    /**
     * 
     * @type {Array<Service>}
     * @memberof Deployment
     */
    services?: Array<Service>;
    /**
     * 
     * @type {Array<DeploymentVariable>}
     * @memberof Deployment
     */
    variables?: Array<DeploymentVariable>;
    /**
     * 
     * @type {Array<Failure>}
     * @memberof Deployment
     */
    failures?: Array<Failure>;
    /**
     * 
     * @type {string}
     * @memberof Deployment
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Deployment
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Deployment
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Deployment
     */
    readonly updatedAt?: Date | null;
    /**
     * Whether this revision has a stack of its own on a swarm right now.
     * @type {boolean}
     * @memberof Deployment
     */
    readonly onASwarm?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Deployment
     */
    readonly deleted?: boolean;
}


/**
 * @export
 */
export const DeploymentStatusEnum = {
    Pending: 'pending',
    Building: 'building',
    Built: 'built',
    Deploying: 'deploying',
    Running: 'running',
    Failed: 'failed',
    RolledBack: 'rolled_back',
    Quarantined: 'quarantined',
    Cancelled: 'cancelled'
} as const;
export type DeploymentStatusEnum = typeof DeploymentStatusEnum[keyof typeof DeploymentStatusEnum];


/**
 * Check if a given object implements the Deployment interface.
 */
export function instanceOfDeployment(value: object): value is Deployment {
    return true;
}

export function DeploymentFromJSON(json: any): Deployment {
    return DeploymentFromJSONTyped(json, false);
}

export function DeploymentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Deployment {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'] == null ? undefined : json['application'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'name': json['name'] == null ? undefined : json['name'],
        'rawCompose': json['rawCompose'] == null ? undefined : json['rawCompose'],
        'canonicalSpec': json['canonicalSpec'] == null ? undefined : (mapValues(json['canonicalSpec'], DeploymentJsonMergePatchCanonicalSpecValueFromJSON)),
        'buildContexts': json['buildContexts'] == null ? undefined : json['buildContexts'],
        'forwardedImages': json['forwardedImages'] == null ? undefined : json['forwardedImages'],
        'buildSecrets': json['buildSecrets'] == null ? undefined : json['buildSecrets'],
        'targetSwarm': json['targetSwarm'] == null ? undefined : json['targetSwarm'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusReason': json['statusReason'] == null ? undefined : json['statusReason'],
        'failedOnSwarm': json['failedOnSwarm'] == null ? undefined : json['failedOnSwarm'],
        'zeroTaskObservedAt': json['zeroTaskObservedAt'] == null ? undefined : (new Date(json['zeroTaskObservedAt'])),
        'degraded': json['degraded'] == null ? undefined : json['degraded'],
        'digest': json['digest'] == null ? undefined : json['digest'],
        'createdBy': json['createdBy'] == null ? undefined : UserFromJSON(json['createdBy']),
        'services': json['services'] == null ? undefined : ((json['services'] as Array<any>).map(ServiceFromJSON)),
        'variables': json['variables'] == null ? undefined : ((json['variables'] as Array<any>).map(DeploymentVariableFromJSON)),
        'failures': json['failures'] == null ? undefined : ((json['failures'] as Array<any>).map(FailureFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'onASwarm': json['onASwarm'] == null ? undefined : json['onASwarm'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function DeploymentToJSON(json: any): Deployment {
    return DeploymentToJSONTyped(json, false);
}

export function DeploymentToJSONTyped(value?: Omit<Deployment, 'id'|'deletedAt'|'createdAt'|'updatedAt'|'onASwarm'|'deleted'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'sequence': value['sequence'],
        'name': value['name'],
        'rawCompose': value['rawCompose'],
        'canonicalSpec': value['canonicalSpec'] == null ? undefined : (mapValues(value['canonicalSpec'], DeploymentJsonMergePatchCanonicalSpecValueToJSON)),
        'buildContexts': value['buildContexts'],
        'forwardedImages': value['forwardedImages'],
        'buildSecrets': value['buildSecrets'],
        'targetSwarm': value['targetSwarm'],
        'status': value['status'],
        'statusReason': value['statusReason'],
        'failedOnSwarm': value['failedOnSwarm'],
        'zeroTaskObservedAt': value['zeroTaskObservedAt'] == null ? undefined : ((value['zeroTaskObservedAt'] as any).toISOString()),
        'degraded': value['degraded'],
        'digest': value['digest'],
        'createdBy': UserToJSON(value['createdBy']),
        'services': value['services'] == null ? undefined : ((value['services'] as Array<any>).map(ServiceToJSON)),
        'variables': value['variables'] == null ? undefined : ((value['variables'] as Array<any>).map(DeploymentVariableToJSON)),
        'failures': value['failures'] == null ? undefined : ((value['failures'] as Array<any>).map(FailureToJSON)),
    };
}

