/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An IMMUTABLE compose revision. A deploy is a new row; rollback re-points
 * Application::$currentDeployment at an older one. Placement is resolved onto this
 * row (targetSwarm) at deploy time, so migration is just the next revision.
 * @export
 * @interface DeploymentBundleUploadConfirmOutput
 */
export interface DeploymentBundleUploadConfirmOutput {
    /**
     * 
     * @type {string}
     * @memberof DeploymentBundleUploadConfirmOutput
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof DeploymentBundleUploadConfirmOutput
     */
    sequence?: number;
    /**
     * 
     * @type {string}
     * @memberof DeploymentBundleUploadConfirmOutput
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof DeploymentBundleUploadConfirmOutput
     */
    digest?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DeploymentBundleUploadConfirmOutput
     */
    url?: string;
    /**
     * True when this upload restarted an existing failed revision rather than minting one.
     * @type {boolean}
     * @memberof DeploymentBundleUploadConfirmOutput
     */
    retried?: boolean;
    /**
     * A deploy this organization can still afford, but is projected to run out of paying for soon — null on every ordinary deploy.
     * @type {string}
     * @memberof DeploymentBundleUploadConfirmOutput
     */
    warning?: string | null;
}

/**
 * Check if a given object implements the DeploymentBundleUploadConfirmOutput interface.
 */
export function instanceOfDeploymentBundleUploadConfirmOutput(value: object): value is DeploymentBundleUploadConfirmOutput {
    return true;
}

export function DeploymentBundleUploadConfirmOutputFromJSON(json: any): DeploymentBundleUploadConfirmOutput {
    return DeploymentBundleUploadConfirmOutputFromJSONTyped(json, false);
}

export function DeploymentBundleUploadConfirmOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentBundleUploadConfirmOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'status': json['status'] == null ? undefined : json['status'],
        'digest': json['digest'] == null ? undefined : json['digest'],
        'url': json['url'] == null ? undefined : json['url'],
        'retried': json['retried'] == null ? undefined : json['retried'],
        'warning': json['warning'] == null ? undefined : json['warning'],
    };
}

export function DeploymentBundleUploadConfirmOutputToJSON(json: any): DeploymentBundleUploadConfirmOutput {
    return DeploymentBundleUploadConfirmOutputToJSONTyped(json, false);
}

export function DeploymentBundleUploadConfirmOutputToJSONTyped(value?: DeploymentBundleUploadConfirmOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'sequence': value['sequence'],
        'status': value['status'],
        'digest': value['digest'],
        'url': value['url'],
        'retried': value['retried'],
        'warning': value['warning'],
    };
}

