/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VariableVersion } from './VariableVersion';
import {
    VariableVersionFromJSON,
    VariableVersionFromJSONTyped,
    VariableVersionToJSON,
    VariableVersionToJSONTyped,
} from './VariableVersion';

/**
 * 
 * @export
 * @interface DeploymentVariable
 */
export interface DeploymentVariable {
    /**
     * 
     * @type {string}
     * @memberof DeploymentVariable
     */
    deployment?: string;
    /**
     * 
     * @type {VariableVersion}
     * @memberof DeploymentVariable
     */
    variableVersion?: VariableVersion;
    /**
     * 
     * @type {string}
     * @memberof DeploymentVariable
     */
    readonly id?: string;
    /**
     * The environment variable name this entry contributes.
     * @type {string}
     * @memberof DeploymentVariable
     */
    readonly key?: string;
}

/**
 * Check if a given object implements the DeploymentVariable interface.
 */
export function instanceOfDeploymentVariable(value: object): value is DeploymentVariable {
    return true;
}

export function DeploymentVariableFromJSON(json: any): DeploymentVariable {
    return DeploymentVariableFromJSONTyped(json, false);
}

export function DeploymentVariableFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentVariable {
    if (json == null) {
        return json;
    }
    return {
        
        'deployment': json['deployment'] == null ? undefined : json['deployment'],
        'variableVersion': json['variableVersion'] == null ? undefined : VariableVersionFromJSON(json['variableVersion']),
        'id': json['id'] == null ? undefined : json['id'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function DeploymentVariableToJSON(json: any): DeploymentVariable {
    return DeploymentVariableToJSONTyped(json, false);
}

export function DeploymentVariableToJSONTyped(value?: Omit<DeploymentVariable, 'id'|'key'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deployment': value['deployment'],
        'variableVersion': VariableVersionToJSON(value['variableVersion']),
    };
}

