/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BundleUploadTarget } from './BundleUploadTarget';
import {
    BundleUploadTargetFromJSON,
    BundleUploadTargetFromJSONTyped,
    BundleUploadTargetToJSON,
    BundleUploadTargetToJSONTyped,
} from './BundleUploadTarget';

/**
 * An IMMUTABLE compose revision. A deploy is a new row; rollback re-points
 * Application::$currentDeployment at an older one. Placement is resolved onto this
 * row (targetSwarm) at deploy time, so migration is just the next revision.
 * @export
 * @interface DeploymentBundleUploadDeclareOutput
 */
export interface DeploymentBundleUploadDeclareOutput {
    /**
     * 
     * @type {Array<BundleUploadTarget>}
     * @memberof DeploymentBundleUploadDeclareOutput
     */
    contexts?: Array<BundleUploadTarget>;
    /**
     * 
     * @type {Array<BundleUploadTarget>}
     * @memberof DeploymentBundleUploadDeclareOutput
     */
    additionalContexts?: Array<BundleUploadTarget>;
    /**
     * 
     * @type {Array<BundleUploadTarget>}
     * @memberof DeploymentBundleUploadDeclareOutput
     */
    images?: Array<BundleUploadTarget>;
    /**
     * 
     * @type {Date}
     * @memberof DeploymentBundleUploadDeclareOutput
     */
    expiresAt?: Date;
}

/**
 * Check if a given object implements the DeploymentBundleUploadDeclareOutput interface.
 */
export function instanceOfDeploymentBundleUploadDeclareOutput(value: object): value is DeploymentBundleUploadDeclareOutput {
    return true;
}

export function DeploymentBundleUploadDeclareOutputFromJSON(json: any): DeploymentBundleUploadDeclareOutput {
    return DeploymentBundleUploadDeclareOutputFromJSONTyped(json, false);
}

export function DeploymentBundleUploadDeclareOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeploymentBundleUploadDeclareOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'contexts': json['contexts'] == null ? undefined : ((json['contexts'] as Array<any>).map(BundleUploadTargetFromJSON)),
        'additionalContexts': json['additionalContexts'] == null ? undefined : ((json['additionalContexts'] as Array<any>).map(BundleUploadTargetFromJSON)),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(BundleUploadTargetFromJSON)),
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function DeploymentBundleUploadDeclareOutputToJSON(json: any): DeploymentBundleUploadDeclareOutput {
    return DeploymentBundleUploadDeclareOutputToJSONTyped(json, false);
}

export function DeploymentBundleUploadDeclareOutputToJSONTyped(value?: DeploymentBundleUploadDeclareOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contexts': value['contexts'] == null ? undefined : ((value['contexts'] as Array<any>).map(BundleUploadTargetToJSON)),
        'additionalContexts': value['additionalContexts'] == null ? undefined : ((value['additionalContexts'] as Array<any>).map(BundleUploadTargetToJSON)),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(BundleUploadTargetToJSON)),
        'expiresAt': value['expiresAt'] == null ? undefined : ((value['expiresAt']).toISOString()),
    };
}

