/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { ProxmoxInstance } from './ProxmoxInstance';
import {
    ProxmoxInstanceFromJSON,
    ProxmoxInstanceFromJSONTyped,
    ProxmoxInstanceToJSON,
    ProxmoxInstanceToJSONTyped,
} from './ProxmoxInstance';

/**
 * 
 * @export
 * @interface Failure
 */
export interface Failure {
    /**
     * Deleting a revision deletes its failures with it. They are an account of
     * what that revision did, and outliving the thing they describe would leave
     * a page that can only render half of itself.
     * @type {string}
     * @memberof Failure
     */
    deployment?: string | null;
    /**
     * 
     * @type {ProxmoxInstance}
     * @memberof Failure
     */
    proxmoxInstance?: ProxmoxInstance | null;
    /**
     * 
     * @type {string}
     * @memberof Failure
     */
    phase?: FailurePhaseEnum;
    /**
     * Verbatim, as it was written to `Deployment::$statusReason` at the time.
     * @type {string}
     * @memberof Failure
     */
    reason?: string;
    /**
     * The short handle this failure is quoted by — see {@see FailureReference}.
     * @type {string}
     * @memberof Failure
     */
    readonly reference?: string;
    /**
     * Which compose service, where the phase happens per-service. Null for the
     * phases that fail the revision as a whole (placement, stranded) and for a
     * deploy that never got as far as naming one.
     * @type {string}
     * @memberof Failure
     */
    service?: string | null;
    /**
     * Object key of the build log as it stood, or null when there was none.
     * @type {string}
     * @memberof Failure
     */
    buildLogKey?: string | null;
    /**
     * The digest a {@see FailurePhase::Scan} failure was quarantined over —
     * null for every other phase. What lets the scan quarantine queue
     * (docs/image-scanning.md, #816) resolve straight from a quarantined
     * revision to the exact {@see \App\Entity\ImageScan} an operator's Clear
     * or Uphold acts on, without re-deriving it from a pinned image
     * reference or a reason string meant for a person to read.
     * @type {string}
     * @memberof Failure
     */
    imageDigest?: string | null;
    /**
     * The capability that makes {@see \App\Controller\FailureController::shared()}
     * serve this to someone with no session, or null while it is private.
     * @type {string}
     * @memberof Failure
     */
    readonly shareToken?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Failure
     */
    readonly sharedAt?: Date | null;
    /**
     * When the capability above stops working, 24 hours after it was minted.
     * @type {Date}
     * @memberof Failure
     */
    readonly shareExpiresAt?: Date | null;
    /**
     * 
     * @type {User}
     * @memberof Failure
     */
    sharedBy?: User | null;
    /**
     * 
     * @type {string}
     * @memberof Failure
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Failure
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Failure
     */
    readonly updatedAt?: Date | null;
    /**
     * The reference as it is written for a reader: `F-24GT1BQ7`.
     * @type {string}
     * @memberof Failure
     */
    readonly displayLabel?: string;
    /**
     * Whether an unauthenticated request may read this: a token was minted and
     * it has not yet passed its expiry.
     * @type {boolean}
     * @memberof Failure
     */
    readonly shared?: boolean;
}


/**
 * @export
 */
export const FailurePhaseEnum = {
    Placement: 'placement',
    Build: 'build',
    Deploy: 'deploy',
    Teardown: 'teardown',
    Runtime: 'runtime',
    Scan: 'scan',
    Stranded: 'stranded',
    Infrastructure: 'infrastructure'
} as const;
export type FailurePhaseEnum = typeof FailurePhaseEnum[keyof typeof FailurePhaseEnum];


/**
 * Check if a given object implements the Failure interface.
 */
export function instanceOfFailure(value: object): value is Failure {
    return true;
}

export function FailureFromJSON(json: any): Failure {
    return FailureFromJSONTyped(json, false);
}

export function FailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Failure {
    if (json == null) {
        return json;
    }
    return {
        
        'deployment': json['deployment'] == null ? undefined : json['deployment'],
        'proxmoxInstance': json['proxmoxInstance'] == null ? undefined : ProxmoxInstanceFromJSON(json['proxmoxInstance']),
        'phase': json['phase'] == null ? undefined : json['phase'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'reference': json['reference'] == null ? undefined : json['reference'],
        'service': json['service'] == null ? undefined : json['service'],
        'buildLogKey': json['buildLogKey'] == null ? undefined : json['buildLogKey'],
        'imageDigest': json['imageDigest'] == null ? undefined : json['imageDigest'],
        'shareToken': json['shareToken'] == null ? undefined : json['shareToken'],
        'sharedAt': json['sharedAt'] == null ? undefined : (new Date(json['sharedAt'])),
        'shareExpiresAt': json['shareExpiresAt'] == null ? undefined : (new Date(json['shareExpiresAt'])),
        'sharedBy': json['sharedBy'] == null ? undefined : UserFromJSON(json['sharedBy']),
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'displayLabel': json['displayLabel'] == null ? undefined : json['displayLabel'],
        'shared': json['shared'] == null ? undefined : json['shared'],
    };
}

export function FailureToJSON(json: any): Failure {
    return FailureToJSONTyped(json, false);
}

export function FailureToJSONTyped(value?: Omit<Failure, 'reference'|'shareToken'|'sharedAt'|'shareExpiresAt'|'id'|'createdAt'|'updatedAt'|'displayLabel'|'shared'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deployment': value['deployment'],
        'proxmoxInstance': ProxmoxInstanceToJSON(value['proxmoxInstance']),
        'phase': value['phase'],
        'reason': value['reason'],
        'service': value['service'],
        'buildLogKey': value['buildLogKey'],
        'imageDigest': value['imageDigest'],
        'sharedBy': UserToJSON(value['sharedBy']),
    };
}

