/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProxmoxInstance } from './ProxmoxInstance';
import {
    ProxmoxInstanceFromJSON,
    ProxmoxInstanceFromJSONTyped,
    ProxmoxInstanceToJSON,
    ProxmoxInstanceToJSONTyped,
} from './ProxmoxInstance';

/**
 * 
 * @export
 * @interface Machine
 */
export interface Machine {
    /**
     * 
     * @type {ProxmoxInstance}
     * @memberof Machine
     */
    instance?: ProxmoxInstance;
    /**
     * The node within the instance — same string `app:proxmox:template` builds on.
     * @type {string}
     * @memberof Machine
     */
    node?: string;
    /**
     * 
     * @type {number}
     * @memberof Machine
     */
    vmid?: number;
    /**
     * How an operator addresses it; also the guest hostname the seed sets.
     * @type {string}
     * @memberof Machine
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Machine
     */
    size?: MachineSizeEnum;
    /**
     * Disk as a block count, never gigabytes: a thin volume grows and never
     * shrinks, so the invariant worth enforcing is "this number only goes up",
     * and a count makes that checkable where a free-form size would not.
     * @type {number}
     * @memberof Machine
     */
    readonly diskBlocks?: number;
    /**
     * The template this was cloned from, by vmid. The reference count that
     * decides when a superseded template may be deleted (§03): linked clones
     * pin their base disk, and Proxmox will refuse — rightly — to delete a
     * template that still has children.
     * @type {number}
     * @memberof Machine
     */
    templateVmid?: number;
    /**
     * The island address chosen by the control plane's pool and registered
     * with Proxmox, which is what dnsmasq then answers the machine's DHCP
     * request with (docs/island-network.md — Proxmox's IPAM cannot allocate,
     * so the platform still picks). Null until allocation; unique so the pool
     * cannot double-allocate even if two provisions race.
     * @type {string}
     * @memberof Machine
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Machine
     */
    state?: MachineStateEnum;
    /**
     * Why `Failed`, when it is. Carries the task's own words, never a paraphrase.
     * @type {string}
     * @memberof Machine
     */
    readonly failure?: string | null;
    /**
     * Which run through the flow this is, starting at 1 and incremented on
     * every {@see self::reprovision()}. {@see \App\Entity\ProvisioningLogLine}
     * tags each captured line with the value that was current when it was
     * written, so a retry's transcript starts fresh rather than appending to
     * the failed attempt before it.
     * @type {number}
     * @memberof Machine
     */
    readonly provisionAttempt?: number;
    /**
     * When the current run through the flow began — set at construction and
     * reset on every {@see self::reprovision()}, mirroring
     * {@see ProxmoxInstance::$templateBuildStartedAt}. What
     * {@see self::isProvisioningStale()} measures against: the real ceiling is
     * the flow's own step deadlines ({@see \App\MessageHandler\ProvisionMachineHandler}'s
     * `BOOT_DEADLINE`/`TASK_DEADLINE`), and a run still going past
     * {@see self::PROVISION_PRESUMED_DEAD_AFTER} is a worker that died holding
     * it — a crash, an OOM, a deploy restart — rather than one still working.
     * @type {Date}
     * @memberof Machine
     */
    readonly provisionStartedAt?: Date | null;
    /**
     * The context this machine serves, if any. Nullable on purpose — see the class docblock.
     * @type {string}
     * @memberof Machine
     */
    swarm?: string | null;
    /**
     * The organization this machine was self-service-provisioned for, or null
     * for one an operator made through `/admin/machines`. Nullable for the same
     * reason `$swarm` is: an admin-made machine belongs to nobody's tenancy, and
     * this column must not invent an owner for it. Set once, at creation, to the
     * same organization that owns the paired `$swarm` — {@see Organization::markDeleted()}
     * detaches it rather than deleting the row, matching how a BYO context's
     * owner is handled.
     * @type {string}
     * @memberof Machine
     */
    organization?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Machine
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Machine
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Machine
     */
    readonly updatedAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Machine
     */
    readonly diskGigabytes?: number;
    /**
     * Still mid-flow, and has been for longer than any healthy run takes —
     * what {@see \App\MessageHandler\SweepStaleMachineProvisionsHandler} sweeps
     * for. A worker that crashed, OOM'd, or was recycled mid-step leaves the
     * row exactly where it stood; nothing else ever revisits it, since the
     * handler's own guard is "state is Requested" and every other step only
     * ever moves the flow forward.
     * @type {boolean}
     * @memberof Machine
     */
    readonly provisioningStale?: boolean;
}


/**
 * @export
 */
export const MachineSizeEnum = {
    S: 's',
    M: 'm',
    L: 'l'
} as const;
export type MachineSizeEnum = typeof MachineSizeEnum[keyof typeof MachineSizeEnum];

/**
 * @export
 */
export const MachineStateEnum = {
    Requested: 'requested',
    Cloning: 'cloning',
    Configuring: 'configuring',
    Starting: 'starting',
    Booting: 'booting',
    Running: 'running',
    Serving: 'serving',
    Retiring: 'retiring',
    Failed: 'failed'
} as const;
export type MachineStateEnum = typeof MachineStateEnum[keyof typeof MachineStateEnum];


/**
 * Check if a given object implements the Machine interface.
 */
export function instanceOfMachine(value: object): value is Machine {
    return true;
}

export function MachineFromJSON(json: any): Machine {
    return MachineFromJSONTyped(json, false);
}

export function MachineFromJSONTyped(json: any, ignoreDiscriminator: boolean): Machine {
    if (json == null) {
        return json;
    }
    return {
        
        'instance': json['instance'] == null ? undefined : ProxmoxInstanceFromJSON(json['instance']),
        'node': json['node'] == null ? undefined : json['node'],
        'vmid': json['vmid'] == null ? undefined : json['vmid'],
        'name': json['name'] == null ? undefined : json['name'],
        'size': json['size'] == null ? undefined : json['size'],
        'diskBlocks': json['diskBlocks'] == null ? undefined : json['diskBlocks'],
        'templateVmid': json['templateVmid'] == null ? undefined : json['templateVmid'],
        'address': json['address'] == null ? undefined : json['address'],
        'state': json['state'] == null ? undefined : json['state'],
        'failure': json['failure'] == null ? undefined : json['failure'],
        'provisionAttempt': json['provisionAttempt'] == null ? undefined : json['provisionAttempt'],
        'provisionStartedAt': json['provisionStartedAt'] == null ? undefined : (new Date(json['provisionStartedAt'])),
        'swarm': json['swarm'] == null ? undefined : json['swarm'],
        'organization': json['organization'] == null ? undefined : json['organization'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'diskGigabytes': json['diskGigabytes'] == null ? undefined : json['diskGigabytes'],
        'provisioningStale': json['provisioningStale'] == null ? undefined : json['provisioningStale'],
    };
}

export function MachineToJSON(json: any): Machine {
    return MachineToJSONTyped(json, false);
}

export function MachineToJSONTyped(value?: Omit<Machine, 'diskBlocks'|'failure'|'provisionAttempt'|'provisionStartedAt'|'id'|'createdAt'|'updatedAt'|'diskGigabytes'|'provisioningStale'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instance': ProxmoxInstanceToJSON(value['instance']),
        'node': value['node'],
        'vmid': value['vmid'],
        'name': value['name'],
        'size': value['size'],
        'templateVmid': value['templateVmid'],
        'address': value['address'],
        'state': value['state'],
        'swarm': value['swarm'],
        'organization': value['organization'],
    };
}

