/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One tenant's database or bucket on a shared engine.
 * 
 * **Owned by an organization and bound to applications** — not a per-application
 * toggle. The distinction is the whole reason this entity exists in this shape: a
 * toggle with a unique foreign key cannot express one database backing both a web
 * app and its worker, and cannot survive an application being rebuilt under a new
 * name. Binding is therefore explicit ({@see ServiceBinding}), which costs one
 * step at creation and buys sharing, one billing shape, one permission model and
 * one set of verbs across databases *and* buckets.
 * 
 * A bucket is the same noun with a different {@see $kind}. Only the driver that
 * executes the tenancy operations differs.
 * 
 * Soft-deleted, so a destroy is recoverable within its grace period
 * ({@see ManagedServiceRepository::GRACE_PERIOD}); only the driver's `DROP` is not,
 * and that runs on the far side of it.
 * 
 * **Read is scoped by membership and writing by role**, which are different
 * questions: {@see \App\ApiResource\ManagedServiceOwnerExtension} filters the
 * query, so another tenant's id answers 404 rather than confirming it exists, while
 * {@see \App\Security\Voter\ManageVoter} governs the verbs inside each processor
 * — a plain member may see their organization's databases without being able to
 * destroy one.
 * 
 * Delete does *not* fall through to the generic soft-delete processor: dropping a
 * database is not stamping a column, and the difference is a tenant's data. See
 * {@see \App\State\ManagedServiceDestroyProcessor}.
 * @export
 * @interface ManagedServiceManagedServiceInput
 */
export interface ManagedServiceManagedServiceInput {
    /**
     * The engine, as the catalogue names it — `postgres:17`, `mysql:8.0`.
     * @type {string}
     * @memberof ManagedServiceManagedServiceInput
     */
    engine: string;
    /**
     * The tenant's own name for it — what appears in the UI and in `sc service ls`.
     * @type {string}
     * @memberof ManagedServiceManagedServiceInput
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedServiceManagedServiceInput
     */
    organization: string | null;
}

/**
 * Check if a given object implements the ManagedServiceManagedServiceInput interface.
 */
export function instanceOfManagedServiceManagedServiceInput(value: object): value is ManagedServiceManagedServiceInput {
    if (!('engine' in value) || value['engine'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    return true;
}

export function ManagedServiceManagedServiceInputFromJSON(json: any): ManagedServiceManagedServiceInput {
    return ManagedServiceManagedServiceInputFromJSONTyped(json, false);
}

export function ManagedServiceManagedServiceInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedServiceManagedServiceInput {
    if (json == null) {
        return json;
    }
    return {
        
        'engine': json['engine'],
        'slug': json['slug'],
        'organization': json['organization'],
    };
}

export function ManagedServiceManagedServiceInputToJSON(json: any): ManagedServiceManagedServiceInput {
    return ManagedServiceManagedServiceInputToJSONTyped(json, false);
}

export function ManagedServiceManagedServiceInputToJSONTyped(value?: ManagedServiceManagedServiceInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'engine': value['engine'],
        'slug': value['slug'],
        'organization': value['organization'],
    };
}

