/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ManagedServiceUsageBytes } from './ManagedServiceUsageBytes';
import {
    ManagedServiceUsageBytesFromJSON,
    ManagedServiceUsageBytesFromJSONTyped,
    ManagedServiceUsageBytesToJSON,
    ManagedServiceUsageBytesToJSONTyped,
} from './ManagedServiceUsageBytes';
import type { ManagedServiceLastLoadMillis } from './ManagedServiceLastLoadMillis';
import {
    ManagedServiceLastLoadMillisFromJSON,
    ManagedServiceLastLoadMillisFromJSONTyped,
    ManagedServiceLastLoadMillisToJSON,
    ManagedServiceLastLoadMillisToJSONTyped,
} from './ManagedServiceLastLoadMillis';
import type { SealedSecret } from './SealedSecret';
import {
    SealedSecretFromJSON,
    SealedSecretFromJSONTyped,
    SealedSecretToJSON,
    SealedSecretToJSONTyped,
} from './SealedSecret';
import type { ManagedServicePendingLoadMillis } from './ManagedServicePendingLoadMillis';
import {
    ManagedServicePendingLoadMillisFromJSON,
    ManagedServicePendingLoadMillisFromJSONTyped,
    ManagedServicePendingLoadMillisToJSON,
    ManagedServicePendingLoadMillisToJSONTyped,
} from './ManagedServicePendingLoadMillis';
import type { ServiceInstance } from './ServiceInstance';
import {
    ServiceInstanceFromJSON,
    ServiceInstanceFromJSONTyped,
    ServiceInstanceToJSON,
    ServiceInstanceToJSONTyped,
} from './ServiceInstance';
import type { ManagedServiceQuotaBytes } from './ManagedServiceQuotaBytes';
import {
    ManagedServiceQuotaBytesFromJSON,
    ManagedServiceQuotaBytesFromJSONTyped,
    ManagedServiceQuotaBytesToJSON,
    ManagedServiceQuotaBytesToJSONTyped,
} from './ManagedServiceQuotaBytes';

/**
 * One tenant's database or bucket on a shared engine.
 * 
 * **Owned by an organization and bound to applications** — not a per-application
 * toggle. The distinction is the whole reason this entity exists in this shape: a
 * toggle with a unique foreign key cannot express one database backing both a web
 * app and its worker, and cannot survive an application being rebuilt under a new
 * name. Binding is therefore explicit ({@see ServiceBinding}), which costs one
 * step at creation and buys sharing, one billing shape, one permission model and
 * one set of verbs across databases *and* buckets.
 * 
 * A bucket is the same noun with a different {@see $kind}. Only the driver that
 * executes the tenancy operations differs.
 * 
 * Soft-deleted, so a destroy is recoverable within its grace period
 * ({@see ManagedServiceRepository::GRACE_PERIOD}); only the driver's `DROP` is not,
 * and that runs on the far side of it.
 * 
 * **Read is scoped by membership and writing by role**, which are different
 * questions: {@see \App\ApiResource\ManagedServiceOwnerExtension} filters the
 * query, so another tenant's id answers 404 rather than confirming it exists, while
 * {@see \App\Security\Voter\ManageVoter} governs the verbs inside each processor
 * — a plain member may see their organization's databases without being able to
 * destroy one.
 * 
 * Delete does *not* fall through to the generic soft-delete processor: dropping a
 * database is not stamping a column, and the difference is a tenant's data. See
 * {@see \App\State\ManagedServiceDestroyProcessor}.
 * @export
 * @interface ManagedService
 */
export interface ManagedService {
    /**
     * 
     * @type {string}
     * @memberof ManagedService
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedService
     */
    slug?: string;
    /**
     * The catalogue entry the tenant picked, as `(kind, majorVersion)`.
     * @type {string}
     * @memberof ManagedService
     */
    kind?: ManagedServiceKindEnum;
    /**
     * 
     * @type {string}
     * @memberof ManagedService
     */
    majorVersion?: string;
    /**
     * 
     * @type {ServiceInstance}
     * @memberof ManagedService
     */
    instance?: ServiceInstance | null;
    /**
     * What the object is actually called inside the engine — `acme_hearth_db` for a
     * database, `acme-hearth-media` for a bucket.
     * @type {string}
     * @memberof ManagedService
     */
    backingName?: string;
    /**
     * A bucket's access key id — the non-secret half of a Garage key, paired with
     * {@see $credentialCiphertext}'s sealed secret access key. Null for every
     * database kind, which has no such pair: its one credential is a password,
     * sealed whole into the four columns above.
     * @type {string}
     * @memberof ManagedService
     */
    externalKeyId?: string | null;
    /**
     * 
     * @type {ManagedServiceQuotaBytes}
     * @memberof ManagedService
     */
    quotaBytes?: ManagedServiceQuotaBytes | null;
    /**
     * Operator override of the backend pool size — how many connections each of
     * this service's proxies holds open to the engine (`default_pool_size` on
     * pgbouncer, `mysql_servers.max_connections` on ProxySQL). Null means the
     * generator's own default; the effective number is always asked of the
     * generator ({@see \App\Service\ManagedService\Sidecar\SidecarConfigGenerator::poolSizeFor()}),
     * never read from here directly, so the default lives in one place.
     * @type {number}
     * @memberof ManagedService
     */
    poolSizeOverride?: number | null;
    /**
     * Operator override of the client-side connection ceiling — how many client
     * connections each proxy will accept (`max_client_conn` on pgbouncer,
     * `mysql-max_connections` on ProxySQL). Same null-means-default and
     * ask-the-generator contract as {@see $poolSizeOverride}.
     * @type {number}
     * @memberof ManagedService
     */
    clientConnectionsOverride?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ManagedService
     */
    state?: ManagedServiceStateEnum;
    /**
     * 
     * @type {string}
     * @memberof ManagedService
     */
    readonly failureReason?: string | null;
    /**
     * Why the service is suspended, or null when a state of `suspended` was put
     * there by an operator or the tenant rather than by the platform.
     * @type {string}
     * @memberof ManagedService
     */
    suspensionReason?: ManagedServiceSuspensionReasonEnum | null;
    /**
     * 
     * @type {ManagedServiceUsageBytes}
     * @memberof ManagedService
     */
    usageBytes?: ManagedServiceUsageBytes | null;
    /**
     * 
     * @type {Date}
     * @memberof ManagedService
     */
    readonly usageSampledAt?: Date | null;
    /**
     * 
     * @type {ManagedServiceLastLoadMillis}
     * @memberof ManagedService
     */
    lastLoadMillis?: ManagedServiceLastLoadMillis | null;
    /**
     * 
     * @type {Date}
     * @memberof ManagedService
     */
    readonly lastLoadSampledAt?: Date | null;
    /**
     * 
     * @type {ManagedServicePendingLoadMillis}
     * @memberof ManagedService
     */
    pendingLoadMillis?: ManagedServicePendingLoadMillis;
    /**
     * 
     * @type {Array<string>}
     * @memberof ManagedService
     */
    bindings?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ManagedService
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ManagedService
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ManagedService
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ManagedService
     */
    readonly updatedAt?: Date | null;
    /**
     * `postgres 17`, `mysql 8.0` — the catalogue entry, as one string.
     * @type {string}
     * @memberof ManagedService
     */
    readonly catalogueEntry?: string;
    /**
     * 
     * @type {SealedSecret}
     * @memberof ManagedService
     */
    credential?: SealedSecret;
    /**
     * 
     * @type {boolean}
     * @memberof ManagedService
     */
    readonly available?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ManagedService
     */
    readonly deleted?: boolean;
}


/**
 * @export
 */
export const ManagedServiceKindEnum = {
    Postgres: 'postgres',
    Mariadb: 'mariadb',
    Mysql: 'mysql',
    Garage: 'garage'
} as const;
export type ManagedServiceKindEnum = typeof ManagedServiceKindEnum[keyof typeof ManagedServiceKindEnum];

/**
 * @export
 */
export const ManagedServiceStateEnum = {
    Requested: 'requested',
    Creating: 'creating',
    Available: 'available',
    Suspended: 'suspended',
    Dropping: 'dropping',
    Dropped: 'dropped',
    Failed: 'failed'
} as const;
export type ManagedServiceStateEnum = typeof ManagedServiceStateEnum[keyof typeof ManagedServiceStateEnum];

/**
 * @export
 */
export const ManagedServiceSuspensionReasonEnum = {
    CreditExhausted: 'credit_exhausted',
    OverQuota: 'over_quota'
} as const;
export type ManagedServiceSuspensionReasonEnum = typeof ManagedServiceSuspensionReasonEnum[keyof typeof ManagedServiceSuspensionReasonEnum];


/**
 * Check if a given object implements the ManagedService interface.
 */
export function instanceOfManagedService(value: object): value is ManagedService {
    return true;
}

export function ManagedServiceFromJSON(json: any): ManagedService {
    return ManagedServiceFromJSONTyped(json, false);
}

export function ManagedServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedService {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': json['organization'] == null ? undefined : json['organization'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'majorVersion': json['majorVersion'] == null ? undefined : json['majorVersion'],
        'instance': json['instance'] == null ? undefined : ServiceInstanceFromJSON(json['instance']),
        'backingName': json['backingName'] == null ? undefined : json['backingName'],
        'externalKeyId': json['externalKeyId'] == null ? undefined : json['externalKeyId'],
        'quotaBytes': json['quotaBytes'] == null ? undefined : ManagedServiceQuotaBytesFromJSON(json['quotaBytes']),
        'poolSizeOverride': json['poolSizeOverride'] == null ? undefined : json['poolSizeOverride'],
        'clientConnectionsOverride': json['clientConnectionsOverride'] == null ? undefined : json['clientConnectionsOverride'],
        'state': json['state'] == null ? undefined : json['state'],
        'failureReason': json['failureReason'] == null ? undefined : json['failureReason'],
        'suspensionReason': json['suspensionReason'] == null ? undefined : json['suspensionReason'],
        'usageBytes': json['usageBytes'] == null ? undefined : ManagedServiceUsageBytesFromJSON(json['usageBytes']),
        'usageSampledAt': json['usageSampledAt'] == null ? undefined : (new Date(json['usageSampledAt'])),
        'lastLoadMillis': json['lastLoadMillis'] == null ? undefined : ManagedServiceLastLoadMillisFromJSON(json['lastLoadMillis']),
        'lastLoadSampledAt': json['lastLoadSampledAt'] == null ? undefined : (new Date(json['lastLoadSampledAt'])),
        'pendingLoadMillis': json['pendingLoadMillis'] == null ? undefined : ManagedServicePendingLoadMillisFromJSON(json['pendingLoadMillis']),
        'bindings': json['bindings'] == null ? undefined : json['bindings'],
        'id': json['id'] == null ? undefined : json['id'],
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'catalogueEntry': json['catalogueEntry'] == null ? undefined : json['catalogueEntry'],
        'credential': json['credential'] == null ? undefined : SealedSecretFromJSON(json['credential']),
        'available': json['available'] == null ? undefined : json['available'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function ManagedServiceToJSON(json: any): ManagedService {
    return ManagedServiceToJSONTyped(json, false);
}

export function ManagedServiceToJSONTyped(value?: Omit<ManagedService, 'failureReason'|'usageSampledAt'|'lastLoadSampledAt'|'id'|'deletedAt'|'createdAt'|'updatedAt'|'catalogueEntry'|'available'|'deleted'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': value['organization'],
        'slug': value['slug'],
        'kind': value['kind'],
        'majorVersion': value['majorVersion'],
        'instance': ServiceInstanceToJSON(value['instance']),
        'backingName': value['backingName'],
        'externalKeyId': value['externalKeyId'],
        'quotaBytes': ManagedServiceQuotaBytesToJSON(value['quotaBytes']),
        'poolSizeOverride': value['poolSizeOverride'],
        'clientConnectionsOverride': value['clientConnectionsOverride'],
        'state': value['state'],
        'suspensionReason': value['suspensionReason'],
        'usageBytes': ManagedServiceUsageBytesToJSON(value['usageBytes']),
        'lastLoadMillis': ManagedServiceLastLoadMillisToJSON(value['lastLoadMillis']),
        'pendingLoadMillis': ManagedServicePendingLoadMillisToJSON(value['pendingLoadMillis']),
        'bindings': value['bindings'],
        'credential': SealedSecretToJSON(value['credential']),
    };
}

