/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Latest metered size. Suspended services keep reporting it — they are still billed for storage.
 * @export
 * @interface ManagedServiceUsageBytes
 */
export interface ManagedServiceUsageBytes {
}

/**
 * Check if a given object implements the ManagedServiceUsageBytes interface.
 */
export function instanceOfManagedServiceUsageBytes(value: object): value is ManagedServiceUsageBytes {
    return true;
}

export function ManagedServiceUsageBytesFromJSON(json: any): ManagedServiceUsageBytes {
    return ManagedServiceUsageBytesFromJSONTyped(json, false);
}

export function ManagedServiceUsageBytesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedServiceUsageBytes {
    return json;
}

export function ManagedServiceUsageBytesToJSON(json: any): ManagedServiceUsageBytes {
    return ManagedServiceUsageBytesToJSONTyped(json, false);
}

export function ManagedServiceUsageBytesToJSONTyped(value?: ManagedServiceUsageBytes | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

