/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The engine's own cumulative exec-time counter as of the last sample, in
 * milliseconds — the baseline {@see \App\Service\ManagedService\LoadSampler}
 * subtracts from the next reading to get a delta, the same shape
 * {@see \App\Entity\Task::$lastCpuNanos} uses for a container's CPU rate.
 * @export
 * @interface ManagedServiceLastLoadMillis
 */
export interface ManagedServiceLastLoadMillis {
}

/**
 * Check if a given object implements the ManagedServiceLastLoadMillis interface.
 */
export function instanceOfManagedServiceLastLoadMillis(value: object): value is ManagedServiceLastLoadMillis {
    return true;
}

export function ManagedServiceLastLoadMillisFromJSON(json: any): ManagedServiceLastLoadMillis {
    return ManagedServiceLastLoadMillisFromJSONTyped(json, false);
}

export function ManagedServiceLastLoadMillisFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedServiceLastLoadMillis {
    return json;
}

export function ManagedServiceLastLoadMillisToJSON(json: any): ManagedServiceLastLoadMillis {
    return ManagedServiceLastLoadMillisToJSONTyped(json, false);
}

export function ManagedServiceLastLoadMillisToJSONTyped(value?: ManagedServiceLastLoadMillis | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

