/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Byte ceiling this service must not exceed; null where none is set.
 * @export
 * @interface ManagedServiceQuotaBytes
 */
export interface ManagedServiceQuotaBytes {
}

/**
 * Check if a given object implements the ManagedServiceQuotaBytes interface.
 */
export function instanceOfManagedServiceQuotaBytes(value: object): value is ManagedServiceQuotaBytes {
    return true;
}

export function ManagedServiceQuotaBytesFromJSON(json: any): ManagedServiceQuotaBytes {
    return ManagedServiceQuotaBytesFromJSONTyped(json, false);
}

export function ManagedServiceQuotaBytesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedServiceQuotaBytes {
    return json;
}

export function ManagedServiceQuotaBytesToJSON(json: any): ManagedServiceQuotaBytes {
    return ManagedServiceQuotaBytesToJSONTyped(json, false);
}

export function ManagedServiceQuotaBytesToJSONTyped(value?: ManagedServiceQuotaBytes | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

