/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Create a new managed service (database or bucket) on a shared engine.
 * @export
 * @interface ManagedServiceManagedServiceInput
 */
export interface ManagedServiceManagedServiceInput {
    /**
     * The engine, as the catalogue names it — `postgres:17`, `mysql:8.0`.
     * @type {string}
     * @memberof ManagedServiceManagedServiceInput
     */
    engine: string;
    /**
     * The tenant's own name for it — what appears in the UI and in `sc service ls`.
     * @type {string}
     * @memberof ManagedServiceManagedServiceInput
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof ManagedServiceManagedServiceInput
     */
    organization: string | null;
}

/**
 * Check if a given object implements the ManagedServiceManagedServiceInput interface.
 */
export function instanceOfManagedServiceManagedServiceInput(value: object): value is ManagedServiceManagedServiceInput {
    if (!('engine' in value) || value['engine'] === undefined) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('organization' in value) || value['organization'] === undefined) return false;
    return true;
}

export function ManagedServiceManagedServiceInputFromJSON(json: any): ManagedServiceManagedServiceInput {
    return ManagedServiceManagedServiceInputFromJSONTyped(json, false);
}

export function ManagedServiceManagedServiceInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedServiceManagedServiceInput {
    if (json == null) {
        return json;
    }
    return {
        
        'engine': json['engine'],
        'slug': json['slug'],
        'organization': json['organization'],
    };
}

export function ManagedServiceManagedServiceInputToJSON(json: any): ManagedServiceManagedServiceInput {
    return ManagedServiceManagedServiceInputToJSONTyped(json, false);
}

export function ManagedServiceManagedServiceInputToJSONTyped(value?: ManagedServiceManagedServiceInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'engine': value['engine'],
        'slug': value['slug'],
        'organization': value['organization'],
    };
}

