/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Engine-milliseconds accrued since the last hourly bill, in milliseconds.
 * @export
 * @interface ManagedServicePendingLoadMillis
 */
export interface ManagedServicePendingLoadMillis {
}

/**
 * Check if a given object implements the ManagedServicePendingLoadMillis interface.
 */
export function instanceOfManagedServicePendingLoadMillis(value: object): value is ManagedServicePendingLoadMillis {
    return true;
}

export function ManagedServicePendingLoadMillisFromJSON(json: any): ManagedServicePendingLoadMillis {
    return ManagedServicePendingLoadMillisFromJSONTyped(json, false);
}

export function ManagedServicePendingLoadMillisFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManagedServicePendingLoadMillis {
    return json;
}

export function ManagedServicePendingLoadMillisToJSON(json: any): ManagedServicePendingLoadMillis {
    return ManagedServicePendingLoadMillisToJSONTyped(json, false);
}

export function ManagedServicePendingLoadMillisToJSONTyped(value?: ManagedServicePendingLoadMillis | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

