/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface Membership
 */
export interface Membership {
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    organization?: string;
    /**
     * 
     * @type {User}
     * @memberof Membership
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    role?: MembershipRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof Membership
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Membership
     */
    readonly updatedAt?: Date | null;
}


/**
 * @export
 */
export const MembershipRoleEnum = {
    Owner: 'owner',
    Admin: 'admin',
    Member: 'member'
} as const;
export type MembershipRoleEnum = typeof MembershipRoleEnum[keyof typeof MembershipRoleEnum];


/**
 * Check if a given object implements the Membership interface.
 */
export function instanceOfMembership(value: object): value is Membership {
    return true;
}

export function MembershipFromJSON(json: any): Membership {
    return MembershipFromJSONTyped(json, false);
}

export function MembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): Membership {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': json['organization'] == null ? undefined : json['organization'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'role': json['role'] == null ? undefined : json['role'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function MembershipToJSON(json: any): Membership {
    return MembershipToJSONTyped(json, false);
}

export function MembershipToJSONTyped(value?: Omit<Membership, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': value['organization'],
        'user': UserToJSON(value['user']),
        'role': value['role'],
    };
}

