/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A representation of common errors.
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * A short, human-readable summary of the problem.
     * @type {string}
     * @memberof ModelError
     */
    readonly title?: string | null;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     * @type {string}
     * @memberof ModelError
     */
    readonly detail?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ModelError
     */
    status?: number | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
     * @type {string}
     * @memberof ModelError
     */
    readonly instance?: string | null;
    /**
     * A URI reference that identifies the problem type
     * @type {string}
     * @memberof ModelError
     */
    readonly type?: string;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'status': json['status'] == null ? undefined : json['status'],
        'instance': json['instance'] == null ? undefined : json['instance'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ModelErrorToJSON(json: any): ModelError {
    return ModelErrorToJSONTyped(json, false);
}

export function ModelErrorToJSONTyped(value?: Omit<ModelError, 'title'|'detail'|'instance'|'type'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

