/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface OAuthIdentity
 */
export interface OAuthIdentity {
    /**
     * 
     * @type {string}
     * @memberof OAuthIdentity
     */
    provider?: OAuthIdentityProviderEnum;
    /**
     * The stable, provider-assigned user id (never the email).
     * @type {string}
     * @memberof OAuthIdentity
     */
    providerUserId?: string;
    /**
     * 
     * @type {User}
     * @memberof OAuthIdentity
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof OAuthIdentity
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof OAuthIdentity
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OAuthIdentity
     */
    readonly updatedAt?: Date | null;
}


/**
 * @export
 */
export const OAuthIdentityProviderEnum = {
    Github: 'github',
    Google: 'google'
} as const;
export type OAuthIdentityProviderEnum = typeof OAuthIdentityProviderEnum[keyof typeof OAuthIdentityProviderEnum];


/**
 * Check if a given object implements the OAuthIdentity interface.
 */
export function instanceOfOAuthIdentity(value: object): value is OAuthIdentity {
    return true;
}

export function OAuthIdentityFromJSON(json: any): OAuthIdentity {
    return OAuthIdentityFromJSONTyped(json, false);
}

export function OAuthIdentityFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthIdentity {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'] == null ? undefined : json['provider'],
        'providerUserId': json['providerUserId'] == null ? undefined : json['providerUserId'],
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function OAuthIdentityToJSON(json: any): OAuthIdentity {
    return OAuthIdentityToJSONTyped(json, false);
}

export function OAuthIdentityToJSONTyped(value?: Omit<OAuthIdentity, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'providerUserId': value['providerUserId'],
        'user': UserToJSON(value['user']),
    };
}

