/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationSignal
 */
export interface OrganizationSignal {
    /**
     * 
     * @type {string}
     * @memberof OrganizationSignal
     */
    organization?: string;
    /**
     * Which application's compose file produced it — deleting the application does not un-say what it asked for.
     * @type {string}
     * @memberof OrganizationSignal
     */
    application?: string | null;
    /**
     * Verbatim, as {@see \App\Service\Compose\ComposeParser::parse()} produced it.
     * @type {string}
     * @memberof OrganizationSignal
     */
    reason?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSignal
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationSignal
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationSignal
     */
    readonly updatedAt?: Date | null;
}

/**
 * Check if a given object implements the OrganizationSignal interface.
 */
export function instanceOfOrganizationSignal(value: object): value is OrganizationSignal {
    return true;
}

export function OrganizationSignalFromJSON(json: any): OrganizationSignal {
    return OrganizationSignalFromJSONTyped(json, false);
}

export function OrganizationSignalFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationSignal {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': json['organization'] == null ? undefined : json['organization'],
        'application': json['application'] == null ? undefined : json['application'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function OrganizationSignalToJSON(json: any): OrganizationSignal {
    return OrganizationSignalToJSONTyped(json, false);
}

export function OrganizationSignalToJSONTyped(value?: Omit<OrganizationSignal, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': value['organization'],
        'application': value['application'],
        'reason': value['reason'],
    };
}

