/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrganizationSignal } from './OrganizationSignal';
import {
    OrganizationSignalFromJSON,
    OrganizationSignalFromJSONTyped,
    OrganizationSignalToJSON,
    OrganizationSignalToJSONTyped,
} from './OrganizationSignal';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Variable } from './Variable';
import {
    VariableFromJSON,
    VariableFromJSONTyped,
    VariableToJSON,
    VariableToJSONTyped,
} from './Variable';
import type { Membership } from './Membership';
import {
    MembershipFromJSON,
    MembershipFromJSONTyped,
    MembershipToJSON,
    MembershipToJSONTyped,
} from './Membership';
import type { Machine } from './Machine';
import {
    MachineFromJSON,
    MachineFromJSONTyped,
    MachineToJSON,
    MachineToJSONTyped,
} from './Machine';

/**
 * Ownership and (future) billing boundary. Owns applications, may own BYO swarms.
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * 
     * @type {User}
     * @memberof Organization
     */
    machineAccount?: User | null;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    name?: string;
    /**
     * `unique: true` stops two organizations holding the same *string*; the
     * constraint stops two holding strings that fold to the same **stack name**,
     * which the database has no way to express (#860). Both are needed: the
     * column guards the identifier, the constraint guards what is derived from it.
     * @type {string}
     * @memberof Organization
     */
    slug?: string;
    /**
     * The skin this organization's members see, or null to take the instance's.
     * @type {string}
     * @memberof Organization
     */
    theme?: OrganizationThemeEnum | null;
    /**
     * An operator's grant of a tier this organization would not reach through
     * any member — {@see \App\Enum\AccountTier::Verified} in particular, which
     * is granted rather than earned and belongs to a contractual relationship
     * with the *organization*, not incidentally to whichever of its members
     * happens to carry the highest personal tier
     * ({@see \App\Service\Trust\TierResolver::forOrganization()}). A member
     * individually pinned `Verified` still lifts the org the same way a
     * `Trusted` member always has — this pin is for granting it to the org
     * directly, without needing a person to hang it on.
     * @type {string}
     * @memberof Organization
     */
    readonly tierPin?: OrganizationTierPinEnum | null;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    readonly tierPinnedAt?: Date | null;
    /**
     * 
     * @type {User}
     * @memberof Organization
     */
    tierPinnedBy?: User | null;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    readonly tierPinReason?: string | null;
    /**
     * When {@see \App\MessageHandler\CheckRunwayHandler} last warned this
     * organization that its projected runway had dropped below the
     * threshold; null once no warning is outstanding. Set once per crossing
     * and cleared the moment the projection recovers — by a top-up or by the
     * burn easing off — which is what makes "warn once, re-arm on recovery"
     * a fact this column can answer rather than something re-derived from
     * the notification table on every tick.
     * @type {Date}
     * @memberof Organization
     */
    readonly lowBalanceWarnedAt?: Date | null;
    /**
     * When an Owner/Admin turned on the requirement that every member of this
     * organization protects their account with a second factor; null means it is
     * optional. A reversible policy toggle, stamped like {@see User::$disabledAt}
     * rather than a verdict, so no "who set it" attribution.
     * @type {Date}
     * @memberof Organization
     */
    readonly twoFactorRequiredAt?: Date | null;
    /**
     * 
     * @type {Array<Membership>}
     * @memberof Organization
     */
    memberships?: Array<Membership>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Organization
     */
    applications?: Array<string>;
    /**
     * BYO swarms owned by this organization.
     * @type {Array<string>}
     * @memberof Organization
     */
    swarms?: Array<string>;
    /**
     * 
     * @type {Array<Machine>}
     * @memberof Organization
     */
    machines?: Array<Machine>;
    /**
     * The append-only credit ledger.
     * @type {Array<string>}
     * @memberof Organization
     */
    creditTransactions?: Array<string>;
    /**
     * 
     * @type {Array<Variable>}
     * @memberof Organization
     */
    variables?: Array<Variable>;
    /**
     * 
     * @type {Array<OrganizationSignal>}
     * @memberof Organization
     */
    signals?: Array<OrganizationSignal>;
    /**
     * 
     * @type {string}
     * @memberof Organization
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Organization
     */
    readonly updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof Organization
     */
    readonly tierPinned?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Organization
     */
    readonly deleted?: boolean;
}


/**
 * @export
 */
export const OrganizationThemeEnum = {
    House: 'house',
    Corporate: 'corporate',
    Dull: 'dull',
    Plain: 'plain',
    RedLabel: 'red-label'
} as const;
export type OrganizationThemeEnum = typeof OrganizationThemeEnum[keyof typeof OrganizationThemeEnum];

/**
 * @export
 */
export const OrganizationTierPinEnum = {
    Untrusted: 'untrusted',
    Trusted: 'trusted',
    Verified: 'verified'
} as const;
export type OrganizationTierPinEnum = typeof OrganizationTierPinEnum[keyof typeof OrganizationTierPinEnum];


/**
 * Check if a given object implements the Organization interface.
 */
export function instanceOfOrganization(value: object): value is Organization {
    return true;
}

export function OrganizationFromJSON(json: any): Organization {
    return OrganizationFromJSONTyped(json, false);
}

export function OrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Organization {
    if (json == null) {
        return json;
    }
    return {
        
        'machineAccount': json['machineAccount'] == null ? undefined : UserFromJSON(json['machineAccount']),
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'tierPin': json['tierPin'] == null ? undefined : json['tierPin'],
        'tierPinnedAt': json['tierPinnedAt'] == null ? undefined : (new Date(json['tierPinnedAt'])),
        'tierPinnedBy': json['tierPinnedBy'] == null ? undefined : UserFromJSON(json['tierPinnedBy']),
        'tierPinReason': json['tierPinReason'] == null ? undefined : json['tierPinReason'],
        'lowBalanceWarnedAt': json['lowBalanceWarnedAt'] == null ? undefined : (new Date(json['lowBalanceWarnedAt'])),
        'twoFactorRequiredAt': json['twoFactorRequiredAt'] == null ? undefined : (new Date(json['twoFactorRequiredAt'])),
        'memberships': json['memberships'] == null ? undefined : ((json['memberships'] as Array<any>).map(MembershipFromJSON)),
        'applications': json['applications'] == null ? undefined : json['applications'],
        'swarms': json['swarms'] == null ? undefined : json['swarms'],
        'machines': json['machines'] == null ? undefined : ((json['machines'] as Array<any>).map(MachineFromJSON)),
        'creditTransactions': json['creditTransactions'] == null ? undefined : json['creditTransactions'],
        'variables': json['variables'] == null ? undefined : ((json['variables'] as Array<any>).map(VariableFromJSON)),
        'signals': json['signals'] == null ? undefined : ((json['signals'] as Array<any>).map(OrganizationSignalFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'tierPinned': json['tierPinned'] == null ? undefined : json['tierPinned'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function OrganizationToJSON(json: any): Organization {
    return OrganizationToJSONTyped(json, false);
}

export function OrganizationToJSONTyped(value?: Omit<Organization, 'tierPin'|'tierPinnedAt'|'tierPinReason'|'lowBalanceWarnedAt'|'twoFactorRequiredAt'|'id'|'deletedAt'|'createdAt'|'updatedAt'|'tierPinned'|'deleted'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'machineAccount': UserToJSON(value['machineAccount']),
        'name': value['name'],
        'slug': value['slug'],
        'theme': value['theme'],
        'tierPinnedBy': UserToJSON(value['tierPinnedBy']),
        'memberships': value['memberships'] == null ? undefined : ((value['memberships'] as Array<any>).map(MembershipToJSON)),
        'applications': value['applications'],
        'swarms': value['swarms'],
        'machines': value['machines'] == null ? undefined : ((value['machines'] as Array<any>).map(MachineToJSON)),
        'creditTransactions': value['creditTransactions'],
        'variables': value['variables'] == null ? undefined : ((value['variables'] as Array<any>).map(VariableToJSON)),
        'signals': value['signals'] == null ? undefined : ((value['signals'] as Array<any>).map(OrganizationSignalToJSON)),
    };
}

