/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PortAllocation
 */
export interface PortAllocation {
    /**
     * The cluster this port is claimed on. Deleting the cluster takes its
     * allocations with it — a reservation on a swarm that no longer exists is not
     * holding anything back.
     * @type {string}
     * @memberof PortAllocation
     */
    swarm?: string;
    /**
     * 
     * @type {string}
     * @memberof PortAllocation
     */
    application?: string;
    /**
     * The deployment name this reservation belongs to — {@see Deployment::$name},
     * or `''` for a revision that carries no name (before the field existed, or a
     * client that never sent one), which is its own stable scope rather than a
     * wildcard: every unnamed revision of an application shares it, exactly the
     * single continuous scope every application had before this column existed.
     * @type {string}
     * @memberof PortAllocation
     */
    deploymentName?: string;
    /**
     * The compose service name, as the customer's file spells it.
     * @type {string}
     * @memberof PortAllocation
     */
    serviceName?: string;
    /**
     * The container port traffic is forwarded to.
     * @type {number}
     * @memberof PortAllocation
     */
    targetPort?: number;
    /**
     * 
     * @type {string}
     * @memberof PortAllocation
     */
    protocol?: PortAllocationProtocolEnum;
    /**
     * What the world connects to. Unique per protocol on this cluster.
     * @type {number}
     * @memberof PortAllocation
     */
    publishedPort?: number;
    /**
     * Whether the platform chose this number or the compose file did.
     * @type {boolean}
     * @memberof PortAllocation
     */
    assigned?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PortAllocation
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof PortAllocation
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PortAllocation
     */
    readonly updatedAt?: Date | null;
}


/**
 * @export
 */
export const PortAllocationProtocolEnum = {
    Tcp: 'tcp',
    Udp: 'udp'
} as const;
export type PortAllocationProtocolEnum = typeof PortAllocationProtocolEnum[keyof typeof PortAllocationProtocolEnum];


/**
 * Check if a given object implements the PortAllocation interface.
 */
export function instanceOfPortAllocation(value: object): value is PortAllocation {
    return true;
}

export function PortAllocationFromJSON(json: any): PortAllocation {
    return PortAllocationFromJSONTyped(json, false);
}

export function PortAllocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PortAllocation {
    if (json == null) {
        return json;
    }
    return {
        
        'swarm': json['swarm'] == null ? undefined : json['swarm'],
        'application': json['application'] == null ? undefined : json['application'],
        'deploymentName': json['deploymentName'] == null ? undefined : json['deploymentName'],
        'serviceName': json['serviceName'] == null ? undefined : json['serviceName'],
        'targetPort': json['targetPort'] == null ? undefined : json['targetPort'],
        'protocol': json['protocol'] == null ? undefined : json['protocol'],
        'publishedPort': json['publishedPort'] == null ? undefined : json['publishedPort'],
        'assigned': json['assigned'] == null ? undefined : json['assigned'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function PortAllocationToJSON(json: any): PortAllocation {
    return PortAllocationToJSONTyped(json, false);
}

export function PortAllocationToJSONTyped(value?: Omit<PortAllocation, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'swarm': value['swarm'],
        'application': value['application'],
        'deploymentName': value['deploymentName'],
        'serviceName': value['serviceName'],
        'targetPort': value['targetPort'],
        'protocol': value['protocol'],
        'publishedPort': value['publishedPort'],
        'assigned': value['assigned'],
    };
}

