/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProxmoxInstance
 */
export interface ProxmoxInstance {
    /**
     * 
     * @type {string}
     * @memberof ProxmoxInstance
     */
    name?: string;
    /**
     * Base URL of the API, scheme and authority only — `https://10.0.0.68:8006`.
     * @type {string}
     * @memberof ProxmoxInstance
     */
    endpoint?: string;
    /**
     * Full token identifier, `user@realm!tokenid` — e.g. `root@pam!someones-computer`.
     * @type {string}
     * @memberof ProxmoxInstance
     */
    tokenId?: string;
    /**
     * The token's secret (a UUID as Proxmox issues it), encrypted at rest and
     * never serialized. Proxmox shows it exactly once, at creation.
     * @type {string}
     * @memberof ProxmoxInstance
     */
    tokenSecret?: string;
    /**
     * Whether the certificate must validate against a CA chain.
     * @type {boolean}
     * @memberof ProxmoxInstance
     */
    verifyTls?: boolean;
    /**
     * base64 SHA-256 of the endpoint's SubjectPublicKeyInfo — curl's
     * `pin-sha256`. The right answer for a self-signed Proxmox: it
     * authenticates *this specific host* without any CA, so the connection is
     * still protected against interception, which `verifyTls = false` alone is
     * not.
     * @type {string}
     * @memberof ProxmoxInstance
     */
    publicKeyPin?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProxmoxInstance
     */
    status?: ProxmoxInstanceStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof ProxmoxInstance
     */
    lastSeenAt?: Date | null;
    /**
     * Why the last probe failed, kept so an operator can tell a revoked token
     * from a dead host without re-running anything. Cleared on success.
     * @type {string}
     * @memberof ProxmoxInstance
     */
    lastError?: string | null;
    /**
     * Observed `GET /version` snapshot (release, repoid). Observed state, so it
     * is whatever the last probe saw and is never authoritative.
     * @type {{ [key: string]: string | null; }}
     * @memberof ProxmoxInstance
     */
    version?: { [key: string]: string | null; };
    /**
     * The vmid of the Alpine template `app:proxmox:template` last built here, or
     * null if it has never been run against this endpoint. This is what makes a
     * template's existence something the app can answer without an SSH session
     * and a `qm list` — the gap that sent an operator to do exactly that.
     * @type {number}
     * @memberof ProxmoxInstance
     */
    readonly templateVmid?: number | null;
    /**
     * The Alpine version baked into {@see $templateVmid}, e.g. `3.23.0`.
     * @type {string}
     * @memberof ProxmoxInstance
     */
    readonly templateAlpineVersion?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ProxmoxInstance
     */
    readonly templateBuiltAt?: Date | null;
    /**
     * When a background template build was dispatched for this endpoint, or null
     * when none is in flight — the only trace a build leaves while it runs.
     * @type {Date}
     * @memberof ProxmoxInstance
     */
    readonly templateBuildStartedAt?: Date | null;
    /**
     * How many builds in a row have failed since the last success, incremented
     * by {@see \App\MessageHandler\BuildProxmoxTemplateHandler}'s catch block
     * and cleared by {@see recordTemplateBuilt()}. This is what
     * {@see templateBuildIsBackedOff()} backs the retry off against — without
     * it, {@see \App\MessageHandler\CheckProxmoxTemplatesHandler} redispatches
     * a build every tick regardless of how many times it has already failed
     * (#1059).
     * @type {number}
     * @memberof ProxmoxInstance
     */
    readonly templateBuildFailures?: number;
    /**
     * 
     * @type {string}
     * @memberof ProxmoxInstance
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProxmoxInstance
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProxmoxInstance
     */
    readonly updatedAt?: Date | null;
    /**
     * Whether `app:proxmox:template` has ever recorded a build against this endpoint.
     * @type {boolean}
     * @memberof ProxmoxInstance
     */
    readonly template?: boolean;
}


/**
 * @export
 */
export const ProxmoxInstanceStatusEnum = {
    Reachable: 'reachable',
    Unreachable: 'unreachable',
    Unauthorized: 'unauthorized'
} as const;
export type ProxmoxInstanceStatusEnum = typeof ProxmoxInstanceStatusEnum[keyof typeof ProxmoxInstanceStatusEnum];


/**
 * Check if a given object implements the ProxmoxInstance interface.
 */
export function instanceOfProxmoxInstance(value: object): value is ProxmoxInstance {
    return true;
}

export function ProxmoxInstanceFromJSON(json: any): ProxmoxInstance {
    return ProxmoxInstanceFromJSONTyped(json, false);
}

export function ProxmoxInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProxmoxInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'tokenId': json['tokenId'] == null ? undefined : json['tokenId'],
        'tokenSecret': json['tokenSecret'] == null ? undefined : json['tokenSecret'],
        'verifyTls': json['verifyTls'] == null ? undefined : json['verifyTls'],
        'publicKeyPin': json['publicKeyPin'] == null ? undefined : json['publicKeyPin'],
        'status': json['status'] == null ? undefined : json['status'],
        'lastSeenAt': json['lastSeenAt'] == null ? undefined : (new Date(json['lastSeenAt'])),
        'lastError': json['lastError'] == null ? undefined : json['lastError'],
        'version': json['version'] == null ? undefined : json['version'],
        'templateVmid': json['templateVmid'] == null ? undefined : json['templateVmid'],
        'templateAlpineVersion': json['templateAlpineVersion'] == null ? undefined : json['templateAlpineVersion'],
        'templateBuiltAt': json['templateBuiltAt'] == null ? undefined : (new Date(json['templateBuiltAt'])),
        'templateBuildStartedAt': json['templateBuildStartedAt'] == null ? undefined : (new Date(json['templateBuildStartedAt'])),
        'templateBuildFailures': json['templateBuildFailures'] == null ? undefined : json['templateBuildFailures'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'template': json['template'] == null ? undefined : json['template'],
    };
}

export function ProxmoxInstanceToJSON(json: any): ProxmoxInstance {
    return ProxmoxInstanceToJSONTyped(json, false);
}

export function ProxmoxInstanceToJSONTyped(value?: Omit<ProxmoxInstance, 'templateVmid'|'templateAlpineVersion'|'templateBuiltAt'|'templateBuildStartedAt'|'templateBuildFailures'|'id'|'createdAt'|'updatedAt'|'template'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'endpoint': value['endpoint'],
        'tokenId': value['tokenId'],
        'tokenSecret': value['tokenSecret'],
        'verifyTls': value['verifyTls'],
        'publicKeyPin': value['publicKeyPin'],
        'status': value['status'],
        'lastSeenAt': value['lastSeenAt'] == null ? undefined : ((value['lastSeenAt'] as any).toISOString()),
        'lastError': value['lastError'],
        'version': value['version'],
    };
}

