/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface RecoveryCode
 */
export interface RecoveryCode {
    /**
     * 
     * @type {User}
     * @memberof RecoveryCode
     */
    user?: User;
    /**
     * SHA-256 hex digest of the plaintext code; the only copy that is ever stored.
     * @type {string}
     * @memberof RecoveryCode
     */
    codeHash?: string;
    /**
     * When this code was spent; null means it is still usable.
     * @type {Date}
     * @memberof RecoveryCode
     */
    readonly usedAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof RecoveryCode
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof RecoveryCode
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof RecoveryCode
     */
    readonly updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof RecoveryCode
     */
    readonly used?: boolean;
}

/**
 * Check if a given object implements the RecoveryCode interface.
 */
export function instanceOfRecoveryCode(value: object): value is RecoveryCode {
    return true;
}

export function RecoveryCodeFromJSON(json: any): RecoveryCode {
    return RecoveryCodeFromJSONTyped(json, false);
}

export function RecoveryCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecoveryCode {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : UserFromJSON(json['user']),
        'codeHash': json['codeHash'] == null ? undefined : json['codeHash'],
        'usedAt': json['usedAt'] == null ? undefined : (new Date(json['usedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'used': json['used'] == null ? undefined : json['used'],
    };
}

export function RecoveryCodeToJSON(json: any): RecoveryCode {
    return RecoveryCodeToJSONTyped(json, false);
}

export function RecoveryCodeToJSONTyped(value?: Omit<RecoveryCode, 'usedAt'|'id'|'createdAt'|'updatedAt'|'used'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user': UserToJSON(value['user']),
        'codeHash': value['codeHash'],
    };
}

