/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SealedSecret
 */
export interface SealedSecret {
    /**
     * 
     * @type {string}
     * @memberof SealedSecret
     */
    algo?: string;
    /**
     * 
     * @type {string}
     * @memberof SealedSecret
     */
    keyId?: string;
    /**
     * 
     * @type {string}
     * @memberof SealedSecret
     */
    nonce?: string;
    /**
     * 
     * @type {string}
     * @memberof SealedSecret
     */
    ciphertext?: string;
}

/**
 * Check if a given object implements the SealedSecret interface.
 */
export function instanceOfSealedSecret(value: object): value is SealedSecret {
    return true;
}

export function SealedSecretFromJSON(json: any): SealedSecret {
    return SealedSecretFromJSONTyped(json, false);
}

export function SealedSecretFromJSONTyped(json: any, ignoreDiscriminator: boolean): SealedSecret {
    if (json == null) {
        return json;
    }
    return {
        
        'algo': json['algo'] == null ? undefined : json['algo'],
        'keyId': json['keyId'] == null ? undefined : json['keyId'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'ciphertext': json['ciphertext'] == null ? undefined : json['ciphertext'],
    };
}

export function SealedSecretToJSON(json: any): SealedSecret {
    return SealedSecretToJSONTyped(json, false);
}

export function SealedSecretToJSONTyped(value?: SealedSecret | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algo': value['algo'],
        'keyId': value['keyId'],
        'nonce': value['nonce'],
        'ciphertext': value['ciphertext'],
    };
}

