/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Bind a managed service to an application.
 * @export
 * @interface ServiceBindingServiceBindingInput
 */
export interface ServiceBindingServiceBindingInput {
    /**
     * 
     * @type {string}
     * @memberof ServiceBindingServiceBindingInput
     */
    application: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceBindingServiceBindingInput
     */
    service: string | null;
}

/**
 * Check if a given object implements the ServiceBindingServiceBindingInput interface.
 */
export function instanceOfServiceBindingServiceBindingInput(value: object): value is ServiceBindingServiceBindingInput {
    if (!('application' in value) || value['application'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    return true;
}

export function ServiceBindingServiceBindingInputFromJSON(json: any): ServiceBindingServiceBindingInput {
    return ServiceBindingServiceBindingInputFromJSONTyped(json, false);
}

export function ServiceBindingServiceBindingInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBindingServiceBindingInput {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'],
        'service': json['service'],
    };
}

export function ServiceBindingServiceBindingInputToJSON(json: any): ServiceBindingServiceBindingInput {
    return ServiceBindingServiceBindingInputToJSONTyped(json, false);
}

export function ServiceBindingServiceBindingInputToJSONTyped(value?: ServiceBindingServiceBindingInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'service': value['service'],
    };
}

