/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Memory floor in bytes (`deploy.resources.reservations.memory`), null = nothing declared.
 * @export
 * @interface ServiceMemReservation
 */
export interface ServiceMemReservation {
}

/**
 * Check if a given object implements the ServiceMemReservation interface.
 */
export function instanceOfServiceMemReservation(value: object): value is ServiceMemReservation {
    return true;
}

export function ServiceMemReservationFromJSON(json: any): ServiceMemReservation {
    return ServiceMemReservationFromJSONTyped(json, false);
}

export function ServiceMemReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceMemReservation {
    return json;
}

export function ServiceMemReservationToJSON(json: any): ServiceMemReservation {
    return ServiceMemReservationToJSONTyped(json, false);
}

export function ServiceMemReservationToJSONTyped(value?: ServiceMemReservation | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

