/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Nanoseconds of CPU the scheduler should hold for each replica
 * (compose `deploy.resources.reservations.cpus`), null = nothing declared.
 * @export
 * @interface ServiceCpuReservation
 */
export interface ServiceCpuReservation {
}

/**
 * Check if a given object implements the ServiceCpuReservation interface.
 */
export function instanceOfServiceCpuReservation(value: object): value is ServiceCpuReservation {
    return true;
}

export function ServiceCpuReservationFromJSON(json: any): ServiceCpuReservation {
    return ServiceCpuReservationFromJSONTyped(json, false);
}

export function ServiceCpuReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceCpuReservation {
    return json;
}

export function ServiceCpuReservationToJSON(json: any): ServiceCpuReservation {
    return ServiceCpuReservationToJSONTyped(json, false);
}

export function ServiceCpuReservationToJSONTyped(value?: ServiceCpuReservation | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

