/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServicePortsInnerValue
 */
export interface ServicePortsInnerValue {
}

/**
 * Check if a given object implements the ServicePortsInnerValue interface.
 */
export function instanceOfServicePortsInnerValue(value: object): value is ServicePortsInnerValue {
    return true;
}

export function ServicePortsInnerValueFromJSON(json: any): ServicePortsInnerValue {
    return ServicePortsInnerValueFromJSONTyped(json, false);
}

export function ServicePortsInnerValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicePortsInnerValue {
    return json;
}

export function ServicePortsInnerValueToJSON(json: any): ServicePortsInnerValue {
    return ServicePortsInnerValueToJSONTyped(json, false);
}

export function ServicePortsInnerValueToJSONTyped(value?: ServicePortsInnerValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

