/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Bytes observed in use across every tenant on this instance.
 * @export
 * @interface ServiceInstanceObservedUsageBytes
 */
export interface ServiceInstanceObservedUsageBytes {
}

/**
 * Check if a given object implements the ServiceInstanceObservedUsageBytes interface.
 */
export function instanceOfServiceInstanceObservedUsageBytes(value: object): value is ServiceInstanceObservedUsageBytes {
    return true;
}

export function ServiceInstanceObservedUsageBytesFromJSON(json: any): ServiceInstanceObservedUsageBytes {
    return ServiceInstanceObservedUsageBytesFromJSONTyped(json, false);
}

export function ServiceInstanceObservedUsageBytesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceInstanceObservedUsageBytes {
    return json;
}

export function ServiceInstanceObservedUsageBytesToJSON(json: any): ServiceInstanceObservedUsageBytes {
    return ServiceInstanceObservedUsageBytesToJSONTyped(json, false);
}

export function ServiceInstanceObservedUsageBytesToJSONTyped(value?: ServiceInstanceObservedUsageBytes | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

