/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SealedSecret } from './SealedSecret';
import {
    SealedSecretFromJSON,
    SealedSecretFromJSONTyped,
    SealedSecretToJSON,
    SealedSecretToJSONTyped,
} from './SealedSecret';

/**
 * That an application may use a managed service — the join the per-application
 * toggle could not express.
 * 
 * Many-to-many by construction: one database can back a web app and its worker,
 * and one application can hold several bindings. Unbinding leaves the data alone;
 * only destroying the {@see ManagedService} touches it.
 * 
 * A binding is also where the *deployment* seam lives. It records which variable
 * names it injects, so the UI can say what an application will receive before it
 * receives it, and so the resolver can show an operator-set variable shadowing a
 * binding rather than silently losing to it.
 * 
 * **Creating one is a permission, not a provisioning step** — nothing at the engine
 * moves. Deleting one withdraws that permission and touches no data, which is why
 * `DELETE` here is a hard delete and `DELETE` on a {@see ManagedService} is not the
 * same kind of verb at all.
 * @export
 * @interface ServiceBinding
 */
export interface ServiceBinding {
    /**
     * 
     * @type {string}
     * @memberof ServiceBinding
     */
    application?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBinding
     */
    service?: string;
    /**
     * The environment variable names this binding contributes — one
     * `DATABASE_URL` for a database, the four `S3_*` names for a bucket.
     * @type {Array<string>}
     * @memberof ServiceBinding
     */
    injectedKeys?: Array<string>;
    /**
     * What the sidecar is called inside the tenant's stack — `db` unless something
     * else claimed the name first.
     * @type {string}
     * @memberof ServiceBinding
     */
    sidecarServiceName?: string;
    /**
     * The compose service this binding replaced, or null for a binding somebody
     * asked for directly.
     * @type {string}
     * @memberof ServiceBinding
     */
    adoptedComposeService?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceBinding
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceBinding
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceBinding
     */
    readonly updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceBinding
     */
    readonly adopted?: boolean;
    /**
     * 
     * @type {SealedSecret}
     * @memberof ServiceBinding
     */
    sidecarCredential?: SealedSecret;
}

/**
 * Check if a given object implements the ServiceBinding interface.
 */
export function instanceOfServiceBinding(value: object): value is ServiceBinding {
    return true;
}

export function ServiceBindingFromJSON(json: any): ServiceBinding {
    return ServiceBindingFromJSONTyped(json, false);
}

export function ServiceBindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBinding {
    if (json == null) {
        return json;
    }
    return {
        
        'application': json['application'] == null ? undefined : json['application'],
        'service': json['service'] == null ? undefined : json['service'],
        'injectedKeys': json['injectedKeys'] == null ? undefined : json['injectedKeys'],
        'sidecarServiceName': json['sidecarServiceName'] == null ? undefined : json['sidecarServiceName'],
        'adoptedComposeService': json['adoptedComposeService'] == null ? undefined : json['adoptedComposeService'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'adopted': json['adopted'] == null ? undefined : json['adopted'],
        'sidecarCredential': json['sidecarCredential'] == null ? undefined : SealedSecretFromJSON(json['sidecarCredential']),
    };
}

export function ServiceBindingToJSON(json: any): ServiceBinding {
    return ServiceBindingToJSONTyped(json, false);
}

export function ServiceBindingToJSONTyped(value?: Omit<ServiceBinding, 'id'|'createdAt'|'updatedAt'|'adopted'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'application': value['application'],
        'service': value['service'],
        'injectedKeys': value['injectedKeys'],
        'sidecarServiceName': value['sidecarServiceName'],
        'adoptedComposeService': value['adoptedComposeService'],
        'sidecarCredential': SealedSecretToJSON(value['sidecarCredential']),
    };
}

