/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceHealthcheckValue
 */
export interface ServiceHealthcheckValue {
}

/**
 * Check if a given object implements the ServiceHealthcheckValue interface.
 */
export function instanceOfServiceHealthcheckValue(value: object): value is ServiceHealthcheckValue {
    return true;
}

export function ServiceHealthcheckValueFromJSON(json: any): ServiceHealthcheckValue {
    return ServiceHealthcheckValueFromJSONTyped(json, false);
}

export function ServiceHealthcheckValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceHealthcheckValue {
    return json;
}

export function ServiceHealthcheckValueToJSON(json: any): ServiceHealthcheckValue {
    return ServiceHealthcheckValueToJSONTyped(json, false);
}

export function ServiceHealthcheckValueToJSONTyped(value?: ServiceHealthcheckValue | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

