/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceMemReservation } from './ServiceMemReservation';
import {
    ServiceMemReservationFromJSON,
    ServiceMemReservationFromJSONTyped,
    ServiceMemReservationToJSON,
    ServiceMemReservationToJSONTyped,
} from './ServiceMemReservation';
import type { ServiceMemLimit } from './ServiceMemLimit';
import {
    ServiceMemLimitFromJSON,
    ServiceMemLimitFromJSONTyped,
    ServiceMemLimitToJSON,
    ServiceMemLimitToJSONTyped,
} from './ServiceMemLimit';
import type { ServiceCpuLimit } from './ServiceCpuLimit';
import {
    ServiceCpuLimitFromJSON,
    ServiceCpuLimitFromJSONTyped,
    ServiceCpuLimitToJSON,
    ServiceCpuLimitToJSONTyped,
} from './ServiceCpuLimit';
import type { ServiceCpuReservation } from './ServiceCpuReservation';
import {
    ServiceCpuReservationFromJSON,
    ServiceCpuReservationFromJSONTyped,
    ServiceCpuReservationToJSON,
    ServiceCpuReservationToJSONTyped,
} from './ServiceCpuReservation';
import type { ServiceHealthcheckValue } from './ServiceHealthcheckValue';
import {
    ServiceHealthcheckValueFromJSON,
    ServiceHealthcheckValueFromJSONTyped,
    ServiceHealthcheckValueToJSON,
    ServiceHealthcheckValueToJSONTyped,
} from './ServiceHealthcheckValue';
import type { ServicePortsInnerValue } from './ServicePortsInnerValue';
import {
    ServicePortsInnerValueFromJSON,
    ServicePortsInnerValueFromJSONTyped,
    ServicePortsInnerValueToJSON,
    ServicePortsInnerValueToJSONTyped,
} from './ServicePortsInnerValue';

/**
 * 
 * @export
 * @interface Service
 */
export interface Service {
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    deployment?: string;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    image?: string;
    /**
     * 
     * @type {number}
     * @memberof Service
     */
    replicas?: number;
    /**
     * 
     * @type {ServiceCpuLimit}
     * @memberof Service
     */
    cpuLimit?: ServiceCpuLimit | null;
    /**
     * 
     * @type {ServiceMemLimit}
     * @memberof Service
     */
    memLimit?: ServiceMemLimit | null;
    /**
     * 
     * @type {ServiceCpuReservation}
     * @memberof Service
     */
    cpuReservation?: ServiceCpuReservation | null;
    /**
     * 
     * @type {ServiceMemReservation}
     * @memberof Service
     */
    memReservation?: ServiceMemReservation | null;
    /**
     * 
     * @type {Array<{ [key: string]: ServicePortsInnerValue; }>}
     * @memberof Service
     */
    ports?: Array<{ [key: string]: ServicePortsInnerValue; }> | null;
    /**
     * The container port this service speaks HTTP on, as compose's
     * `x-someones.http` declared it — null means nothing was declared and
     * {@see \App\Service\Ingress\IngressPlanner} falls back to the well-known
     * ports.
     * @type {number}
     * @memberof Service
     */
    httpPort?: number | null;
    /**
     * The container's argv, as compose `command:` declared it — already split into
     * words by the parser, because Swarm's `Args` is argv rather than a line.
     * @type {Array<string>}
     * @memberof Service
     */
    command?: Array<string> | null;
    /**
     * The container's `Command` — compose `entrypoint:`, which replaces the
     * image's own `ENTRYPOINT` rather than feeding it, unlike {@see $command}.
     * @type {Array<string>}
     * @memberof Service
     */
    entrypoint?: Array<string> | null;
    /**
     * Compose `healthcheck:`, projected straight from {@see \App\Service\Compose\ComposeParser::healthcheck()}
     * into the shape {@see \App\Service\Deploy\StackDeployer} sends as Swarm's
     * `ContainerSpec.Healthcheck` — `test` is a `NONE`/`CMD`/`CMD-SHELL` argv,
     * the rest are nanoseconds/a count. Null means nothing was declared, so an
     * image's own baked-in `HEALTHCHECK` (or none) stands; `disable: true` in
     * the compose file is not null, it is `test: ["NONE"]` — an explicit
     * instruction rather than silence.
     * @type {{ [key: string]: ServiceHealthcheckValue; }}
     * @memberof Service
     */
    healthcheck?: { [key: string]: ServiceHealthcheckValue; };
    /**
     * What happens when a container exits; also decides service vs job.
     * @type {string}
     * @memberof Service
     */
    restart?: ServiceRestartEnum;
    /**
     * Set while this service's image arrived by client-side forwarding
     * (docs/registry.md's "Client-side forwarding" callout) and no scan verdict
     * is yet on record for the digest it was pinned to — bytes from a user's
     * machine, not a source tree we built or a registry we chose to trust. A
     * forwarded image is scanned as it loads ({@see \App\MessageHandler\BuildBundleHandler}),
     * so this is normally cleared by the time the service is projected; one left
     * set is a forwarded image that reached deploy unvetted, which
     * {@see \App\MessageHandler\DeployRevisionHandler} refuses to run
     * (docs/image-scanning.md).
     * @type {boolean}
     * @memberof Service
     */
    forwardedUnscanned?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Service
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Service
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Service
     */
    readonly updatedAt?: Date | null;
}


/**
 * @export
 */
export const ServiceRestartEnum = {
    Always: 'always',
    OnFailure: 'on-failure',
    Never: 'never'
} as const;
export type ServiceRestartEnum = typeof ServiceRestartEnum[keyof typeof ServiceRestartEnum];


/**
 * Check if a given object implements the Service interface.
 */
export function instanceOfService(value: object): value is Service {
    return true;
}

export function ServiceFromJSON(json: any): Service {
    return ServiceFromJSONTyped(json, false);
}

export function ServiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Service {
    if (json == null) {
        return json;
    }
    return {
        
        'deployment': json['deployment'] == null ? undefined : json['deployment'],
        'name': json['name'] == null ? undefined : json['name'],
        'image': json['image'] == null ? undefined : json['image'],
        'replicas': json['replicas'] == null ? undefined : json['replicas'],
        'cpuLimit': json['cpuLimit'] == null ? undefined : ServiceCpuLimitFromJSON(json['cpuLimit']),
        'memLimit': json['memLimit'] == null ? undefined : ServiceMemLimitFromJSON(json['memLimit']),
        'cpuReservation': json['cpuReservation'] == null ? undefined : ServiceCpuReservationFromJSON(json['cpuReservation']),
        'memReservation': json['memReservation'] == null ? undefined : ServiceMemReservationFromJSON(json['memReservation']),
        'ports': json['ports'] == null ? undefined : json['ports'],
        'httpPort': json['httpPort'] == null ? undefined : json['httpPort'],
        'command': json['command'] == null ? undefined : json['command'],
        'entrypoint': json['entrypoint'] == null ? undefined : json['entrypoint'],
        'healthcheck': json['healthcheck'] == null ? undefined : (mapValues(json['healthcheck'], ServiceHealthcheckValueFromJSON)),
        'restart': json['restart'] == null ? undefined : json['restart'],
        'forwardedUnscanned': json['forwardedUnscanned'] == null ? undefined : json['forwardedUnscanned'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ServiceToJSON(json: any): Service {
    return ServiceToJSONTyped(json, false);
}

export function ServiceToJSONTyped(value?: Omit<Service, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deployment': value['deployment'],
        'name': value['name'],
        'image': value['image'],
        'replicas': value['replicas'],
        'cpuLimit': ServiceCpuLimitToJSON(value['cpuLimit']),
        'memLimit': ServiceMemLimitToJSON(value['memLimit']),
        'cpuReservation': ServiceCpuReservationToJSON(value['cpuReservation']),
        'memReservation': ServiceMemReservationToJSON(value['memReservation']),
        'ports': value['ports'],
        'httpPort': value['httpPort'],
        'command': value['command'],
        'entrypoint': value['entrypoint'],
        'healthcheck': value['healthcheck'] == null ? undefined : (mapValues(value['healthcheck'], ServiceHealthcheckValueToJSON)),
        'restart': value['restart'],
        'forwardedUnscanned': value['forwardedUnscanned'],
    };
}

