/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceInstanceObservedUsageBytes } from './ServiceInstanceObservedUsageBytes';
import {
    ServiceInstanceObservedUsageBytesFromJSON,
    ServiceInstanceObservedUsageBytesFromJSONTyped,
    ServiceInstanceObservedUsageBytesToJSON,
    ServiceInstanceObservedUsageBytesToJSONTyped,
} from './ServiceInstanceObservedUsageBytes';
import type { SealedSecret } from './SealedSecret';
import {
    SealedSecretFromJSON,
    SealedSecretFromJSONTyped,
    SealedSecretToJSON,
    SealedSecretToJSONTyped,
} from './SealedSecret';
import type { ServiceInstanceCapacityBytes } from './ServiceInstanceCapacityBytes';
import {
    ServiceInstanceCapacityBytesFromJSON,
    ServiceInstanceCapacityBytesFromJSONTyped,
    ServiceInstanceCapacityBytesToJSON,
    ServiceInstanceCapacityBytesToJSONTyped,
} from './ServiceInstanceCapacityBytes';

/**
 * 
 * @export
 * @interface ServiceInstance
 */
export interface ServiceInstance {
    /**
     * Operator-facing handle, unique across the estate: `pg17-1`, `mysql80-1`.
     * @type {string}
     * @memberof ServiceInstance
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstance
     */
    kind?: ServiceInstanceKindEnum;
    /**
     * The major version this engine *is*, as the catalogue names it: `17`, `16`,
     * `11.8`, `8.4`, `8.0`.
     * @type {string}
     * @memberof ServiceInstance
     */
    majorVersion?: string;
    /**
     * The exact image this instance runs, pinned — never a floating upstream tag.
     * @type {string}
     * @memberof ServiceInstance
     */
    imageRef?: string;
    /**
     * Repoint the instance at a different context.
     * @type {string}
     * @memberof ServiceInstance
     */
    swarm?: string;
    /**
     * The internal overlay this engine and every sidecar bound to it share.
     * @type {string}
     * @memberof ServiceInstance
     */
    overlayNetwork?: string;
    /**
     * Moving to any state other than {@see ServiceInstanceState::Failed} clears a stale failure.
     * @type {string}
     * @memberof ServiceInstance
     */
    state?: ServiceInstanceStateEnum;
    /**
     * Why the instance failed, carried beside the state as `Machine::$failure` already does.
     * @type {string}
     * @memberof ServiceInstance
     */
    readonly failureReason?: string | null;
    /**
     * 
     * @type {ServiceInstanceCapacityBytes}
     * @memberof ServiceInstance
     */
    capacityBytes?: ServiceInstanceCapacityBytes | null;
    /**
     * 
     * @type {ServiceInstanceObservedUsageBytes}
     * @memberof ServiceInstance
     */
    observedUsageBytes?: ServiceInstanceObservedUsageBytes | null;
    /**
     * 
     * @type {Date}
     * @memberof ServiceInstance
     */
    readonly observedAt?: Date | null;
    /**
     * When the current attempt to reach `Serving` began — {@see claim()} sets it
     * on a fresh row and {@see markInFlight()} again on an upgrade's re-entry into
     * `Healthchecking`; null once the row is `Serving`, `Failed`, or anything else
     * that means nothing is still trying.
     * @type {Date}
     * @memberof ServiceInstance
     */
    readonly inFlightSince?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ServiceInstance
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof ServiceInstance
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceInstance
     */
    readonly updatedAt?: Date | null;
    /**
     * `postgres 17`, `mysql 8.0` — the catalogue entry this instance serves.
     * @type {string}
     * @memberof ServiceInstance
     */
    readonly catalogueEntry?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceInstance
     */
    readonly serving?: boolean;
    /**
     * Dispatched so long ago that whatever was carrying it is gone.
     * @type {boolean}
     * @memberof ServiceInstance
     */
    readonly inFlightStale?: boolean;
    /**
     * 
     * @type {SealedSecret}
     * @memberof ServiceInstance
     */
    adminCredential?: SealedSecret;
}


/**
 * @export
 */
export const ServiceInstanceKindEnum = {
    Postgres: 'postgres',
    Mariadb: 'mariadb',
    Mysql: 'mysql',
    Garage: 'garage'
} as const;
export type ServiceInstanceKindEnum = typeof ServiceInstanceKindEnum[keyof typeof ServiceInstanceKindEnum];

/**
 * @export
 */
export const ServiceInstanceStateEnum = {
    Requested: 'requested',
    Deploying: 'deploying',
    Healthchecking: 'healthchecking',
    Serving: 'serving',
    Draining: 'draining',
    Retired: 'retired',
    Failed: 'failed'
} as const;
export type ServiceInstanceStateEnum = typeof ServiceInstanceStateEnum[keyof typeof ServiceInstanceStateEnum];


/**
 * Check if a given object implements the ServiceInstance interface.
 */
export function instanceOfServiceInstance(value: object): value is ServiceInstance {
    return true;
}

export function ServiceInstanceFromJSON(json: any): ServiceInstance {
    return ServiceInstanceFromJSONTyped(json, false);
}

export function ServiceInstanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceInstance {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'majorVersion': json['majorVersion'] == null ? undefined : json['majorVersion'],
        'imageRef': json['imageRef'] == null ? undefined : json['imageRef'],
        'swarm': json['swarm'] == null ? undefined : json['swarm'],
        'overlayNetwork': json['overlayNetwork'] == null ? undefined : json['overlayNetwork'],
        'state': json['state'] == null ? undefined : json['state'],
        'failureReason': json['failureReason'] == null ? undefined : json['failureReason'],
        'capacityBytes': json['capacityBytes'] == null ? undefined : ServiceInstanceCapacityBytesFromJSON(json['capacityBytes']),
        'observedUsageBytes': json['observedUsageBytes'] == null ? undefined : ServiceInstanceObservedUsageBytesFromJSON(json['observedUsageBytes']),
        'observedAt': json['observedAt'] == null ? undefined : (new Date(json['observedAt'])),
        'inFlightSince': json['inFlightSince'] == null ? undefined : (new Date(json['inFlightSince'])),
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'catalogueEntry': json['catalogueEntry'] == null ? undefined : json['catalogueEntry'],
        'serving': json['serving'] == null ? undefined : json['serving'],
        'inFlightStale': json['inFlightStale'] == null ? undefined : json['inFlightStale'],
        'adminCredential': json['adminCredential'] == null ? undefined : SealedSecretFromJSON(json['adminCredential']),
    };
}

export function ServiceInstanceToJSON(json: any): ServiceInstance {
    return ServiceInstanceToJSONTyped(json, false);
}

export function ServiceInstanceToJSONTyped(value?: Omit<ServiceInstance, 'failureReason'|'observedAt'|'inFlightSince'|'id'|'createdAt'|'updatedAt'|'catalogueEntry'|'serving'|'inFlightStale'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'kind': value['kind'],
        'majorVersion': value['majorVersion'],
        'imageRef': value['imageRef'],
        'swarm': value['swarm'],
        'overlayNetwork': value['overlayNetwork'],
        'state': value['state'],
        'capacityBytes': ServiceInstanceCapacityBytesToJSON(value['capacityBytes']),
        'observedUsageBytes': ServiceInstanceObservedUsageBytesToJSON(value['observedUsageBytes']),
        'adminCredential': SealedSecretToJSON(value['adminCredential']),
    };
}

