/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Nanoseconds of CPU (compose deploy.resources.limits.cpus), null = unset.
 * @export
 * @interface ServiceCpuLimit
 */
export interface ServiceCpuLimit {
}

/**
 * Check if a given object implements the ServiceCpuLimit interface.
 */
export function instanceOfServiceCpuLimit(value: object): value is ServiceCpuLimit {
    return true;
}

export function ServiceCpuLimitFromJSON(json: any): ServiceCpuLimit {
    return ServiceCpuLimitFromJSONTyped(json, false);
}

export function ServiceCpuLimitFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceCpuLimit {
    return json;
}

export function ServiceCpuLimitToJSON(json: any): ServiceCpuLimit {
    return ServiceCpuLimitToJSONTyped(json, false);
}

export function ServiceCpuLimitToJSONTyped(value?: ServiceCpuLimit | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

