/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwarmNode
 */
export interface SwarmNode {
    /**
     * 
     * @type {string}
     * @memberof SwarmNode
     */
    swarm?: string;
    /**
     * The swarm-assigned node id.
     * @type {string}
     * @memberof SwarmNode
     */
    nodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof SwarmNode
     */
    hostname?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SwarmNode
     */
    state?: string | null;
    /**
     * This node's share of the cluster's capacity, as the reconciler read it.
     * @type {{ [key: string]: string | null; }}
     * @memberof SwarmNode
     */
    capacity?: { [key: string]: string | null; };
    /**
     * 
     * @type {string}
     * @memberof SwarmNode
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof SwarmNode
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SwarmNode
     */
    readonly updatedAt?: Date | null;
}

/**
 * Check if a given object implements the SwarmNode interface.
 */
export function instanceOfSwarmNode(value: object): value is SwarmNode {
    return true;
}

export function SwarmNodeFromJSON(json: any): SwarmNode {
    return SwarmNodeFromJSONTyped(json, false);
}

export function SwarmNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwarmNode {
    if (json == null) {
        return json;
    }
    return {
        
        'swarm': json['swarm'] == null ? undefined : json['swarm'],
        'nodeId': json['nodeId'] == null ? undefined : json['nodeId'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'state': json['state'] == null ? undefined : json['state'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function SwarmNodeToJSON(json: any): SwarmNode {
    return SwarmNodeToJSONTyped(json, false);
}

export function SwarmNodeToJSONTyped(value?: Omit<SwarmNode, 'id'|'createdAt'|'updatedAt'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'swarm': value['swarm'],
        'nodeId': value['nodeId'],
        'hostname': value['hostname'],
        'state': value['state'],
        'capacity': value['capacity'],
    };
}

