/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Machine } from './Machine';
import {
    MachineFromJSON,
    MachineFromJSONTyped,
    MachineToJSON,
    MachineToJSONTyped,
} from './Machine';
import type { SwarmNode } from './SwarmNode';
import {
    SwarmNodeFromJSON,
    SwarmNodeFromJSONTyped,
    SwarmNodeToJSON,
    SwarmNodeToJSONTyped,
} from './SwarmNode';

/**
 * A Docker Swarm we can deploy onto. The trust boundary of the platform.
 * 
 * owner === null  => PLATFORM pool (shared infra we run).
 * owner !== null  => CUSTOMER BYO cluster (untrusted, outbound-only).
 * @export
 * @interface Swarm
 */
export interface Swarm {
    /**
     * Null for the platform pool; set for a customer BYO cluster.
     * @type {string}
     * @memberof Swarm
     */
    owner?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Swarm
     */
    readonly kind?: SwarmKindEnum;
    /**
     * 
     * @type {string}
     * @memberof Swarm
     */
    name?: string;
    /**
     * Manager API endpoint (tcp+TLS) or SSH target.
     * @type {string}
     * @memberof Swarm
     */
    endpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof Swarm
     */
    status?: SwarmStatusEnum;
    /**
     * The address a client *outside* the cluster reaches this context's published
     * ports on — a hostname or an IP, no scheme and no port.
     * @type {string}
     * @memberof Swarm
     */
    publicHost?: string | null;
    /**
     * What this context is used for — builds, runtime, or both. Stored as the
     * enum's string values rather than a relation: it is a small fixed set, and a
     * json column needs no join to answer "where can I build?".
     * @type {Array<string>}
     * @memberof Swarm
     */
    roles?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof Swarm
     */
    lastSeenAt?: Date | null;
    /**
     * Observed capacity snapshot (cpu/mem/nodes), reconciled from the swarm —
     * whatever {@see \App\Service\Swarm\SwarmHealth::$capacity} carried at the
     * last successful probe.
     * @type {{ [key: string]: string | null; }}
     * @memberof Swarm
     */
    capacity?: { [key: string]: string | null; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof Swarm
     */
    readonly labels?: { [key: string]: string; };
    /**
     * When {@see \App\Service\Ingress\TraefikInstaller} last stood up (or
     * confirmed) the edge on this context, dispatched automatically once it
     * becomes a platform-owned runtime context.
     * @type {Date}
     * @memberof Swarm
     */
    readonly ingressInstalledAt?: Date | null;
    /**
     * What the last automatic install attempt said, when it failed. Cleared on
     * a success so the row never shows a stale complaint next to a working edge.
     * @type {string}
     * @memberof Swarm
     */
    readonly ingressError?: string | null;
    /**
     * The shared overlay that install put the edge on — the one Traefik's
     * `--providers.swarm.network` names, and therefore the only network a
     * service can be routed from.
     * @type {string}
     * @memberof Swarm
     */
    readonly ingressNetwork?: string | null;
    /**
     * When the edge was last *observed* routing — the overlay present, the edge
     * service on it, watching it, with a task running
     * ({@see \App\Service\Ingress\IngressVerifier}).
     * @type {Date}
     * @memberof Swarm
     */
    readonly ingressVerifiedAt?: Date | null;
    /**
     * What the last verification found wrong, or null when the edge was routing.
     * @type {string}
     * @memberof Swarm
     */
    readonly ingressVerificationError?: string | null;
    /**
     * 
     * @type {Array<SwarmNode>}
     * @memberof Swarm
     */
    nodes?: Array<SwarmNode>;
    /**
     * 
     * @type {Array<Machine>}
     * @memberof Swarm
     */
    machines?: Array<Machine>;
    /**
     * The revisions placed here. Mapped for the same single reason as
     * {@see self::$machines} — so a delete can let go of them — rather than as
     * a collection anything reads; {@see \App\Repository\DeploymentRepository}
     * is where a caller asks what is on a context.
     * @type {Array<string>}
     * @memberof Swarm
     */
    deployments?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Swarm
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Swarm
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Swarm
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Swarm
     */
    readonly updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof Swarm
     */
    readonly platformOwned?: boolean;
    /**
     * Whether the platform itself stood this context up, whoever currently
     * owns the row — a machine {@see \App\MessageHandler\ProvisionMachineHandler}
     * provisioned, running this platform's own trusted image, versus a
     * customer's own cluster registered straight through
     * {@see \App\Controller\Admin\SwarmController}.
     * @type {boolean}
     * @memberof Swarm
     */
    readonly platformProvisioned?: boolean;
    /**
     * Whether a revision that publishes a port can be routed here.
     * @type {boolean}
     * @memberof Swarm
     */
    readonly workingEdge?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Swarm
     */
    readonly deleted?: boolean;
}


/**
 * @export
 */
export const SwarmKindEnum = {
    Platform: 'platform',
    Customer: 'customer'
} as const;
export type SwarmKindEnum = typeof SwarmKindEnum[keyof typeof SwarmKindEnum];

/**
 * @export
 */
export const SwarmStatusEnum = {
    Reachable: 'reachable',
    Unreachable: 'unreachable',
    Draining: 'draining'
} as const;
export type SwarmStatusEnum = typeof SwarmStatusEnum[keyof typeof SwarmStatusEnum];


/**
 * Check if a given object implements the Swarm interface.
 */
export function instanceOfSwarm(value: object): value is Swarm {
    return true;
}

export function SwarmFromJSON(json: any): Swarm {
    return SwarmFromJSONTyped(json, false);
}

export function SwarmFromJSONTyped(json: any, ignoreDiscriminator: boolean): Swarm {
    if (json == null) {
        return json;
    }
    return {
        
        'owner': json['owner'] == null ? undefined : json['owner'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'name': json['name'] == null ? undefined : json['name'],
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'status': json['status'] == null ? undefined : json['status'],
        'publicHost': json['publicHost'] == null ? undefined : json['publicHost'],
        'roles': json['roles'] == null ? undefined : json['roles'],
        'lastSeenAt': json['lastSeenAt'] == null ? undefined : (new Date(json['lastSeenAt'])),
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'ingressInstalledAt': json['ingressInstalledAt'] == null ? undefined : (new Date(json['ingressInstalledAt'])),
        'ingressError': json['ingressError'] == null ? undefined : json['ingressError'],
        'ingressNetwork': json['ingressNetwork'] == null ? undefined : json['ingressNetwork'],
        'ingressVerifiedAt': json['ingressVerifiedAt'] == null ? undefined : (new Date(json['ingressVerifiedAt'])),
        'ingressVerificationError': json['ingressVerificationError'] == null ? undefined : json['ingressVerificationError'],
        'nodes': json['nodes'] == null ? undefined : ((json['nodes'] as Array<any>).map(SwarmNodeFromJSON)),
        'machines': json['machines'] == null ? undefined : ((json['machines'] as Array<any>).map(MachineFromJSON)),
        'deployments': json['deployments'] == null ? undefined : json['deployments'],
        'id': json['id'] == null ? undefined : json['id'],
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'platformOwned': json['platformOwned'] == null ? undefined : json['platformOwned'],
        'platformProvisioned': json['platformProvisioned'] == null ? undefined : json['platformProvisioned'],
        'workingEdge': json['workingEdge'] == null ? undefined : json['workingEdge'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function SwarmToJSON(json: any): Swarm {
    return SwarmToJSONTyped(json, false);
}

export function SwarmToJSONTyped(value?: Omit<Swarm, 'kind'|'labels'|'ingressInstalledAt'|'ingressError'|'ingressNetwork'|'ingressVerifiedAt'|'ingressVerificationError'|'id'|'deletedAt'|'createdAt'|'updatedAt'|'platformOwned'|'platformProvisioned'|'workingEdge'|'deleted'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'owner': value['owner'],
        'name': value['name'],
        'endpoint': value['endpoint'],
        'status': value['status'],
        'publicHost': value['publicHost'],
        'roles': value['roles'],
        'lastSeenAt': value['lastSeenAt'] == null ? undefined : ((value['lastSeenAt'] as any).toISOString()),
        'capacity': value['capacity'],
        'nodes': value['nodes'] == null ? undefined : ((value['nodes'] as Array<any>).map(SwarmNodeToJSON)),
        'machines': value['machines'] == null ? undefined : ((value['machines'] as Array<any>).map(MachineToJSON)),
        'deployments': value['deployments'],
    };
}

