/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAvatarPhoto
 */
export interface UserAvatarPhoto {
    /**
     * Base64 of the raw image bytes — see {@see User::getAvatarPhoto()} for why text rather than a BLOB.
     * @type {string}
     * @memberof UserAvatarPhoto
     */
    readonly photo?: string;
    /**
     * The media type sniffed from the bytes ({@see \App\Service\DirectoryPhoto}),
     * nullable like the old `avatar_photo_type` column was: bytes can be stored
     * without a type, and {@see \App\Controller\AvatarController} falls back to
     * `application/octet-stream`.
     * @type {string}
     * @memberof UserAvatarPhoto
     */
    type?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserAvatarPhoto
     */
    readonly id?: string;
}

/**
 * Check if a given object implements the UserAvatarPhoto interface.
 */
export function instanceOfUserAvatarPhoto(value: object): value is UserAvatarPhoto {
    return true;
}

export function UserAvatarPhotoFromJSON(json: any): UserAvatarPhoto {
    return UserAvatarPhotoFromJSONTyped(json, false);
}

export function UserAvatarPhotoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAvatarPhoto {
    if (json == null) {
        return json;
    }
    return {
        
        'photo': json['photo'] == null ? undefined : json['photo'],
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function UserAvatarPhotoToJSON(json: any): UserAvatarPhoto {
    return UserAvatarPhotoToJSONTyped(json, false);
}

export function UserAvatarPhotoToJSONTyped(value?: Omit<UserAvatarPhoto, 'photo'|'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

