/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VariableVersion } from './VariableVersion';
import {
    VariableVersionFromJSON,
    VariableVersionFromJSONTyped,
    VariableVersionToJSON,
    VariableVersionToJSONTyped,
} from './VariableVersion';

/**
 * 
 * @export
 * @interface Variable
 */
export interface Variable {
    /**
     * Re-home this variable. Used only when an application-scoped row follows
     * its {@see Application} across organizations — an org-shared row
     * (`$application === null`) has no application to follow and is never
     * moved this way.
     * @type {string}
     * @memberof Variable
     */
    organization?: string;
    /**
     * Null => org-shared across all of the organization's applications.
     * @type {string}
     * @memberof Variable
     */
    application?: string | null;
    /**
     * The environment variable name. ("key" is reserved in some SQL dialects.)
     * @type {string}
     * @memberof Variable
     */
    key?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Variable
     */
    sensitive?: boolean;
    /**
     * Opt-in only, and meaningless unless {@see $sensitive} is also true: whether
     * this secret is delivered to its containers as a mounted Swarm secret file
     * (plus a `<KEY>_FILE` env var naming its path) rather than as a plain `Env`
     * entry — {@see \App\Service\Deploy\StackDeployer}.
     * @type {boolean}
     * @memberof Variable
     */
    secretFileDelivery?: boolean;
    /**
     * 
     * @type {Array<VariableVersion>}
     * @memberof Variable
     */
    versions?: Array<VariableVersion>;
    /**
     * 
     * @type {string}
     * @memberof Variable
     */
    readonly id?: string;
    /**
     * 
     * @type {Date}
     * @memberof Variable
     */
    readonly deletedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Variable
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Variable
     */
    readonly updatedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof Variable
     */
    readonly orgShared?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Variable
     */
    readonly deleted?: boolean;
}

/**
 * Check if a given object implements the Variable interface.
 */
export function instanceOfVariable(value: object): value is Variable {
    return true;
}

export function VariableFromJSON(json: any): Variable {
    return VariableFromJSONTyped(json, false);
}

export function VariableFromJSONTyped(json: any, ignoreDiscriminator: boolean): Variable {
    if (json == null) {
        return json;
    }
    return {
        
        'organization': json['organization'] == null ? undefined : json['organization'],
        'application': json['application'] == null ? undefined : json['application'],
        'key': json['key'] == null ? undefined : json['key'],
        'sensitive': json['sensitive'] == null ? undefined : json['sensitive'],
        'secretFileDelivery': json['secretFileDelivery'] == null ? undefined : json['secretFileDelivery'],
        'versions': json['versions'] == null ? undefined : ((json['versions'] as Array<any>).map(VariableVersionFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'orgShared': json['orgShared'] == null ? undefined : json['orgShared'],
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

export function VariableToJSON(json: any): Variable {
    return VariableToJSONTyped(json, false);
}

export function VariableToJSONTyped(value?: Omit<Variable, 'id'|'deletedAt'|'createdAt'|'updatedAt'|'orgShared'|'deleted'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'organization': value['organization'],
        'application': value['application'],
        'key': value['key'],
        'sensitive': value['sensitive'],
        'secretFileDelivery': value['secretFileDelivery'],
        'versions': value['versions'] == null ? undefined : ((value['versions'] as Array<any>).map(VariableVersionToJSON)),
    };
}

