/* tslint:disable */
/* eslint-disable */
/**
 * someones.computer API
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';
import type { Variable } from './Variable';
import {
    VariableFromJSON,
    VariableFromJSONTyped,
    VariableToJSON,
    VariableToJSONTyped,
} from './Variable';

/**
 * 
 * @export
 * @interface VariableVersion
 */
export interface VariableVersion {
    /**
     * 
     * @type {Variable}
     * @memberof VariableVersion
     */
    variable?: Variable;
    /**
     * 
     * @type {number}
     * @memberof VariableVersion
     */
    version?: number;
    /**
     * Encryption algorithm identifier, e.g. "xsalsa20poly1305". Sensitive only.
     * @type {string}
     * @memberof VariableVersion
     */
    readonly algo?: string | null;
    /**
     * Identifier of the key-encryption-key that wrapped this value. Sensitive only.
     * @type {string}
     * @memberof VariableVersion
     */
    readonly keyId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VariableVersion
     */
    readonly nonce?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VariableVersion
     */
    readonly ciphertext?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VariableVersion
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {User}
     * @memberof VariableVersion
     */
    createdBy?: User | null;
    /**
     * 
     * @type {string}
     * @memberof VariableVersion
     */
    readonly id?: string;
    /**
     * Populate an encrypted (sensitive) value.
     * @type {string}
     * @memberof VariableVersion
     */
    encrypted?: string;
    /**
     * Populate a plaintext (non-sensitive) value.
     * @type {string}
     * @memberof VariableVersion
     */
    plaintext?: string;
}

/**
 * Check if a given object implements the VariableVersion interface.
 */
export function instanceOfVariableVersion(value: object): value is VariableVersion {
    return true;
}

export function VariableVersionFromJSON(json: any): VariableVersion {
    return VariableVersionFromJSONTyped(json, false);
}

export function VariableVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): VariableVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'variable': json['variable'] == null ? undefined : VariableFromJSON(json['variable']),
        'version': json['version'] == null ? undefined : json['version'],
        'algo': json['algo'] == null ? undefined : json['algo'],
        'keyId': json['keyId'] == null ? undefined : json['keyId'],
        'nonce': json['nonce'] == null ? undefined : json['nonce'],
        'ciphertext': json['ciphertext'] == null ? undefined : json['ciphertext'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'createdBy': json['createdBy'] == null ? undefined : UserFromJSON(json['createdBy']),
        'id': json['id'] == null ? undefined : json['id'],
        'encrypted': json['encrypted'] == null ? undefined : json['encrypted'],
        'plaintext': json['plaintext'] == null ? undefined : json['plaintext'],
    };
}

export function VariableVersionToJSON(json: any): VariableVersion {
    return VariableVersionToJSONTyped(json, false);
}

export function VariableVersionToJSONTyped(value?: Omit<VariableVersion, 'algo'|'keyId'|'nonce'|'ciphertext'|'createdAt'|'id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'variable': VariableToJSON(value['variable']),
        'version': value['version'],
        'createdBy': UserToJSON(value['createdBy']),
        'encrypted': value['encrypted'],
        'plaintext': value['plaintext'],
    };
}

